Repository PostHog/posthog, pull requests merged in 2021-04, with the labels that each got.

#3911 Fix commandpallet test
  cypress/integration/commandPalette.js
Labels: automerge

#3919 Run Automerge as posthog-bot
  .github/workflows/automerge.yml
Labels: automerge

#3917 Are migrations safe to run on cloud?
  .github/pull_request_template.md
Labels: automerge

#3923 Revert "Increase Element model varchar limits"
  latest_migrations.manifest
  posthog/migrations/0144_increase_element_varchars.py
  posthog/models/element.py
Labels: automerge

#3925 Update autocapture label to be more descriptive
  frontend/src/scenes/ingestion/panels/FrameworkGrid.tsx
Labels: automerge

#3908 Always show event stats and add warnings
  frontend/src/scenes/events/Events.tsx
  frontend/src/scenes/events/EventsVolumeTable.tsx
  frontend/src/scenes/events/PropertiesVolumeTable.tsx
Labels: automerge

#3950 Fixes project settings not loading
  frontend/src/scenes/project/Settings/TestAccountFiltersConfig.tsx
  frontend/src/scenes/project/Settings/WebhookIntegration.tsx
Labels: release-1.24.0

#3964 Revert "Update autocapture label to be more descriptive"
  frontend/src/scenes/ingestion/panels/FrameworkGrid.tsx
Labels: automerge

#3670 Highlight automatic changes to date range filters
  frontend/src/global.scss
  frontend/src/lib/components/IntervalFilter/IntervalFilter.js
  frontend/src/lib/components/IntervalFilter/intervalFilterLogic.js
  frontend/src/scenes/insights/DateFilter/dateFilterLogic.ts
  frontend/src/scenes/insights/DateFilter/index.scss
  frontend/src/scenes/insights/DateFilter/index.tsx
Labels: UI/UX, analytics-filters, core-experience

#3962 Refactor funnel filters & fix flexbox sizing
  frontend/src/lib/components/PropertyFilters/PropertyFilterButton.tsx
  frontend/src/lib/components/PropertyFilters/PropertyFilters.js
  frontend/src/scenes/insights/ActionFilter/ActionFilterRow.js
  frontend/src/scenes/insights/ActionFilter/ActionFilterRow.scss
  frontend/src/scenes/insights/ActionFilter/MathPropertySelector.js
  frontend/src/scenes/insights/ActionFilter/MathSelector.js
Labels: analytics-filters, core-experience

#3961 Lifecycle toggle
  frontend/src/scenes/insights/InsightTabs/TrendTab/TrendTab.scss
  frontend/src/scenes/insights/InsightTabs/TrendTab/TrendTab.tsx
  frontend/src/scenes/trends/trendsLogic.ts
  frontend/src/types.ts
Labels: enhancement, trends

#3988 Make new Sessions filter UI responsive
  frontend/src/lib/components/ResizableTable/index.tsx
  frontend/src/lib/components/ResizableTable/responsiveUtils.ts
  frontend/src/scenes/sessions/Sessions.scss
  frontend/src/scenes/sessions/Sessions.tsx
  frontend/src/scenes/sessions/SessionsView.tsx
Labels: UI/UX, analytics-filters, core-experience

#4007 Update Django to 3.1.8 (and related)
  .github/workflows/ci-backend.yml
  dev.Dockerfile
  ee/api/hooks.py
  ee/api/test/test_hooks.py
  ee/api/test/test_organization.py
  latest_migrations.manifest
  posthog/api/action.py
  posthog/api/cohort.py
  posthog/api/dashboard.py
  posthog/api/element.py
  posthog/api/event.py
  posthog/api/feature_flag.py
  posthog/api/organization.py
  posthog/api/organization_invite.py
  posthog/api/organization_member.py
  posthog/api/person.py
  posthog/api/personal_api_key.py
  posthog/api/team.py
  posthog/api/test/test_annotation.py
  posthog/api/test/test_authentication.py
  posthog/api/test/test_feature_flag.py
  posthog/api/test/test_organization.py
  posthog/api/test/test_organization_invites.py
  posthog/api/test/test_person.py
  posthog/api/test/test_plugin.py
  posthog/demo/__init__.py
  posthog/migrations/0144_update_django_3_1_8.py
  posthog/models/action_step.py
  posthog/models/cohort.py
  posthog/models/dashboard.py
  posthog/models/dashboard_item.py
  posthog/models/element.py
  posthog/models/event.py
  posthog/models/feature_flag.py
  posthog/models/organization.py
  posthog/models/person.py
  posthog/models/plugin.py
  posthog/models/session_recording_event.py
  posthog/models/sessions_filter.py
  posthog/models/team.py
  posthog/permissions.py
  posthog/templatetags/posthog_assets.py
  production.Dockerfile
  requirements-dev.in
  requirements-dev.txt
  requirements.in
  requirements.txt
Labels: security, tech debt

#4047 Update README.md
  README.md
Labels: automerge

#3825 #3765 Show cohort for bar chart (Insights > Trends)
  ee/clickhouse/queries/trends/normal.py
  frontend/src/scenes/insights/LineGraph.js
  frontend/src/scenes/trends/PersonModal.tsx
  frontend/src/scenes/trends/trendsLogic.ts
  frontend/src/scenes/trends/viz/ActionsBarValueGraph.tsx
  frontend/src/scenes/trends/viz/ActionsLineGraph.tsx
  frontend/src/scenes/trends/viz/ActionsPie.tsx
  posthog/queries/test/test_trends.py
Labels: cohorts, enhancement, trends

#4157 Feat/ph home updates
  frontend/src/global.scss
  frontend/src/scenes/onboarding/home/sections/DiscoverInsight.tsx
Labels: automerge
