Repository PostHog/posthog, pull requests merged in 2021-05, with the labels that each got.

#4204 Warn before running all tests
  bin/tests
Labels: automerge

#4207 Reorganize files in frontend/src/scenes/insights/
  .ts-strict-blacklist
  frontend/src/scenes/dashboard/DashboardItem.tsx
  frontend/src/scenes/insights/ActionFilter/ActionFilter.tsx
  frontend/src/scenes/insights/ActionFilter/ActionFilterRow.tsx
  frontend/src/scenes/insights/ActionFilter/Sortable.tsx
  frontend/src/scenes/insights/ActionSelectInfo/ActionSelectInfo.tsx
  frontend/src/scenes/insights/ActionSelectInfo/index.ts
  frontend/src/scenes/insights/BreakdownFilter/BreakdownFilter.js
  frontend/src/scenes/insights/BreakdownFilter/index.js
  frontend/src/scenes/insights/EmptyStates/EmptyStates.tsx
  frontend/src/scenes/insights/EmptyStates/index.ts
  frontend/src/scenes/insights/InsightTabs/FunnelTab/FunnelTab.tsx
  frontend/src/scenes/insights/InsightTabs/FunnelTab/index.ts
  frontend/src/scenes/insights/InsightTabs/SessionTab.tsx
  frontend/src/scenes/insights/InsightTabs/TrendTab/TrendTab.tsx
  frontend/src/scenes/insights/InsightTabs/TrendTab/index.ts
  frontend/src/scenes/insights/InsightTabs/index.ts
  frontend/src/scenes/insights/Insights.scss
  frontend/src/scenes/insights/Insights.tsx
  frontend/src/scenes/insights/LineGraph/LineGraph.js
  frontend/src/scenes/insights/LineGraph/LineGraph.scss
  frontend/src/scenes/insights/LineGraph/index.js
  frontend/src/scenes/insights/SaveModal/SaveModal.tsx
  frontend/src/scenes/insights/SaveModal/index.ts
  frontend/src/scenes/insights/TestAccountFilter/TestAccountFilter.tsx
  frontend/src/scenes/insights/TestAccountFilter/index.ts
  frontend/src/scenes/insights/TrendLegend/TrendLegend.tsx
  frontend/src/scenes/insights/TrendLegend/index.ts
Labels: automerge

#4233 New Insights query UI, Option B
  frontend/src/lib/components/PropertyFilters/PropertyFilters.js
  frontend/src/lib/components/PropertyFilters/components/FilterRow.js
  frontend/src/lib/components/PropertyFilters/components/OperatorValueSelect.tsx
  frontend/src/lib/components/PropertyFilters/components/PropertyFilter.tsx
  frontend/src/lib/components/PropertyFilters/components/PropertyFilterButton.tsx
  frontend/src/lib/components/PropertyFilters/components/PropertyFiltersDisplay.tsx
  frontend/src/lib/components/PropertyFilters/components/PropertySelect.tsx
  frontend/src/lib/components/PropertyFilters/components/PropertyValue.js
  frontend/src/lib/components/PropertyFilters/components/TabbedPropertyFilter.tsx
  frontend/src/lib/components/PropertyFilters/components/UnifiedPropertyFilter.tsx
  frontend/src/lib/components/PropertyFilters/index.js
  frontend/src/lib/components/PropertyKeyInfo.tsx
  frontend/src/lib/components/SelectBox.tsx
  frontend/src/lib/components/SelectGradientOverflow.tsx
  frontend/src/scenes/experimentation/FeatureFlags.tsx
  frontend/src/scenes/insights/ActionFilter/ActionFilterRow/index.tsx
  frontend/src/scenes/sessions/filters/DurationFilter.tsx
  frontend/src/scenes/sessions/filters/EventPropertyFilter.tsx
  frontend/src/scenes/sessions/filters/UserFilter.tsx
Labels: UI/UX, analytics-filters, core-experience

#4248 Fix date range component in insights
  frontend/src/scenes/insights/InsightDateFilter/index.scss
  frontend/src/scenes/insights/InsightDateFilter/index.tsx
  frontend/src/scenes/insights/InsightDateFilter/insightDateFilterLogic.ts
  frontend/src/scenes/insights/InsightTabs/InsightDisplayConfig.tsx
  frontend/src/scenes/insights/insightCommandLogic.ts
Labels: P0, bug

#4261 speed up autoplay, scroll more slides
  frontend/src/scenes/onboarding/home/sections/PostHogLessons.tsx
Labels: automerge

#4286 Revert dashboard item view
  cypress/integration/dashboard.js
  frontend/src/lib/components/SaveToDashboard/SaveToDashboard.tsx
  frontend/src/scenes/dashboard/Dashboard.scss
  frontend/src/scenes/dashboard/DashboardItem.tsx
  frontend/src/scenes/dashboard/DashboardItemHeader.tsx
  frontend/src/scenes/funnels/funnelLogic.js
  frontend/src/scenes/insights/InsightHistoryPanel/InsightHistoryPanel.tsx
  frontend/src/scenes/insights/Insights.tsx
  frontend/src/scenes/insights/insightLogic.ts
  frontend/src/scenes/onboarding/home/sections/DiscoverInsight.tsx
  frontend/src/scenes/paths/pathsLogic.ts
  frontend/src/scenes/retention/RetentionLineGraph.tsx
  frontend/src/scenes/retention/RetentionTable.tsx
  frontend/src/scenes/retention/retentionTableLogic.ts
  frontend/src/scenes/sceneLogic.ts
  frontend/src/scenes/trends/trendsLogic.ts
  frontend/src/scenes/trends/viz/ActionsLineGraph.tsx
Labels: release-1.25.0

#4287 Fix empty /personalization due to personalizationLogic error
  frontend/src/scenes/onboarding/personalizationLogic.ts
Labels: release-1.25.0

#4352 fix link
  frontend/src/scenes/onboarding/home/sections/PostHogLessons.tsx
Labels: automerge

#4383 update recent analyses height for small screens
  frontend/src/scenes/onboarding/home/Home.scss
Labels: automerge

#4384 Update recent analysis container size
  frontend/src/scenes/onboarding/home/Home.scss
Labels: automerge

#4385 show dashboard items if there are no recent items
  frontend/src/scenes/insights/InsightHistoryPanel/InsightHistoryPanel.tsx
  frontend/src/scenes/onboarding/home/sections/DiscoverInsight.tsx
Labels: automerge

#4386 update conditional - only show skeleton if both groups are loading
  frontend/src/scenes/insights/InsightHistoryPanel/InsightHistoryPanel.tsx
  frontend/src/scenes/onboarding/home/sections/DiscoverInsight.tsx
Labels: automerge

#4450 Shadows on insights cards
  frontend/src/scenes/insights/Insights.scss
  frontend/src/vars.scss
Labels: extra merch

#4487 Adjust click area of copy component in FF
  frontend/src/lib/components/CopyToClipboard.tsx
  frontend/src/scenes/experimentation/FeatureFlags.tsx
Labels: UI/UX

#4544 Redefined shadow variable fixes
  .eslintrc.js
  frontend/src/lib/components/PropertyFilters/components/OperatorValueSelect.tsx
  frontend/src/lib/logic/selectBoxLogic.ts
  frontend/src/scenes/insights/InsightDateFilter/InsightDateFilter.tsx
  frontend/src/scenes/insights/InsightDateFilter/index.ts
  frontend/src/scenes/insights/InsightTabs/FunnelTab/FunnelTab.tsx
  frontend/src/scenes/insights/InsightTabs/RetentionTab.tsx
  frontend/src/scenes/insights/InsightTabs/RetentionTabHorizontal.tsx
  frontend/src/scenes/insights/InsightTabs/TrendTab/Formula.tsx
  frontend/src/scenes/insights/LineGraph/LineGraph.js
  frontend/src/scenes/insights/SaveModal/SaveModal.tsx
  frontend/src/scenes/persons/MergePerson.tsx
  frontend/src/scenes/sessions/SessionDetails.tsx
  frontend/src/scenes/sessions/filters/DurationFilter.tsx
  frontend/src/scenes/sessions/filters/EditFiltersPanel.tsx
  frontend/src/scenes/sessions/filters/EventPropertyFilter.tsx
  frontend/src/scenes/sessions/filters/SessionsFilterBox.tsx
  frontend/src/scenes/sessions/filters/constants.ts
  frontend/src/scenes/sessions/filters/sessionsFiltersLogic.tsx
  frontend/src/toolbar/actions/SelectorCount.tsx
  frontend/src/toolbar/actions/UrlMatchingToggle.tsx
  frontend/src/toolbar/elements/FocusRect.tsx
  frontend/src/toolbar/utils.ts
  frontend/src/types.ts
  package.json
  yarn.lock
Labels: automerge
