Repository PostHog/posthog, pull requests merged in 2021-11, with the labels that each got.

#6418 Grammar nit: write out number, hyphenate for consistency
  .github/workflows/e2e.yml
  .github/workflows/storybook-chromatic.yml
  README.md
Labels: stale

#6695 Cleanup unused python imports
  posthog/migrations/0103_retention_remove_date.py
  posthog/models/filters/mixins/session_recordings.py
  posthog/models/filters/mixins/utils.py
  posthog/models/filters/test/test_retention_filter.py
  posthog/queries/retention.py
  posthog/queries/sessions/test/test_sessions.py
  posthog/tasks/calculate_cohort.py
  posthog/test/base.py
  posthog/test/test_event_model.py
  posthog/test/test_urls.py
  posthog/test/test_utils.py
Labels: stale

#7031 Fix dashboard empty state issues
  frontend/src/scenes/dashboard/Dashboards.tsx
  posthog/api/dashboard.py
  posthog/api/test/test_dashboard.py
  posthog/helpers/dashboard_templates.py
Labels: automerge

#7116 Add some benchmarks for stickiness
  ee/benchmarks/benchmarks.py
  posthog/models/filters/mixins/stickiness.py
  posthog/models/filters/stickiness_filter.py
Labels: performance

#7099 feat(funnels): update frontend to use new people_urls in response
  ee/clickhouse/queries/funnels/funnel.py
  frontend/src/scenes/funnels/FunnelBarGraph.tsx
  frontend/src/scenes/funnels/funnelLogic.test.ts
  frontend/src/scenes/funnels/funnelLogic.ts
  frontend/src/scenes/insights/InsightTabs/FunnelTab/FunnelStepTable.tsx
  frontend/src/scenes/insights/InsightTabs/FunnelTab/funnelStepTableUtils.tsx
  frontend/src/scenes/insights/__stories__/Funnel.stories.tsx
  frontend/src/scenes/trends/personsModalLogic.tsx
  frontend/src/types.ts
Labels: release-1.30.0

#7076 Fix feature flag edit page load
  cypress/integration/featureFlags.js
  frontend/src/scenes/feature-flags/featureFlagLogic.tsx
  posthog/settings.py
Labels: release-1.30.0

#7131 Improve icons and responsiveness of fresh top bar
  frontend/src/layout/lemonade/RedesignOptIn.scss
  frontend/src/layout/lemonade/TopBar/SitePopover.tsx
  frontend/src/layout/lemonade/TopBar/index.scss
  frontend/src/lib/components/HelpButton/HelpButton.scss
  frontend/src/lib/components/HelpButton/HelpButton.tsx
  frontend/src/lib/components/LemonSwitch/LemonSwitch.scss
  frontend/src/lib/components/icons.tsx
Labels: release-1.30.0

#7136 Fix sidebar and breadcrumbs logic
  frontend/src/layout/lemonade/Breadcrumbs/Breadcrumbs.scss
  frontend/src/layout/lemonade/Breadcrumbs/Breadcrumbs.tsx
  frontend/src/layout/lemonade/Breadcrumbs/breadcrumbsLogic.tsx
  frontend/src/scenes/sceneLogic.ts
  frontend/src/scenes/scenes.ts
Labels: release-1.30.0

#6982 Update person version on person updates and send value to Kafka
  plugin-server/src/types.ts
  plugin-server/src/utils/db/db.ts
  plugin-server/src/utils/db/utils.ts
  plugin-server/src/worker/ingestion/process-event.ts
  plugin-server/tests/clickhouse/postgres-parity.test.ts
  plugin-server/tests/shared/process-event.ts
Labels: release-1.30.0

#7135 Show delete button on single filter in Recordings
  frontend/src/scenes/insights/ActionFilter/ActionFilterRow/ActionFilterRow.tsx
  frontend/src/scenes/insights/InsightTabs/FunnelTab/FunnelTab.tsx
Labels: release-1.30.0

#6952 Update pull_request_template.md
  .github/pull_request_template.md
Labels: stale

#7148 Groups: Disable person modal if breaking down by groups
  frontend/src/scenes/trends/trendsLogic.ts
  frontend/src/types.ts
Labels: release-1.30.0

#7141 Handling for plugin server restarts in historical exports
  plugin-server/src/worker/vm/upgrades/historical-export/export-historical-events.ts
  plugin-server/src/worker/vm/upgrades/historical-export/utils.ts
Labels: release-1.30.0

#7139 [funnel trends] make sure required parameter is being passed
  frontend/src/scenes/insights/utils/cleanFilters.ts
Labels: release-1.30.0

#7142 Better handling of current project edge cases
  frontend/src/layout/ErrorProjectUnavailable.tsx
  frontend/src/layout/lemonade/ProjectSwitcher.tsx
  frontend/src/layout/lemonade/SideBar/SideBar.tsx
  frontend/src/lib/api.mock.ts
  frontend/src/lib/components/LemonButton/LemonButton.scss
  frontend/src/lib/components/LemonRow/LemonRow.scss
  frontend/src/scenes/App.tsx
  frontend/src/scenes/organization/CreateOrganizationModal.tsx
  frontend/src/scenes/organizationLogic.test.ts
  frontend/src/scenes/organizationLogic.tsx
  frontend/src/scenes/project/CreateProjectModal.tsx
  frontend/src/scenes/sceneLogic.ts
  frontend/src/scenes/teamLogic.tsx
Labels: release-1.30.0

#7117 Speed up stickiness queries & allow aggregating/filtering by groups
  ee/clickhouse/queries/clickhouse_stickiness.py
  ee/clickhouse/queries/column_optimizer.py
  ee/clickhouse/queries/event_query.py
  ee/clickhouse/queries/stickiness/stickiness_event_query.py
  ee/clickhouse/queries/test/__snapshots__/test_stickiness.ambr
  ee/clickhouse/queries/test/test_stickiness.py
  ee/clickhouse/sql/stickiness/__init__.py
  ee/clickhouse/sql/stickiness/stickiness.py
  ee/clickhouse/sql/stickiness/stickiness_actions.py
  ee/clickhouse/sql/stickiness/stickiness_people.py
  frontend/src/scenes/insights/InsightTabs/TrendTab/TrendTab.tsx
  posthog/queries/test/test_stickiness.py
Labels: performance

#7161 Update dashboard items when saving insights
  frontend/src/models/dashboardsModel.tsx
  frontend/src/scenes/insights/insightLogic.tsx
Labels: release-1.30.0

#7163 Make project based permissioning an enterprise feature
  ee/models/license.py
Labels: release-1.30.0

#6667 Persons table schema migration
  ee/clickhouse/migrations/0021_person_table_version_column.py
  ee/clickhouse/models/person.py
  ee/clickhouse/models/test/test_person.py
  ee/clickhouse/models/test/utils/util.py
  ee/clickhouse/sql/clickhouse.py
  ee/clickhouse/sql/person.py
Labels: P0

#7251 Add benchmarks for session recording page
  ee/benchmarks/benchmarks.py
Labels: performance

#7234 Reimplement codespaces support
  .devcontainer/.env
  .devcontainer/Dockerfile
  .devcontainer/container_start.sh
  .devcontainer/devcontainer.json
  .devcontainer/docker-compose.yml
  .github/workflows/codespaces.yml
Labels: codespaces-build

#7174 Add save as button
  cypress/integration/insights.js
  frontend/src/models/dashboardItemsModel.tsx
  frontend/src/scenes/insights/InsightSaveButton.tsx
  frontend/src/scenes/insights/Insights.tsx
  frontend/src/scenes/insights/insightLogic.test.ts
  frontend/src/scenes/insights/insightLogic.tsx
  frontend/src/scenes/saved-insights/SavedInsights.tsx
Labels: team-core-experience, insights, saved-insights

#7281 Materialize has_full_snapshot in session_recording_events
  ee/clickhouse/materialized_columns/columns.py
  ee/clickhouse/materialized_columns/test/test_columns.py
  ee/clickhouse/migrations/0006_session_recording_events.py
  ee/clickhouse/migrations/0021_session_recording_events_materialize_full_snapshot.py
  ee/clickhouse/queries/session_recordings/clickhouse_session_recording_list.py
  ee/clickhouse/queries/session_recordings/test/__snapshots__/test_clickhouse_session_recording_list.ambr
  ee/clickhouse/queries/session_recordings/test/test_clickhouse_session_recording_list.py
  ee/clickhouse/sql/session_recording_events.py
  ee/clickhouse/util.py
  posthog/api/test/test_session_recordings.py
  posthog/queries/session_recordings/test/test_session_recording_list.py
Labels: performance

#7248 Only include events in session recording query when needed
  ee/clickhouse/queries/session_recordings/clickhouse_session_recording_list.py
  ee/clickhouse/queries/session_recordings/test/__snapshots__/test_clickhouse_session_recording_list.ambr
  ee/clickhouse/queries/session_recordings/test/test_clickhouse_session_recording_list.py
Labels: performance
