Repository PostHog/posthog, pull requests merged in 2021-09, with the labels that each got.

#5769 Persons modal polish
  frontend/src/lib/components/Link.tsx
  frontend/src/scenes/persons/PersonHeader.tsx
  frontend/src/scenes/persons/PersonsTable.tsx
  frontend/src/scenes/retention/RetentionLineGraph.tsx
  frontend/src/scenes/retention/RetentionTable.tsx
  frontend/src/scenes/trends/PersonModal.tsx
Labels: stale

#5835 Pull docker before starting
  package.json
Labels: automerge

#5757 Adjust `SessionRecordingsButton` behavior for a single recording
  frontend/src/lib/components/Popup/Popup.tsx
  frontend/src/scenes/persons/Person.cy-spec.js
  frontend/src/scenes/sessions/SessionRecordingsButton.scss
  frontend/src/scenes/sessions/SessionRecordingsButton.tsx
  frontend/src/scenes/sessions/Sessions.cy-spec.js
Labels: stale

#5770 Optimize UI around session recordings
  frontend/src/lib/components/CommandPalette/commandPaletteLogic.ts
  frontend/src/lib/components/ResizableTable/index.tsx
  frontend/src/lib/components/Tooltip.tsx
  frontend/src/lib/utils.test.js
  frontend/src/lib/utils.tsx
  frontend/src/scenes/project/Settings/SessionRecording.tsx
  frontend/src/scenes/project/Settings/index.tsx
  frontend/src/scenes/sessions/SessionsView.tsx
Labels: stale

#5720 Job triggering interface
  frontend/src/lib/constants.tsx
  frontend/src/lib/utils.tsx
  frontend/src/scenes/plugins/Plugins.scss
  frontend/src/scenes/plugins/edit/PluginDrawer.tsx
  frontend/src/scenes/plugins/edit/PluginField.tsx
  frontend/src/scenes/plugins/edit/PluginSource.tsx
  frontend/src/scenes/plugins/edit/interface-jobs/PluginJobConfiguration.tsx
  frontend/src/scenes/plugins/edit/interface-jobs/PluginJobOptions.tsx
  frontend/src/scenes/plugins/edit/interface-jobs/interfaceJobsLogic.ts
  frontend/src/types.ts
  latest_migrations.manifest
  posthog/api/plugin.py
  posthog/api/test/test_plugin.py
  posthog/migrations/0166_plugin_public_jobs.py
  posthog/models/plugin.py
Labels: stale

#5929 Bugfix: cohort calculating race condition
  ee/clickhouse/sql/cohort.py
  posthog/models/cohort.py
  posthog/tasks/calculate_cohort.py
Labels: release-1.28.0

#5933 remove debug line
  frontend/src/scenes/cohorts/cohortLogic.tsx
Labels: automerge

#5931 Polish persons modal + graph tooltip
  frontend/src/lib/components/CopyToClipboard.tsx
  frontend/src/lib/components/InsightLabel/InsightLabel.scss
  frontend/src/scenes/insights/InsightTooltip/InsightTooltip.scss
  frontend/src/scenes/insights/InsightTooltip/InsightTooltip.tsx
  frontend/src/scenes/persons/Person.tsx
  frontend/src/scenes/persons/PersonsTable.tsx
  frontend/src/scenes/trends/PersonModal.tsx
Labels: release-1.28.0

#5923 Fix breakdown people modal postgres
  posthog/api/test/test_action_people.py
  posthog/api/test/test_person.py
  posthog/queries/base.py
Labels: release-1.28.0

#5944 Cohort calculation race condition
  posthog/api/cohort.py
Labels: release-1.28.0

#6037 Cleanup Insights.tsx
  frontend/src/scenes/insights/InsightContainer.tsx
  frontend/src/scenes/insights/Insights.tsx
Labels: tech debt

#5940 Fix eventUsageLogic.ts error if properties is an object
  frontend/src/lib/utils/eventUsageLogic.ts
Labels: release-1.28.1

#5875 Reload 4 dashboard items at a time
  frontend/src/models/dashboardItemsModel.tsx
  frontend/src/scenes/dashboard/DashboardItem.tsx
  frontend/src/scenes/dashboard/DashboardItems.tsx
  frontend/src/scenes/dashboard/dashboardLogic.tsx
  frontend/src/scenes/events/definitions/InsightChart.tsx
  frontend/src/scenes/events/definitions/definitionDrawerLogic.ts
  frontend/src/scenes/funnels/Funnel.tsx
  frontend/src/scenes/funnels/funnelLogic.test.ts
  frontend/src/scenes/funnels/funnelLogic.ts
  frontend/src/scenes/funnels/funnelUtils.ts
  frontend/src/scenes/insights/InsightHistoryPanel/InsightHistoryPanel.tsx
  frontend/src/scenes/insights/InsightRouter.tsx
  frontend/src/scenes/insights/InsightTabs/RetentionTab.tsx
  frontend/src/scenes/insights/Insights.tsx
  frontend/src/scenes/insights/utils.ts
  frontend/src/scenes/paths/pathsLogic.ts
  frontend/src/scenes/retention/RetentionTable.tsx
  frontend/src/scenes/retention/retentionTableLogic.ts
  frontend/src/scenes/saved-insights/SavedInsights.tsx
  frontend/src/scenes/trends/Trends.tsx
  frontend/src/scenes/trends/trendsLogic.ts
  frontend/src/types.ts
Labels: release-1.28.1

#6074 Header label styling for all trend graphs + tab switching bug
  frontend/src/scenes/funnels/FunnelCanvasLabel.scss
  frontend/src/scenes/funnels/funnelLogic.ts
  frontend/src/scenes/insights/Insights.tsx
Labels: release-1.28.1

#6126 Funnel bin count not persisting
  frontend/src/scenes/funnels/funnelLogic.ts
  frontend/src/scenes/insights/InsightTabs/FunnelTab/FunnelBinsPicker.tsx
Labels: funnels, saved-insights
