Repository PostHog/posthog, pull requests merged in 2021-07, with the labels that each got.

#5135 Return correct chart tooltip date
  ee/clickhouse/queries/funnels/funnel_trends.py
  ee/clickhouse/queries/funnels/test/test_funnel_trends.py
Labels: core-experience

#5269 Use flex-basis instead of percentage for funnel bar sizing
  frontend/src/scenes/cohorts/CohortV2/cohortLogic.tsx
  frontend/src/scenes/funnels/FunnelBarGraph.tsx
Labels: release-1.27.0

#5300 Remove funnel step checkboxes, logic, and associated types
  frontend/src/lib/components/InsightLabel/index.tsx
  frontend/src/scenes/funnels/FunnelBarGraph.tsx
  frontend/src/scenes/funnels/funnelLogic.ts
  frontend/src/scenes/insights/InsightTabs/FunnelTab/FunnelStepTable.tsx
  frontend/src/scenes/insights/InsightsTable/components/SeriesToggleWrapper.tsx
  frontend/src/types.ts
Labels: release-1.27.0

#5320 Fix various histogram release bugs
  frontend/src/scenes/funnels/FunnelHistogram.tsx
  frontend/src/scenes/funnels/funnelLogic.ts
  frontend/src/scenes/insights/Histogram/Histogram.scss
  frontend/src/scenes/insights/Insights.tsx
Labels: release-1.27.0

#5319 Funnel steps view: Set 'previousStep' count on first step
  frontend/src/scenes/funnels/funnelLogic.ts
Labels: release-1.27.0

#5348 Ingestion - add confirmation to skip + help button
  frontend/src/lib/constants.tsx
  frontend/src/scenes/ingestion/panels/VerificationPanel.tsx
Labels: automerge

#5296 Maintain default feature flags behavior on cloud
  posthog/settings.py
  task-definition.migration.json
  task-definition.plugins.json
  task-definition.web.json
  task-definition.worker.json
Labels: stale
