Repository PostHog/posthog, pull requests merged in 2021-03, with the labels that each got.

#3518 Fix cannot read property 0 of undefined
  frontend/src/lib/components/AppEditorLink/appUrlsLogic.js
Labels: release-1.22.0

#3528 Add explanation for clipboard not working on remote HTTP
  frontend/src/lib/utils.tsx
Labels: release-1.22.0

#3529 fix plugin invalid config error
  frontend/src/scenes/plugins/edit/PluginDrawer.tsx
Labels: release-1.22.0

#3530 Random fixes Mar 1
  frontend/src/scenes/ingestion/frameworks/CodeSnippet.tsx
  frontend/src/scenes/me/Settings/OptOutCapture.js
  frontend/src/scenes/project/Settings/index.tsx
Labels: release-1.22.0

#3532 Closes #3524 filters do not reset
  frontend/src/lib/components/PropertyFilters/propertyFilterLogic.js
Labels: release-1.22.0

#3533 Closes #3520 fix custom date filter dashboards
  posthog/api/test/test_dashboard.py
  posthog/models/dashboard_item.py
Labels: release-1.22.0

#3521 Disable unnecessary chart filters on retention
  frontend/src/lib/components/ChartFilter/ChartFilter.js
Labels: release-1.22.0

#3522 Parse retention timestamps to local time
  frontend/src/scenes/retention/RetentionTable.tsx
Labels: release-1.22.0

#3608 Dashboard Improvements I
  frontend/src/global.scss
  frontend/src/lib/utils/eventUsageLogic.ts
  frontend/src/models/dashboardsModel.js
  frontend/src/scenes/dashboard/Dashboard.scss
  frontend/src/scenes/dashboard/Dashboard.tsx
  frontend/src/scenes/dashboard/DashboardHeader.scss
  frontend/src/scenes/dashboard/DashboardHeader.tsx
  frontend/src/scenes/dashboard/DashboardItem.tsx
  frontend/src/scenes/dashboard/DashboardItems.scss
  frontend/src/scenes/dashboard/DashboardItems.tsx
  frontend/src/scenes/dashboard/Dashboards.tsx
  frontend/src/scenes/dashboard/dashboardLogic.js
  frontend/src/scenes/insights/InsightHistoryPanel/InsightHistoryPanel.tsx
  frontend/src/scenes/sceneLogic.ts
Labels: UI/UX, dashboards

#3655 Default event property usage to false
  frontend/src/scenes/events/Events.tsx
  frontend/src/types.ts
  posthog/api/user.py
  posthog/celery.py
  posthog/settings.py
Labels: release

#3672 Shared dashboards fix
  frontend/src/lib/utils/eventUsageLogic.ts
  frontend/src/models/dashboardsModel.js
  frontend/src/scenes/dashboard/Dashboard.tsx
  frontend/src/scenes/dashboard/SharedDashboard.tsx
  frontend/src/scenes/dashboard/dashboardLogic.js
Labels: release-1.24.0

#3761 Custom Data Attributes in the toolbar
  .ts-strict-blacklist
  frontend/src/lib/components/AppEditorLink/appUrlsLogic.js
  frontend/src/scenes/actions/ActionEdit.js
  frontend/src/scenes/actions/ActionStep.js
  frontend/src/scenes/project/Settings/DataAttributes.tsx
  frontend/src/scenes/project/Settings/index.tsx
  frontend/src/toolbar/actions/actionsTabLogic.tsx
  frontend/src/toolbar/elements/elementsLogic.ts
  frontend/src/toolbar/elements/heatmapLogic.ts
  frontend/src/toolbar/toolbarLogic.ts
  frontend/src/toolbar/utils.ts
  frontend/src/types.ts
  latest_migrations.manifest
  package.json
  posthog/api/team.py
  posthog/api/user.py
  posthog/migrations/0140_team_data_attributes.py
  posthog/models/team.py
  yarn.lock
Labels: highlight :star:
