Repository PostHog/posthog, pull requests merged in 2021-06, with the labels that each got.

#4419 Refactoring funnel trends
  ee/clickhouse/queries/clickhouse_funnel.py
  ee/clickhouse/queries/clickhouse_funnel_base.py
  ee/clickhouse/queries/clickhouse_funnel_trends.py
  ee/clickhouse/queries/test/test_funnel.py
  ee/clickhouse/queries/test/test_funnel_trends.py
  ee/clickhouse/sql/events.py
  ee/clickhouse/sql/funnels/funnel_trend.py
  ee/tasks/test/test_calculate_cohort.py
  posthog/constants.py
  posthog/models/filters/filter.py
  posthog/models/filters/mixins/funnel_window_days.py
  posthog/models/filters/test/test_filter.py
  posthog/queries/funnel.py
  posthog/queries/test/test_funnel.py
Labels: funnels

#4619 Fix popover padding
  frontend/src/lib/components/Annotations/AnnotationMarker.scss
  frontend/src/lib/components/Annotations/AnnotationMarker.tsx
Labels: release-1.26.0

#4617 SelectBox: fix 'cannot read length of undefined'
  frontend/src/lib/components/SelectBox.tsx
Labels: release-1.26.0

#4662 Fix paths start element selector
  frontend/src/lib/components/PropertyFilters/components/PropertyValue.js
Labels: release-1.26.0

#4686 Refactor PropertyValue to TS
  frontend/src/lib/components/PropertyFilters/components/OperatorValueSelect.tsx
  frontend/src/lib/components/PropertyFilters/components/PropertyValue.js
  frontend/src/lib/components/PropertyFilters/components/PropertyValue.tsx
  frontend/src/lib/components/SelectGradientOverflow.tsx
  frontend/src/lib/constants.tsx
  frontend/src/lib/utils.tsx
  frontend/src/scenes/insights/InsightTabs/PathTab.tsx
  frontend/src/scenes/insights/InsightTabs/PathTabHorizontal.tsx
  frontend/src/scenes/paths/Paths.js
  frontend/src/scenes/paths/pathsLogic.ts
  frontend/src/scenes/trends/trendsLogic.ts
  frontend/src/types.ts
  posthog/queries/paths.py
Labels: release-1.26.0

#4651 New tooltips UI #4156
  frontend/src/lib/components/Annotations/AnnotationMarker.tsx
  frontend/src/lib/components/DateDisplay/DateDisplay.scss
  frontend/src/lib/components/DateDisplay/index.tsx
  frontend/src/lib/components/InsightLabel/InsightLabel.scss
  frontend/src/lib/components/InsightLabel/index.tsx
  frontend/src/lib/components/SeriesLetter.tsx
  frontend/src/lib/components/icons.tsx
  frontend/src/lib/utils.test.js
  frontend/src/lib/utils.tsx
  frontend/src/scenes/insights/ActionFilter/ActionFilter.tsx
  frontend/src/scenes/insights/ActionFilter/ActionFilterRow/index.scss
  frontend/src/scenes/insights/ActionFilter/ActionFilterRow/index.tsx
  frontend/src/scenes/insights/InsightTabs/TrendTab/TrendTabHorizontal.tsx
  frontend/src/scenes/insights/InsightTooltip/InsightTooltip.scss
  frontend/src/scenes/insights/InsightTooltip/index.tsx
  frontend/src/scenes/insights/LineGraph/LineGraph.js
  frontend/src/scenes/trends/trendsLogic.ts
  frontend/src/scenes/trends/viz/ActionsBarValueGraph.tsx
  frontend/src/scenes/trends/viz/ActionsLineGraph.tsx
  frontend/src/styles/global.scss
  frontend/src/types.ts
  frontend/src/vars.scss
  frontend/src/vars.scss.d.ts
Labels: highlight :star:

#4891 Add frontend local dev script for Clickhouse development
  ee/bin/docker-ch-dev-backend
  ee/bin/docker-ch-dev-web
  ee/docker-compose.ch.yml
  package.json
Labels: developer experience
