Repository PostHog/posthog, pull requests merged in 2021-12, with the labels that each got.

#7460 fixes for new short insight urls
  cypress/integration/trends.js
  frontend/src/lib/components/ChartFilter/chartFilterLogic.test.ts
  frontend/src/lib/components/IntervalFilter/intervalFilterLogic.test.ts
  frontend/src/lib/components/IntervalFilter/intervalFilterLogic.ts
  frontend/src/scenes/insights/InsightDateFilter/insightDateFilterLogic.test.ts
  frontend/src/scenes/insights/InsightDateFilter/insightDateFilterLogic.ts
Labels: bug, P1

#7483 perf(retention): add benchmark cases for retention
  ee/benchmarks/benchmarks.py
Labels: performance

#7431 feat(retention): add support for multiple breakdown props
  ee/benchmarks/benchmarks.py
  ee/clickhouse/client.py
  ee/clickhouse/models/property.py
  ee/clickhouse/queries/clickhouse_retention.py
  ee/clickhouse/queries/retention/retention_event_query.py
  ee/clickhouse/sql/retention/retention.py
  ee/clickhouse/views/test/test_clickhouse_retention.py
  posthog/api/test/test_stickiness.py
  posthog/models/filters/base_filter.py
  posthog/utils.py
Labels: performance

#7556 Performance: Add trends daily active users benchmarks
  ee/benchmarks/benchmarks.py
Labels: performance

#7587 Fix codespaces build
  .devcontainer/Dockerfile
Labels: codespaces-build

#7532 Clean up person profile picture
  frontend/src/lib/components/ProfilePicture/ProfilePicture.scss
  frontend/src/lib/components/ProfilePicture/index.tsx
  frontend/src/scenes/persons/PersonHeader.scss
  frontend/src/scenes/persons/PersonHeader.tsx
Labels: release-1.31.0

#7674 Recordings beta tag
  frontend/src/layout/navigation/SideBar/SideBar.tsx
  frontend/src/scenes/session-recordings/SessionRecordings.tsx
Labels: release-1.31.0

#7656 Last seen at enabled for self-hosted
  plugin-server/src/config/config.ts
  plugin-server/tests/shared/process-event.ts
  plugin-server/tests/worker/ingestion/team-manager.test.ts
Labels: release-1.31.0

#7672 Group analytics casing, attempt 2
  frontend/src/lib/introductions/GroupsIntroductionBanner.tsx
  frontend/src/scenes/groups/GroupsIntroduction.tsx
  frontend/src/scenes/groups/GroupsTabs.tsx
Labels: release-1.31.0

#7651 Persisted flags for release 1.31.0
  frontend/src/lib/constants.tsx
  posthog/settings.py
Labels: release-1.31.0

#7692 Unify "Group Analytics" casing completely
  frontend/src/lib/introductions/GroupsIntroductionOption.tsx
  frontend/src/scenes/groups/GroupsIntroduction.tsx
  posthog/api/property_definition.py
Labels: release-1.31.0

#7698 Fix funnel trends incomplete data points when conversion window overlaps
  frontend/src/scenes/funnels/FunnelLineGraph.tsx
  frontend/src/scenes/funnels/funnelLogic.ts
  frontend/src/scenes/funnels/funnelUtils.test.ts
  frontend/src/scenes/funnels/funnelUtils.ts
  frontend/src/scenes/insights/LineGraph/LineGraph.jsx
  frontend/src/types.ts
Labels: release-1.31.0

#7683 Use last seen timestamp
  plugin-server/src/worker/ingestion/process-event.ts
  plugin-server/src/worker/ingestion/team-manager.ts
  plugin-server/tests/worker/ingestion/team-manager.test.ts
Labels: release-1.31.0

#7703 Make heatmap error-resilient
  frontend/src/toolbar/elements/heatmapLogic.ts
Labels: release-1.31.0

#7688 Make sure private projects stay secret for those without access
  ee/api/test/test_team.py
  frontend/src/layout/navigation/ProjectSwitcher.tsx
  frontend/src/layout/navigation/TopBar/SitePopover.tsx
  frontend/src/lib/components/LemonButton/index.tsx
  posthog/api/organization.py
Labels: release-1.31.0

#7706 Async migration 0001: Change events table SAMPLE BY
  ee/clickhouse/sql/events.py
  ee/clickhouse/sql/test/__snapshots__/test_schema.ambr
  posthog/async_migrations/definition.py
  posthog/async_migrations/migrations/0001_events_sample_by.py
  posthog/async_migrations/runner.py
  posthog/async_migrations/setup.py
  posthog/async_migrations/test/test_0001_events_sample_by.py
  posthog/async_migrations/utils.py
  posthog/tasks/test/test_async_migrations.py
Labels: release-1.31.0

#7732 Add margin-left to site popover side link as a precaution
  frontend/src/layout/navigation/TopBar/TopBar.scss
Labels: release-1.31.0

#7736 Async migrations fixes 1.31.0
  bin/docker-worker-celery
  bin/start-worker
Labels: release-1.31.0

#7642 fix(retention): fix breakdown people urls
  ee/clickhouse/queries/actor_base_query.py
  ee/clickhouse/queries/retention/clickhouse_retention.py
  ee/clickhouse/queries/retention/retention_actors.py
  ee/clickhouse/queries/retention/retention_event_query.py
  ee/clickhouse/queries/test/__snapshots__/test_retention.ambr
  ee/clickhouse/queries/test/test_retention.py
  ee/clickhouse/sql/retention/retention.py
  ee/clickhouse/views/test/test_clickhouse_retention.py
  posthog/api/person.py
  posthog/models/filters/retention_filter.py
  posthog/queries/retention.py
  posthog/queries/test/test_retention.py
  posthog/utils.py
Labels: performance

#7737 Refactor where we test if Materialized Columns are enabled
  posthog/celery.py
Labels: release-1.31.0

#7744 Use a helper to get env var for saml
  ee/settings.py
Labels: release-1.31.0

#7729 Remove migration check
  frontend/src/layout/navigation/navigationLogic.ts
  posthog/api/instance_status.py
Labels: release-1.31.0

#7742 [fix] Cohort 0 count bug fix
  ee/clickhouse/models/cohort.py
  ee/clickhouse/models/test/__snapshots__/test_cohort.ambr
  ee/clickhouse/models/test/test_cohort.py
  ee/clickhouse/sql/cohort.py
Labels: release-1.31.0

#7753 perf(lifecycle): add benchmark for lifecycle
  ee/benchmarks/README.md
  ee/benchmarks/benchmarks.py
Labels: performance

#7777 Fix migration healthcheck
  posthog/tasks/async_migrations.py
Labels: patch-1.31.1

#7778 0002_events_sample_by
  ee/clickhouse/sql/events.py
  ee/clickhouse/sql/test/__snapshots__/test_schema.ambr
  posthog/async_migrations/migrations/0001_events_sample_by.py
  posthog/async_migrations/migrations/0002_events_sample_by.py
  posthog/async_migrations/test/test_0002_events_sample_by.py
Labels: patch-1.31.1

#7783 fix migration details changed but name is the same
  ee/management/commands/run_async_migrations.py
  posthog/async_migrations/setup.py
Labels: patch-1.31.1

#7786 Fix 0002 test
  posthog/async_migrations/migrations/0002_events_sample_by.py
  posthog/async_migrations/test/test_0002_events_sample_by.py
Labels: patch-1.31.1

#7813 Add benchmark for funnel query
  ee/benchmarks/benchmarks.py
  ee/clickhouse/queries/event_query.py
  ee/clickhouse/queries/funnels/test/__snapshots__/test_funnel.ambr
  ee/clickhouse/queries/funnels/test/__snapshots__/test_funnel_correlation.ambr
  ee/clickhouse/queries/funnels/test/__snapshots__/test_funnel_strict.ambr
  ee/clickhouse/queries/funnels/test/__snapshots__/test_funnel_unordered.ambr
  ee/clickhouse/queries/test/__snapshots__/test_event_query.ambr
  ee/clickhouse/queries/test/__snapshots__/test_paths.ambr
  ee/clickhouse/queries/test/__snapshots__/test_retention.ambr
  ee/clickhouse/queries/test/__snapshots__/test_trends.ambr
  ee/clickhouse/views/test/__snapshots__/test_clickhouse_experiments.ambr
  ee/clickhouse/views/test/__snapshots__/test_clickhouse_stickiness.ambr
  ee/clickhouse/views/test/__snapshots__/test_clickhouse_trends.ambr
  ee/clickhouse/views/test/funnel/__snapshots__/test_clickhouse_funnel.ambr
  ee/clickhouse/views/test/funnel/__snapshots__/test_clickhouse_funnel_unordered.ambr
Labels: performance
