Repository PostHog/posthog, pull requests merged in 2022-02, with the labels that each got.

#8258 feat(k8s): add kafka connection status to health check endpoint
  ee/kafka_client/client.py
  posthog/health.py
  posthog/test/test_health.py
  posthog/urls.py
Labels: stale

#8304 Async migrations rollback failures to update current index
  posthog/async_migrations/examples/test_with_rollback_exception.py
  posthog/async_migrations/runner.py
  posthog/async_migrations/test/test_runner.py
  posthog/async_migrations/utils.py
Labels: P1, CH migration

#8453 Iterate on performance waterfall chart
  frontend/src/lib/api.test.ts
  frontend/src/lib/api.ts
  frontend/src/lib/utils.tsx
  frontend/src/scenes/performance/WebPerformance.scss
  frontend/src/scenes/performance/WebPerformance.tsx
  frontend/src/scenes/performance/__stories__/PerformanceWaterfall.stories.tsx
  frontend/src/scenes/performance/__stories__/events.json
  frontend/src/scenes/performance/webPerformanceLogic.ts
Labels: team-core-experience, web-performance

#8420 Don't register row clicks to toggle visibility when insight is table mode
  frontend/src/scenes/insights/InsightsTable/InsightsTable.tsx
  frontend/src/scenes/trends/Trends.tsx
Labels: bug, team-core-experience

#8278 Async Migrations: If sql error include sql ran in the message + handle error col limit
  posthog/async_migrations/definition.py
  posthog/async_migrations/utils.py
Labels: P1, CH migration

#8452 Add DLQ error metrics per tag
  posthog/api/dead_letter_queue.py
Labels: stale

#8473 Async migrations errors unlimited
  latest_migrations.manifest
  posthog/async_migrations/utils.py
  posthog/migrations/0211_async_migrations_errors_length.py
  posthog/models/async_migration.py
Labels: stale

#8621 Fix recordings on funnel trends
  ee/clickhouse/queries/funnels/funnel_trends_persons.py
  ee/clickhouse/queries/funnels/test/__snapshots__/test_funnel_trends_persons.ambr
  ee/clickhouse/queries/funnels/test/test_funnel_trends_persons.py
Labels: release-1.33.0

#8727 Add `dashboard-permissions` to `PERSISTED_FEATURE_FLAGS`
  frontend/src/lib/constants.tsx
  posthog/settings/feature_flags.py
Labels: release-1.33.0

#8740 add f string to optimize
  posthog/async_migrations/migrations/0002_events_sample_by.py
Labels: release-1.33.0

#8739 fix resume api for async migrations
  posthog/api/async_migration.py
Labels: release-1.33.0

#8729 Validate redirect URL
  frontend/src/scenes/authentication/loginLogic.test.ts
  frontend/src/scenes/authentication/loginLogic.ts
Labels: release-1.33.0

#8735 Static cohort api return
  ee/clickhouse/sql/cohort.py
  posthog/api/cohort.py
  posthog/api/test/test_person.py
Labels: release-1.33.0

#8757 Set decimal places to 1 for all numbers in web performance pop over
  frontend/src/scenes/performance/WebPerformance.tsx
Labels: application-performance-monitoring

#8769 Fix determination of what dashboard collaborators have _implicit_ access
  frontend/src/scenes/dashboard/ShareModal.tsx
Labels: release-1.33.0

#8762 Add link to async migrations
  frontend/src/layout/navigation/TopBar/Announcement.tsx
  frontend/src/layout/navigation/TopBar/announcementLogic.ts
  frontend/src/layout/navigation/navigationLogic.ts
  frontend/src/scenes/instance/AsyncMigrations/AsyncMigrations.tsx
  frontend/src/scenes/instance/SystemStatus/systemStatusLogic.ts
  posthog/api/instance_status.py
Labels: release-1.33.0
