Repository PostHog/posthog, pull requests merged in 2022-07, with the labels that each got.

#10534 fix: Update AsyncMigrations.tsx to link to Overview page fixing 404
  frontend/src/scenes/instance/AsyncMigrations/AsyncMigrations.tsx
Labels: stale

#10748 fix: typo in edit annotation modal
  frontend/src/scenes/annotations/index.tsx
Labels: bug, feature/annotations

#9880 feat(lifecycle): Lifecycle persons on events
  ee/clickhouse/queries/test/test_lifecycle.py
  posthog/queries/trends/lifecycle.py
  posthog/test/test_journeys.py
Labels: stale

#10753 perf: make zstd(3) the standard compression for event.properties column
  posthog/clickhouse/migrations/0031_event_properties_zstd.py
  posthog/clickhouse/test/__snapshots__/test_schema.ambr
  posthog/models/event/sql.py
Labels: highlight :star:

#10703 fix: don't spam sentry with coordinator not aware errors
  plugin-server/src/main/ingestion-queues/kafka-queue.ts
Labels: stale

#10750 fix(funnel-breakdown): bad link
  frontend/src/scenes/funnels/FunnelBarChart.tsx
Labels: stale

#10706 Update plugin server dev start instructions
  plugin-server/README.md
Labels: stale

#10835 fix: update comment referencing kafka_client/topics.py
  plugin-server/src/config/kafka-topics.ts
Labels: stale

#10811 chore: Instrument license activation events
  ee/api/license.py
Labels: stale

#10734 feat(persons-on-events): async migration for persons-on-events
  posthog/async_migrations/disk_util.py
  posthog/async_migrations/migrations/0002_events_sample_by.py
  posthog/async_migrations/migrations/0006_persons_and_groups_on_events_backfill.py
  posthog/async_migrations/test/test_0004_replicated_schema.py
  posthog/async_migrations/test/test_0006_persons_and_groups_on_events_backfill.py
  posthog/async_migrations/test/test_migrations_not_required.py
  posthog/async_migrations/utils.py
  posthog/clickhouse/test/__snapshots__/test_schema.ambr
  posthog/models/event/sql.py
  posthog/models/group/util.py
  posthog/models/person/sql.py
  posthog/models/person/util.py
Labels: stale

#10758 feat(person-on-events): Add instance setting to show/hide 0006 async migration
  frontend/src/scenes/instance/AsyncMigrations/asyncMigrationsLogic.ts
  posthog/api/instance_settings.py
  posthog/async_migrations/definition.py
  posthog/async_migrations/migrations/0006_persons_and_groups_on_events_backfill.py
  posthog/async_migrations/setup.py
  posthog/async_migrations/test/test_0006_persons_and_groups_on_events_backfill.py
  posthog/management/commands/run_async_migrations.py
  posthog/settings/dynamic_settings.py
Labels: stale

#10790 feat(async-migrations): Allow parameterizing async migrations
  frontend/src/scenes/instance/AsyncMigrations/AsyncMigrationParametersModal.tsx
  frontend/src/scenes/instance/AsyncMigrations/AsyncMigrations.tsx
  frontend/src/scenes/instance/AsyncMigrations/asyncMigrationParameterFormLogic.ts
  frontend/src/scenes/instance/AsyncMigrations/asyncMigrationsLogic.ts
  latest_migrations.manifest
  posthog/api/async_migration.py
  posthog/api/test/test_async_migrations.py
  posthog/async_migrations/definition.py
  posthog/async_migrations/migrations/0005_person_replacing_by_version.py
  posthog/async_migrations/migrations/0006_persons_and_groups_on_events_backfill.py
  posthog/async_migrations/runner.py
  posthog/async_migrations/setup.py
  posthog/async_migrations/test/test_0006_persons_and_groups_on_events_backfill.py
  posthog/async_migrations/test/test_definition.py
  posthog/async_migrations/test/test_runner.py
  posthog/migrations/0253_add_async_migration_parameters.py
  posthog/models/async_migration.py
  posthog/tasks/test/test_async_migrations.py
Labels: stale

#10989 refactor(data-m): toolbar rename actions to events
  frontend/src/toolbar/actions/ActionsList.tsx
  frontend/src/toolbar/actions/ActionsTab.tsx
  frontend/src/toolbar/actions/EditAction.tsx
  frontend/src/toolbar/button/DraggableButton.tsx
  frontend/src/toolbar/button/ToolbarButton.tsx
  frontend/src/toolbar/elements/ElementInfo.tsx
  frontend/src/toolbar/flags/featureFlagsLogic.ts
Labels: release-1.38.0

#10957 feat(feature-flags): endpoint and test for local sdk evaluation
  posthog/api/__init__.py
  posthog/api/feature_flag.py
  posthog/api/test/test_feature_flag.py
  posthog/queries/trends/total_volume.py
  posthog/test/test_feature_flag.py
Labels: release-1.38.0

#11012 fix: Removed CSV button exports for dashboard
  frontend/src/scenes/dashboard/DashboardHeader.tsx
Labels: release-1.38.0

#11013 chore(feature-flags): Release experience continuity
  frontend/src/scenes/feature-flags/FeatureFlag.tsx
Labels: release-1.38.0

#11015 feat(session-analysis): remove feature flag
  frontend/src/lib/constants.tsx
  frontend/src/scenes/insights/EditorFilters/TrendsGlobalAndOrFilters.tsx
  frontend/src/scenes/insights/EditorFilters/TrendsSteps.tsx
  frontend/src/scenes/insights/filters/ActionFilter/ActionFilterRow/ActionFilterRow.tsx
  frontend/src/scenes/insights/filters/BreakdownFilter/TaxonomicBreakdownFilter.tsx
  frontend/src/scenes/insights/filters/BreakdownFilter/taxonomicBreakdownFilterUtils.test.ts
  frontend/src/scenes/insights/filters/BreakdownFilter/taxonomicBreakdownFilterUtils.ts
  frontend/src/scenes/trends/mathsLogic.tsx
Labels: release-1.38.0

#11021 fix: adding collaborators
  frontend/src/scenes/dashboard/DashboardCollaborators.tsx
Labels: release-1.38.0

#11023 fix: Exclude liveness probes from IP blocks
  posthog/middleware.py
  posthog/settings/web.py
Labels: release-1.38.0

#11019 fix: pass user id not user object when checking dashboard permission
  frontend/src/scenes/dashboard/DashboardCollaborators.tsx
  posthog/api/insight.py
  posthog/api/test/test_insight.py
Labels: bug, feature/dashboards, release-1.38.0

#11020 feat(property-filters): Add hover title for long filters
  frontend/src/lib/components/InsightCard/InsightDetails.tsx
  frontend/src/lib/components/PropertyFilters/PathItemFilters.tsx
  frontend/src/lib/components/PropertyFilters/components/PropertyFilterButton.tsx
Labels: release-1.38.0

#11016 chore(async-migrations): Make missing migrations error noticeable
  posthog/async_migrations/definition.py
  posthog/management/commands/run_async_migrations.py
  posthog/models/async_migration.py
  posthog/utils.py
Labels: release-1.38.0

#11018 refactor(data-m): rename actions to calculated events
  cypress/e2e/actionEvents.js
  frontend/src/lib/components/DefinitionPopup/utils.ts
  frontend/src/lib/components/TaxonomicFilter/taxonomicFilterLogic.tsx
  frontend/src/scenes/actions/Action.tsx
  frontend/src/scenes/actions/ActionEdit.tsx
  frontend/src/scenes/actions/ActionStep.tsx
  frontend/src/scenes/actions/NewActionButton.tsx
  frontend/src/scenes/actions/actionEditLogic.ts
  frontend/src/scenes/data-management/definition/DefinitionView.tsx
  frontend/src/scenes/data-management/events/DefinitionHeader.tsx
  frontend/src/scenes/data-management/events/EventDefinitionsTable.tsx
  frontend/src/toolbar/actions/ActionsList.tsx
  frontend/src/toolbar/actions/ActionsTab.tsx
  frontend/src/toolbar/actions/EditAction.tsx
  frontend/src/toolbar/button/DraggableButton.tsx
  frontend/src/toolbar/button/ToolbarButton.tsx
  frontend/src/toolbar/elements/ElementInfo.tsx
  posthog/settings/feature_flags.py
  posthog/templates/authorize_and_redirect.html
Labels: release-1.38.0

#10992 fix: Remove excess intervals
  ee/clickhouse/queries/test/__snapshots__/test_event_query.ambr
  ee/clickhouse/queries/test/__snapshots__/test_trends.ambr
  ee/clickhouse/views/test/__snapshots__/test_clickhouse_experiment_secondary_results.ambr
  ee/clickhouse/views/test/__snapshots__/test_clickhouse_experiments.ambr
  ee/clickhouse/views/test/__snapshots__/test_clickhouse_trends.ambr
  posthog/api/test/__snapshots__/test_action_people.ambr
  posthog/queries/test/__snapshots__/test_trends.ambr
  posthog/queries/test/test_trends.py
  posthog/queries/trends/test/__snapshots__/test_breakdowns.ambr
  posthog/queries/trends/test/__snapshots__/test_formula.ambr
  posthog/queries/util.py
Labels: release-1.38.0

#11033 fix: allow searching and adding on staff users tab
  frontend/src/scenes/instance/SystemStatus/StaffUsersTab.tsx
Labels: release-1.38.0

#11038 fix(persons): Use person UUIDs in merging instead of serial IDs
  frontend/src/scenes/persons/MergeSplitPerson.tsx
  frontend/src/scenes/persons/mergeSplitPersonLogic.ts
  posthog/api/person.py
  posthog/api/test/test_person.py
Labels: release-1.38.0
