Repository PostHog/posthog, pull requests merged in 2022-01, with the labels that each got.

#7705 Run e2e with clickhouse
  .github/workflows/e2e.yml
  bin/e2e-test-runner
  cypress/integration/insights.js
  cypress/integration/person.js
  cypress/integration/retention.js
  cypress/integration/systemStatus.js
  posthog/demo/revenue_data_generator.py
  posthog/tasks/test/test_calculate_event_property_usage.py
Labels: stale

#7806 Make background of insight graphs white
  frontend/src/lib/components/InsightCard/InsightCard.scss
  frontend/src/scenes/experiments/Experiment.scss
  frontend/src/scenes/funnels/FunnelBarGraph.scss
  frontend/src/scenes/insights/Insight.scss
Labels: stale

#7824 PostHog demo environment
  cypress/integration/signup.js
  frontend/src/layout/navigation/TopBar/Announcement.tsx
  frontend/src/layout/navigation/TopBar/SitePopover.tsx
  frontend/src/layout/navigation/TopBar/announcementLogic.ts
  frontend/src/layout/navigation/navigationLogic.ts
  frontend/src/scenes/PreflightCheck/logic.ts
  frontend/src/scenes/authentication/Signup.scss
  frontend/src/scenes/authentication/Signup.tsx
  frontend/src/scenes/sceneLogic.ts
  frontend/src/types.ts
  posthog/api/organization.py
  posthog/api/signup.py
  posthog/api/test/test_preflight.py
  posthog/demo/__init__.py
  posthog/settings/__init__.py
  posthog/utils.py
  posthog/views.py
Labels: stale

#7792 chore(pdi): add data migration for pdi to pdi2
  ee/clickhouse/migrations/0003_person.py
  posthog/async_migrations/migrations/0003_fill_person_distinct_id2.py
  posthog/async_migrations/runner.py
  posthog/async_migrations/test/test_0003_fill_person_distinct_id2.py
  posthog/async_migrations/test/test_runner.py
  posthog/tasks/async_migrations.py
  posthog/tasks/test/test_async_migrations.py
Labels: highlight :star:

#7847 Remove "minute" interval
  ee/clickhouse/queries/funnels/funnel_trends.py
  ee/clickhouse/queries/trends/lifecycle.py
  ee/clickhouse/queries/trends/person.py
  ee/clickhouse/queries/trends/test/test_formula.py
  ee/clickhouse/queries/trends/util.py
  ee/clickhouse/queries/util.py
  ee/clickhouse/views/test/test_clickhouse_action.py
  frontend/src/lib/components/DateDisplay/index.tsx
  frontend/src/lib/components/IntervalFilter/IntervalFilter.tsx
  frontend/src/lib/components/IntervalFilter/intervals.ts
  frontend/src/lib/utils.tsx
  frontend/src/scenes/insights/insightLogic.test.ts
  frontend/src/types.ts
  posthog/api/test/test_action_people.py
  posthog/api/test/test_stickiness.py
  posthog/models/filters/filter.py
  posthog/models/filters/mixins/base.py
  posthog/models/filters/mixins/common.py
  posthog/models/filters/mixins/funnel.py
  posthog/models/filters/mixins/interval.py
  posthog/models/filters/mixins/stickiness.py
  posthog/models/filters/mixins/test/test_interval.py
  posthog/models/filters/path_filter.py
  posthog/models/filters/stickiness_filter.py
  posthog/queries/abstract_test/test_interval.py
  posthog/queries/base.py
  posthog/queries/lifecycle.py
  posthog/queries/sessions/sessions.py
  posthog/queries/test/test_retention.py
  posthog/queries/test/test_trends.py
  posthog/queries/trends.py
  posthog/utils.py
Labels: highlight :star:

#7855 Proposal: Fix performance issues caused by actions page
  ee/clickhouse/views/actions.py
  frontend/src/lib/dayjs.ts
  frontend/src/scenes/actions/Action.tsx
  frontend/src/scenes/actions/ActionEdit.tsx
  frontend/src/scenes/events/EventsTable.tsx
  frontend/src/scenes/events/eventsTableLogic.test.ts
  frontend/src/scenes/events/eventsTableLogic.ts
  frontend/src/scenes/persons/Person.cy-spec.js
  posthog/api/test/test_action.py
Labels: highlight :star:

#7849 Proposal: Set time bounds for "all of time" filter
  ee/clickhouse/queries/test/test_util.py
  ee/clickhouse/queries/util.py
  ee/clickhouse/sql/events.py
  frontend/src/lib/components/DateFilter/DateFilter.tsx
  frontend/src/lib/components/DateFilter/DateFilterRange.tsx
  frontend/src/scenes/insights/InsightTabs/InsightDisplayConfig.tsx
Labels: highlight :star:

#7851 Closes #7842 Updates error message
  frontend/src/scenes/organization/Settings/CreateInviteModal.tsx
Labels: stale

#7823 do not start worker, plugins, or events if migrations not complete
  bin/docker-server
  bin/docker-worker
  bin/docker-worker-celery
  bin/plugin-server
Labels: stale

#8018 Benchmarks: trends breakdown and lifecycle with filtering
  ee/benchmarks/benchmarks.py
Labels: performance

#7988 Redesigned person & group pages
  cypress/integration/person.js
  frontend/src/layout/Error404.tsx
  frontend/src/layout/navigation/ProjectSwitcher.tsx
  frontend/src/layout/navigation/SideBar/SideBar.tsx
  frontend/src/lib/components/CopyToClipboard.tsx
  frontend/src/lib/components/LemonButton/More.tsx
  frontend/src/lib/components/LemonButton/index.tsx
  frontend/src/lib/components/LemonRow/LemonRow.scss
  frontend/src/lib/components/LemonRow/index.tsx
  frontend/src/lib/components/LemonTable/LemonTable.tsx
  frontend/src/lib/components/LemonTable/TableRow.tsx
  frontend/src/lib/components/PropertiesTable.scss
  frontend/src/lib/components/PropertiesTable.tsx
  frontend/src/lib/components/icons.tsx
  frontend/src/models/cohortsModel.ts
  frontend/src/scenes/actions/Action.tsx
  frontend/src/scenes/cohorts/cohortLogic.tsx
  frontend/src/scenes/dashboard/__stories__/dashboard.json
  frontend/src/scenes/events/Events.tsx
  frontend/src/scenes/events/EventsTable.tsx
  frontend/src/scenes/events/eventsTableLogic.test.ts
  frontend/src/scenes/events/eventsTableLogic.ts
  frontend/src/scenes/groups/Group.tsx
  frontend/src/scenes/groups/RelatedGroups.tsx
  frontend/src/scenes/groups/groupLogic.ts
  frontend/src/scenes/groups/relatedGroupsLogic.ts
  frontend/src/scenes/organization/Settings/Invites.tsx
  frontend/src/scenes/persons/GroupActorHeader.tsx
  frontend/src/scenes/persons/NewPropertyComponent.tsx
  frontend/src/scenes/persons/Person.cy-spec.js
  frontend/src/scenes/persons/Person.tsx
  frontend/src/scenes/persons/PersonCohorts.tsx
  frontend/src/scenes/persons/PersonHeader.tsx
  frontend/src/scenes/persons/Persons.scss
  frontend/src/scenes/persons/personsLogic.tsx
  frontend/src/scenes/saved-insights/SavedInsights.tsx
  frontend/src/scenes/session-recordings/SessionRecordingsTable.tsx
  frontend/src/scenes/urls.ts
  frontend/src/styles/global.scss
  frontend/src/types.ts
  posthog/api/person.py
Labels: highlight :star:

#7869 Disable colors in logging ease of reading in places like CloudWatch
  posthog/settings/logging.py
Labels: stale

#8194 Pause polling when there are new events, restart it when they are shown
  frontend/src/scenes/events/eventsTableLogic.test.ts
  frontend/src/scenes/events/eventsTableLogic.ts
Labels: team-core-experience

#8214 Update persisted flags for 1.32.0
  posthog/settings/feature_flags.py
Labels: release-1.32.0

#8228 Insight hash url
  frontend/src/scenes/insights/insightLogic.test.ts
  frontend/src/scenes/insights/insightLogic.tsx
  frontend/src/scenes/saved-insights/SavedInsights.tsx
  frontend/src/scenes/saved-insights/savedInsightsLogic.test.ts
  frontend/src/scenes/urls.ts
Labels: release-1.32.0

#8235 increase 0002 async migration range
  posthog/async_migrations/migrations/0002_events_sample_by.py
Labels: release-1.32.0

#8240 fix async migrations swttings don't update
  frontend/src/scenes/instance/AsyncMigrations/asyncMigrationsLogic.ts
Labels: release-1.32.0

#8246 Fix recording filter analytics event
  frontend/src/scenes/session-recordings/SessionRecordingsTable.tsx
  frontend/src/scenes/session-recordings/sessionRecordingsTableLogic.ts
Labels: release-1.32.0

#8232 fix(funnel): remove old funnel persons table
  frontend/src/scenes/funnels/FunnelPeople.scss
  frontend/src/scenes/funnels/FunnelPeople.tsx
  frontend/src/scenes/insights/InsightContainer.tsx
Labels: release-1.32.0

#8227 UI enhancements (around dashboards)
  cypress/integration/events.js
  frontend/src/lib/components/EditableField/EditableField.scss
  frontend/src/lib/components/InsightCard/InsightCard.scss
  frontend/src/lib/components/InsightCard/InsightCard.tsx
  frontend/src/lib/components/LemonButton/LemonButton.scss
  frontend/src/lib/components/LemonButton/index.tsx
  frontend/src/lib/components/Popup/Popup.scss
  frontend/src/lib/components/Popup/Popup.tsx
  frontend/src/scenes/dashboard/Dashboard.scss
  frontend/src/scenes/dashboard/DashboardItems.scss
  frontend/src/scenes/dashboard/LemonDashboardHeader.tsx
  frontend/src/scenes/insights/InsightTabs/FunnelTab/FunnelStepTable.scss
  frontend/src/scenes/insights/InsightsTable/InsightsTable.tsx
  frontend/src/styles/global.scss
  frontend/src/vars.scss
  package.json
  yarn.lock
Labels: release-1.32.0

#8259 Fix InfiniteList description popup style
  frontend/src/lib/components/TaxonomicFilter/InfiniteList.tsx
Labels: release-1.32.0

#7885 Async migrations UI refresh
  frontend/src/lib/components/LemonButton/LemonButton.scss
  frontend/src/lib/components/LemonRow/LemonRow.scss
  frontend/src/lib/components/LemonTable/LemonTable.scss
  frontend/src/lib/components/LemonTable/TableRow.tsx
  frontend/src/lib/components/LemonTable/types.ts
  frontend/src/lib/components/LemonTag/LemonTag.scss
  frontend/src/lib/components/LemonTag/LemonTag.tsx
  frontend/src/lib/components/icons.tsx
  frontend/src/scenes/appScenes.ts
  frontend/src/scenes/instance/AsyncMigrations/AsyncMigrationDetails.tsx
  frontend/src/scenes/instance/AsyncMigrations/AsyncMigrations.tsx
  frontend/src/scenes/instance/AsyncMigrations/SettingUpdateField.tsx
  frontend/src/scenes/instance/AsyncMigrations/asyncMigrationsLogic.ts
  frontend/src/scenes/instance/AsyncMigrations/index.scss
  frontend/src/scenes/instance/AsyncMigrations/index.tsx
  posthog/api/async_migration.py
Labels: release-1.32.0

#8255 Allow trends to do maths with page performance
  cypress/integration/events.js
  frontend/src/scenes/insights/ActionFilter/ActionFilterRow/ActionFilterRow.tsx
Labels: enhancement, web-performance

#8265 Remove @alexkim205 flags
  posthog/settings/feature_flags.py
Labels: release-1.32.0

#8318 fix(codespaces): only pin versions to major versions
  .devcontainer/Dockerfile
Labels: codespaces-build
