Repository PostHog/posthog, pull requests merged in 2022-11, with the labels that each got.

#12546 chore: Release "Count per user" for self-hosted
  posthog/settings/feature_flags.py
Labels: release-1.41.0

#12547 fix(person-on-events): Fix groups caching in ingestion
  plugin-server/src/utils/db/db.ts
  plugin-server/src/worker/ingestion/process-event.ts
  plugin-server/tests/main/db.test.ts
Labels: release-1.41.0

#12541 feat(person-on-events): person on events by default on self-hosted
  posthog/settings/dynamic_settings.py
Labels: release-1.41.0

#12474 fix(funnels): Improve "Time to convert" behavior
  frontend/src/lib/components/CommandPalette/DebugCHQueries.tsx
  frontend/src/scenes/funnels/FunnelHistogram.tsx
  frontend/src/scenes/funnels/funnelLogic.ts
  frontend/src/scenes/insights/EmptyStates/EmptyStates.scss
  frontend/src/scenes/insights/views/Funnels/FunnelBinsPicker.tsx
  frontend/src/scenes/insights/views/Histogram/Histogram.scss
  frontend/src/types.ts
  posthog/api/test/__snapshots__/test_insight_funnels.ambr
  posthog/api/test/test_insight_funnels.py
  posthog/queries/funnels/funnel_time_to_convert.py
  posthog/queries/funnels/test/__snapshots__/test_funnel_time_to_convert.ambr
  posthog/queries/funnels/test/test_funnel_time_to_convert.py
Labels: release-1.41.0

#12512 feat(trends): Support breakdown with event count per user
  posthog/queries/person_query.py
  posthog/queries/test/test_trends.py
  posthog/queries/trends/breakdown.py
  posthog/queries/trends/sql.py
  posthog/queries/trends/trends_event_query.py
Labels: release-1.41.0

#12536 feat: choose custom unit format in modal
  frontend/src/lib/components/LemonModal/LemonModal.scss
  frontend/src/lib/components/LemonModal/LemonModal.tsx
  frontend/src/lib/components/UnitPicker/CustomUnitModal.tsx
  frontend/src/lib/components/UnitPicker/UnitPicker.tsx
  frontend/src/lib/constants.tsx
  frontend/src/styles/vars.scss
Labels: release-1.41.0

#12475 fix: person ch distinct id deletion less racy
  posthog/api/person.py
  posthog/models/person/util.py
  posthog/models/test/test_person_model.py
Labels: highlight :star:

#12680 chore: allow elements limit to be set from URL
  posthog/api/element.py
  posthog/api/test/test_element.py
  posthog/models/element/sql.py
Labels: stale

#12931 fix(insights): stickiness compare previous
  frontend/src/lib/components/CompareFilter/compareFilterLogic.ts
Labels: release-1.42.0

#12930 fix: billing v2 throwing status 500
  ee/api/billing.py
  ee/api/test/test_billing.py
Labels: release-1.42.0

#12933 fix: text card font size and preview pane
  frontend/src/lib/components/Cards/TextCard/TextCard.tsx
  frontend/src/lib/components/LemonTextArea/LemonTextArea.tsx
Labels: release-1.42.0

#11927 feat: Recordings use events_summary to add extra data and improve performance
  frontend/src/scenes/session-recordings/playlist/SessionRecordingsPlaylistItem.tsx
  frontend/src/types.ts
  plugin-server/src/worker/ingestion/process-event.ts
  posthog/api/session_recording.py
  posthog/api/test/test_capture.py
  posthog/api/test/test_session_recordings.py
  posthog/clickhouse/migrations/0006_session_recording_events.py
  posthog/clickhouse/migrations/0021_session_recording_events_materialize_full_snapshot.py
  posthog/helpers/session_recording.py
  posthog/helpers/tests/test_session_recording_helpers.py
  posthog/models/__init__.py
  posthog/models/session_recording_event/session_recording_event.py
  posthog/models/session_recording_event/sql.py
  posthog/queries/session_recordings/session_recording.py
  posthog/queries/session_recordings/session_recording_list.py
  posthog/queries/session_recordings/test/__snapshots__/test_session_recording_list.ambr
  posthog/queries/session_recordings/test/test_session_recording.py
  posthog/queries/session_recordings/test/test_session_recording_list.py
  posthog/session_recordings/test/test_factory.py
Labels: feature/recordings

#12938 fix(insights): group property filters with operators
  frontend/src/lib/components/PropertyFilters/components/TaxonomicPropertyFilter.tsx
  frontend/src/lib/components/PropertyFilters/components/taxonomicPropertyFilterLogic.ts
  frontend/src/lib/components/PropertyFilters/utils.ts
  frontend/src/lib/utils/eventUsageLogic.ts
  frontend/src/types.ts
Labels: release-1.42.0

#12869 feat(insights): add area chart (closes #7372)
  frontend/src/lib/components/Cards/InsightCard/InsightCard.tsx
  frontend/src/lib/components/ChartFilter/ChartFilter.tsx
  frontend/src/lib/components/icons.stories.tsx
  frontend/src/lib/components/icons.tsx
  frontend/src/scenes/insights/InsightDisplayConfig.tsx
  frontend/src/scenes/insights/Insights.stories.tsx
  frontend/src/scenes/insights/__mocks__/trendsArea.json
  frontend/src/scenes/insights/__mocks__/trendsAreaBreakdown.json
  frontend/src/scenes/insights/sharedUtils.ts
  frontend/src/scenes/insights/views/LineGraph/LineGraph.tsx
  frontend/src/scenes/trends/Trends.tsx
  frontend/src/scenes/trends/viz/ActionsLineGraph.tsx
  frontend/src/types.ts
Labels: release-1.42.0

#12945 fix(group-analytics): Allow accessing group page when group key has dot
  package.json
  yarn.lock
Labels: release-1.42.0

#12949 fix(time-to-see-data): Remove tagging from sync_execute
  posthog/client.py
Labels: release-1.42.0

#12941 feat: support path and url normalisation for funnel breakdown
  posthog/models/property/util.py
  posthog/queries/breakdown_props.py
  posthog/queries/funnels/base.py
  posthog/queries/funnels/test/__snapshots__/test_breakdowns_by_current_url.ambr
  posthog/queries/funnels/test/test_breakdowns_by_current_url.py
  posthog/queries/trends/breakdown.py
Labels: release-1.42.0

#12544 feat: pre-fill existing tags for insights, actions, event definitions, and property definitions
  ee/api/test/test_tagged_item.py
  frontend/src/lib/api.ts
  frontend/src/models/dashboardsModel.tsx
  frontend/src/models/tagsModel.ts
  frontend/src/scenes/actions/ActionEdit.tsx
  frontend/src/scenes/actions/actionEditLogic.tsx
  frontend/src/scenes/dashboard/DashboardHeader.tsx
  frontend/src/scenes/dashboard/dashboardsLogic.ts
  frontend/src/scenes/data-management/definition/DefinitionEdit.tsx
  frontend/src/scenes/data-management/definition/definitionEditLogic.ts
  frontend/src/scenes/insights/Insight.tsx
  frontend/src/scenes/insights/insightLogic.ts
  frontend/src/scenes/saved-insights/savedInsightsLogic.test.ts
  posthog/api/__init__.py
  posthog/api/tagged_item.py
  posthog/api/test/test_event_definition.py
  posthog/api/test/test_tagged_item.py
Labels: stale

#12917 feat: management command to sync postgres persons to clickhouse
  posthog/management/commands/sync_persons_to_clickhouse.py
  posthog/management/commands/test/test_sync_persons_to_clickhouse.py
  posthog/models/person/util.py
Labels: release-1.42.0

#12992 fix(time-to-see-data): Reduce dashboard API payload size 2x
  frontend/src/scenes/dashboard/dashboardLogic.tsx
  posthog/api/dashboard.py
  posthog/api/test/dashboards/test_dashboard.py
  posthog/utils.py
Labels: highlight :star:
