Repository PostHog/posthog, pull requests merged in 2022-06, with the labels that each got.

#10005 feat: Deploy PLUGIN_SERVER_MODE
  task-definition.plugins-async.json
  task-definition.plugins-ingestion.json
Labels: stale

#9892 feat: improve Insight Activity logs
  cypress/integration/insights.js
  frontend/src/lib/components/ActivityLog/activityLogLogic.test.tsx
  frontend/src/lib/components/InsightCard/InsightCard.tsx
  frontend/src/scenes/feature-flags/activityDescriptions.tsx
  frontend/src/scenes/saved-insights/activityDescriptions.tsx
  frontend/src/types.ts
  posthog/api/insight.py
  posthog/api/test/test_insight.py
  posthog/models/activity_logging/activity_log.py
  posthog/models/tagged_item.py
  posthog/test/activity_logging/__init__.py
  posthog/test/activity_logging/test_activity_logging.py
  posthog/test/activity_logging/test_feature_flag_activity_logging.py
  posthog/test/activity_logging/test_insight_activity_logging.py
  posthog/test/activity_logging/test_person_activity_logging.py
  posthog/test/test_activity_logging.py
Labels: stale

#9650 chore: upgrade cypress to v10x
  .github/workflows/e2e.yml
  bin/e2e-test-runner
  cypress.e2e.config.ts
  cypress.e2e.json
  cypress.json
  cypress/e2e/actions.js
  cypress/e2e/annotations.js
  cypress/e2e/auth.js
  cypress/e2e/cohorts.js
  cypress/e2e/commandPalette.js
  cypress/e2e/dashboard.js
  cypress/e2e/dashboardPremium.js
  cypress/e2e/events.js
  cypress/e2e/exports.js
  cypress/e2e/featureFlags.js
  cypress/e2e/funnels.js
  cypress/e2e/insights.js
  cypress/e2e/insightsPremium.js
  cypress/e2e/invites.js
  cypress/e2e/licenses.js
  cypress/e2e/organizationSettings.js
  cypress/e2e/paths.js
  cypress/e2e/person.js
  cypress/e2e/persons.js
  cypress/e2e/preflight.js
  cypress/e2e/retention.js
  cypress/e2e/signup.js
  cypress/e2e/systemStatus.js
  cypress/e2e/toolbar.js
  cypress/e2e/trends.js
  cypress/plugins/index.js
  cypress/support/e2e.js
  package.json
  yarn.lock
Labels: stale

#10113 feat(capture): strip port from ip
  posthog/api/test/test_capture.py
  posthog/utils.py
Labels: stale

#10180 feat: standardize warning/beta tag
  frontend/src/lib/components/ChartFilter/ChartFilter.tsx
  frontend/src/scenes/session-recordings/player/SessionRecordingPlayerV2.tsx
Labels: stale

#10241 chore(hobby-deploy): Advise not to use IP address
  bin/deploy-hobby
Labels: stale

#10401 chore: release toolbar sidebar button
  frontend/src/layout/navigation/SideBar/SideBar.tsx
  frontend/src/lib/constants.tsx
Labels: Release 1.37.0

#10425 fix: Removed persisted flags that we don't want
  posthog/settings/feature_flags.py
Labels: release-1.37.0

#10415 fix: Link component with non target-blank external links
  frontend/src/lib/components/Link.tsx
  frontend/src/lib/utils.test.ts
  frontend/src/lib/utils.tsx
Labels: release-1.37.0

#10433 feat(debugging): automatically comment SQL queries
  posthog/api/test/__snapshots__/test_dashboard.ambr
  posthog/settings/data_stores.py
  posthog/settings/web.py
  requirements.in
  requirements.txt
Labels: highlight :star:

#10422 refactor: Release cohort filters ff
  cypress/e2e/cohorts.js
  frontend/src/lib/components/DefinitionPopup/CohortPopupInfo.tsx
  frontend/src/lib/constants.tsx
  frontend/src/lib/utils.tsx
  frontend/src/models/cohortsModel.ts
  frontend/src/scenes/cohorts/CohortEdit.tsx
  frontend/src/scenes/cohorts/CohortFilters/CohortField.tsx
  frontend/src/scenes/cohorts/MatchCriteriaSelector.tsx
  frontend/src/scenes/cohorts/cohortEditLogic.test.ts
  frontend/src/scenes/cohorts/cohortEditLogic.ts
  frontend/src/scenes/cohorts/cohortUtils.tsx
Labels: release-1.37.0

#10240 feat(feature-flags): Enable persisted flags
  frontend/src/lib/constants.tsx
  frontend/src/scenes/feature-flags/FeatureFlag.tsx
  frontend/src/scenes/feature-flags/activityDescriptions.tsx
  frontend/src/scenes/feature-flags/featureFlagLogic.ts
  frontend/src/types.ts
  posthog/api/feature_flag.py
Labels: stale

#10497 feat: Extended LemonSelectOptions to allow sections
  frontend/src/lib/components/LemonSelect.stories.tsx
  frontend/src/lib/components/LemonSelect.tsx
  frontend/src/lib/components/Subscriptions/utils.tsx
  frontend/src/styles/global.scss
Labels: components
