Repository PostHog/posthog, pull requests merged in 2022-12, with the labels that each got.

#13067 fix(hobby): fix hobby install compose
  docker-compose.hobby.yml
Labels: bug, deployments

#12650 chore(NodeJS): use Node.js v18
  .devcontainer/Dockerfile
  .github/workflows/ci-e2e-vrt.yml
  .github/workflows/ci-e2e.yml
  .github/workflows/ci-frontend.yml
  .github/workflows/ci-plugin-server.yml
  .github/workflows/storybook-chromatic-baselines-to-master.yml
  .github/workflows/storybook-chromatic.yml
  .github/workflows/storybook-deploy.yml
  package.json
  plugin-server/.babelrc
Labels: stale

#12101 fix(experiments): secondary metrics edit functionality and refactor
  frontend/src/scenes/experiments/Experiment.scss
  frontend/src/scenes/experiments/Experiment.tsx
  frontend/src/scenes/experiments/ExperimentPreview.tsx
  frontend/src/scenes/experiments/SecondaryMetrics.tsx
  frontend/src/scenes/experiments/experimentLogic.test.ts
  frontend/src/scenes/experiments/experimentLogic.tsx
  frontend/src/scenes/experiments/secondaryMetricsLogic.ts
  frontend/src/scenes/insights/filters/ActionFilter/ActionFilterRow/ActionFilterRow.tsx
  frontend/src/types.ts
Labels: feature/experimentation

#13371 fix(query-performance): Make `clickhouse_lag` celery metric cheap.
  posthog/async_migrations/migrations/0008_speed_up_kafka_timestamp_filters.py
  posthog/async_migrations/setup.py
  posthog/celery.py
  posthog/clickhouse/dead_letter_queue.py
  posthog/clickhouse/test/__snapshots__/test_schema.ambr
  posthog/management/commands/test/test_run_async_migrations.py
  posthog/models/event/sql.py
Labels: highlight :star:

#13165 fix: Removed the built in paginator as we don't use it for events
  posthog/api/event.py
Labels: stale

#13348 feat: capture performance opt in
  frontend/src/lib/api.mock.ts
  frontend/src/scenes/organization/Settings/VerifiedDomains/__snapshots__/verifiedDomainsLogic.test.ts.snap
  frontend/src/scenes/session-recordings/player/list/PlayerList.tsx
  frontend/src/scenes/session-recordings/settings/SessionRecordingSettings.tsx
  frontend/src/types.ts
  latest_migrations.manifest
  posthog/api/decide.py
  posthog/api/team.py
  posthog/api/test/__snapshots__/test_action.ambr
  posthog/api/test/__snapshots__/test_annotation.ambr
  posthog/api/test/test_decide.py
  posthog/migrations/0285_capture_performance_opt_in.py
  posthog/models/team/team.py
Labels: lisbon-web-performance

#13433 feat: Recording Inspector 3000
  frontend/src/lib/api.ts
  frontend/src/lib/constants.tsx
  frontend/src/scenes/session-recordings/SessionRecordings.tsx
  frontend/src/scenes/session-recordings/player/PlayerController.tsx
  frontend/src/scenes/session-recordings/player/PlayerInspector.tsx
  frontend/src/scenes/session-recordings/player/PlayerMeta.tsx
  frontend/src/scenes/session-recordings/player/PlayerMetaLinks.tsx
  frontend/src/scenes/session-recordings/player/Seekbar.tsx
  frontend/src/scenes/session-recordings/player/SessionRecordingPlayer.scss
  frontend/src/scenes/session-recordings/player/SessionRecordingPlayer.tsx
  frontend/src/scenes/session-recordings/player/icons.tsx
  frontend/src/scenes/session-recordings/player/inspector/PlayerInspector.tsx
  frontend/src/scenes/session-recordings/player/inspector/playerInspectorLogic.test.ts
  frontend/src/scenes/session-recordings/player/inspector/playerInspectorLogic.ts
  frontend/src/scenes/session-recordings/player/inspector/v1/ConsoleDetails.tsx
  frontend/src/scenes/session-recordings/player/inspector/v1/PlayerInspectorControls.tsx
  frontend/src/scenes/session-recordings/player/inspector/v1/PlayerList.scss
  frontend/src/scenes/session-recordings/player/inspector/v1/PlayerList.tsx
  frontend/src/scenes/session-recordings/player/inspector/v1/PlayerListRow.tsx
  frontend/src/scenes/session-recordings/player/inspector/v1/__snapshots__/consoleLogsUtils.test.ts.snap
  frontend/src/scenes/session-recordings/player/inspector/v1/consoleLogsListLogic.test.ts
  frontend/src/scenes/session-recordings/player/inspector/v1/consoleLogsListLogic.ts
  frontend/src/scenes/session-recordings/player/inspector/v1/consoleLogsUtils.test.ts
  frontend/src/scenes/session-recordings/player/inspector/v1/consoleLogsUtils.tsx
  frontend/src/scenes/session-recordings/player/inspector/v1/eventsListLogic.test.ts
  frontend/src/scenes/session-recordings/player/inspector/v1/eventsListLogic.ts
  frontend/src/scenes/session-recordings/player/inspector/v1/listLogic.ts
  frontend/src/scenes/session-recordings/player/inspector/v2/PlayerInspectorControls.tsx
  frontend/src/scenes/session-recordings/player/inspector/v2/PlayerInspectorList.scss
  frontend/src/scenes/session-recordings/player/inspector/v2/PlayerInspectorList.tsx
  frontend/src/scenes/session-recordings/player/inspector/v2/components/ItemConsoleLog.tsx
  frontend/src/scenes/session-recordings/player/inspector/v2/components/ItemEvent.tsx
  frontend/src/scenes/session-recordings/player/inspector/v2/components/ItemPerformanceEvent.tsx
  frontend/src/scenes/session-recordings/player/inspector/v2/components/SimpleKeyValueList.tsx
  frontend/src/scenes/session-recordings/player/list/PlayerFilter.tsx
  frontend/src/scenes/session-recordings/player/list/sharedListLogic.ts
  frontend/src/scenes/session-recordings/player/playerMetaLogic.test.ts
  frontend/src/scenes/session-recordings/player/playerSettingsLogic.test.ts
  frontend/src/scenes/session-recordings/player/playerSettingsLogic.ts
  frontend/src/scenes/session-recordings/player/sessionRecordingDataLogic.ts
  frontend/src/scenes/session-recordings/player/sessionRecordingPlayerLogic.test.ts
  frontend/src/scenes/session-recordings/player/sessionRecordingPlayerLogic.ts
  frontend/src/scenes/session-recordings/playlist/SessionRecordingsPlaylist.scss
  frontend/src/scenes/session-recordings/playlist/SessionRecordingsPlaylist.tsx
  frontend/src/scenes/session-recordings/settings/SessionRecordingSettings.tsx
  frontend/src/styles/utilities.scss
  frontend/src/types.ts
Labels: lisbon-web-performance

#13489 fix(query-performance): speed up trends queries by reducing amount of data streamed between shards
  ee/clickhouse/queries/test/__snapshots__/test_event_query.ambr
  ee/clickhouse/views/test/__snapshots__/test_clickhouse_trends.ambr
  posthog/queries/test/__snapshots__/test_trends.ambr
  posthog/queries/test/test_trends.py
  posthog/queries/trends/sql.py
  posthog/queries/trends/test/__snapshots__/test_formula.ambr
  posthog/queries/trends/total_volume.py
  posthog/queries/trends/trends_event_query.py
  posthog/queries/trends/trends_event_query_base.py
  posthog/queries/trends/util.py
Labels: highlight :star:
