Repository PostHog/posthog, pull requests merged in 2022-09, with the labels that each got.

#11849 feat: Include more info in ProfilePicture hover
  frontend/src/lib/components/LemonTable/columnUtils.tsx
  frontend/src/lib/components/ProfilePicture/ProfilePicture.tsx
  frontend/src/scenes/dashboard/DashboardHeader.tsx
Labels: highlight :star:

#11917 fix(onboarding): remove billing on self-hosted
  frontend/src/scenes/ingestion/Sidebar.tsx
  frontend/src/scenes/ingestion/ingestionLogic.ts
  frontend/src/scenes/ingestion/panels/VerificationPanel.tsx
Labels: release-1.40.0

#11920 fix(stickiness): entity person filter
  posthog/api/test/test_stickiness.py
  posthog/queries/stickiness/stickiness_event_query.py
Labels: release-1.40.0

#11810 fix(retention): Revamp persons modal
  ee/clickhouse/queries/retention/retention.py
  ee/clickhouse/queries/retention/retention_actors.py
  ee/clickhouse/queries/test/__snapshots__/test_retention.ambr
  ee/clickhouse/queries/test/test_retention.py
  ee/clickhouse/views/test/__snapshots__/test_clickhouse_retention.ambr
  ee/clickhouse/views/test/test_clickhouse_retention.py
  frontend/src/scenes/retention/RetentionModal.tsx
  frontend/src/scenes/retention/retentionTableLogic.ts
  frontend/src/scenes/retention/types.ts
  posthog/api/person.py
  posthog/api/test/test_retention.py
  posthog/constants.py
  posthog/models/filters/test/test_retention_filter.py
  posthog/queries/retention/__init__.py
  posthog/queries/retention/actors_query.py
  posthog/queries/retention/retention.py
  posthog/queries/test/test_retention.py
Labels: release-1.40.0

#11909 fix: formulas not working when multiple group or sessions are included
  ee/clickhouse/views/test/__snapshots__/test_clickhouse_trends.ambr
  posthog/queries/trends/test/__snapshots__/test_breakdowns.ambr
  posthog/queries/trends/test/__snapshots__/test_formula.ambr
  posthog/queries/trends/util.py
Labels: release-1.40.0

#11930 fix: 11895 formula bug fix tests
  posthog/queries/trends/test/test_formula.py
Labels: release-1.40.0

#11934 feat: remove 0007 async migration guard
  posthog/async_migrations/migrations/0007_persons_and_groups_on_events_backfill.py
Labels: release-1.40.0

#11936 fix(async-migrations): rename 0006 tmp tables to 0007, update params UI to support strings
  frontend/src/scenes/instance/AsyncMigrations/AsyncMigrationParametersModal.tsx
  frontend/src/scenes/instance/AsyncMigrations/asyncMigrationsLogic.ts
  posthog/async_migrations/migrations/0007_persons_and_groups_on_events_backfill.py
Labels: release-1.40.0

#11682 fix(annotations): Ensure timezone alignment
  frontend/src/lib/components/AnnotationsOverlay/AnnotationsOverlay.scss
  frontend/src/lib/components/AnnotationsOverlay/AnnotationsOverlay.tsx
  frontend/src/lib/components/AnnotationsOverlay/annotationsOverlayLogic.test.ts
  frontend/src/lib/components/AnnotationsOverlay/annotationsOverlayLogic.ts
  frontend/src/lib/dayjs.ts
  frontend/src/models/annotationsModel.ts
  frontend/src/scenes/annotations/annotationModalLogic.ts
  frontend/src/scenes/project/Settings/TimezoneConfig.tsx
Labels: release-1.40.0

#11985 perf(retention): Reduce retention mem usage
  ee/clickhouse/queries/test/__snapshots__/test_retention.ambr
  ee/clickhouse/views/test/__snapshots__/test_clickhouse_retention.ambr
  posthog/queries/retention/event_query.py
  posthog/queries/test/__snapshots__/test_retention.ambr
Labels: performance

#11989 feat: Ingestion warnings tab
  frontend/src/lib/constants.tsx
  frontend/src/scenes/appScenes.ts
  frontend/src/scenes/data-management/DataManagementPageTabs.tsx
  frontend/src/scenes/data-management/ingestion-warnings/IngestionWarningsView.tsx
  frontend/src/scenes/data-management/ingestion-warnings/ingestionWarningsLogic.ts
  frontend/src/scenes/sceneLogic.ts
  frontend/src/scenes/sceneTypes.ts
  frontend/src/scenes/scenes.ts
  frontend/src/scenes/urls.ts
  posthog/api/__init__.py
  posthog/api/ingestion_warnings.py
Labels: highlight :star:

#11973 fix(recordings): recordings width modal regression
  frontend/src/scenes/session-recordings/player/styles.scss
Labels: release-1.40.0
