Repository PostHog/posthog, pull requests merged in 2022-08, with the labels that each got.

#11073 feat: Replace some styles with classes
  cypress/e2e/dashboard.js
  cypress/e2e/trends.js
  frontend/src/exporter/ExportedInsight/ExportedInsight.tsx
  frontend/src/exporter/Exporter.tsx
  frontend/src/layout/navigation/Breadcrumbs/Breadcrumbs.scss
  frontend/src/layout/navigation/Breadcrumbs/Breadcrumbs.tsx
  frontend/src/layout/navigation/Navigation.tsx
  frontend/src/layout/navigation/ProjectSwitcher.tsx
  frontend/src/layout/navigation/SideBar/PageButton.tsx
  frontend/src/layout/navigation/TopBar/SitePopover.tsx
  frontend/src/layout/navigation/TopBar/TopBar.tsx
  frontend/src/lib/components/AddToDashboard/AddToDashboard.scss
  frontend/src/lib/components/AddToDashboard/AddToDashboardModal.tsx
  frontend/src/lib/components/BillingAlerts.tsx
  frontend/src/lib/components/DropdownSelector/DropdownSelector.tsx
  frontend/src/lib/components/EmptyMessage/EmptyMessage.tsx
  frontend/src/lib/components/EntityFilterInfo.tsx
  frontend/src/lib/components/ExpandIcon.tsx
  frontend/src/lib/components/JSBookmarklet.tsx
  frontend/src/lib/components/LemonSelect.tsx
  frontend/src/lib/components/PageHeader.tsx
  frontend/src/lib/components/PathCleanFilters/PathClean.scss
  frontend/src/lib/components/PathCleanFilters/PathCleanFilter.tsx
  frontend/src/lib/components/PropertiesTable.tsx
  frontend/src/lib/components/PropertyKeyInfo.tsx
  frontend/src/lib/components/SelectDownIcon.tsx
  frontend/src/lib/components/SelectGradientOverflow.tsx
  frontend/src/lib/components/icons.tsx
  frontend/src/lib/components/lemonToast.tsx
  frontend/src/lib/utils.tsx
  frontend/src/scenes/dashboard/Dashboard.scss
  frontend/src/scenes/dashboard/Dashboard.tsx
  frontend/src/scenes/insights/filters/PathCleaningFilter.tsx
  frontend/src/scenes/project-homepage/ProjectHomepage.tsx
  frontend/src/styles/utilities.scss
  tailwind.config.js
Labels: frontend/utility-css

#10927 chore: remove enabled for months envs
  plugin-server/src/config/config.ts
  plugin-server/src/types.ts
  plugin-server/src/worker/ingestion/team-manager.ts
  task-definition.plugins-async.json
  task-definition.plugins-ingestion.json
Labels: stale

#10984 fix(data-management): Make sure the page is called "Event Properties"
  frontend/src/scenes/data-management/DataManagementPageTabs.tsx
Labels: stale

#11075 feat(session-recordings): session recordings v3 modal view
  frontend/src/lib/components/LemonButton/LemonButton.tsx
  frontend/src/lib/components/ProfilePicture/ProfilePicture.scss
  frontend/src/lib/components/ProfilePicture/ProfilePicture.tsx
  frontend/src/lib/components/TimezoneAware/index.scss
  frontend/src/lib/components/TimezoneAware/index.tsx
  frontend/src/lib/components/icons.tsx
  frontend/src/lib/constants.tsx
  frontend/src/lib/utils.tsx
  frontend/src/scenes/persons/PersonHeader.tsx
  frontend/src/scenes/session-recordings/SessionPlayerDrawer.tsx
  frontend/src/scenes/session-recordings/player/PlayerConsole.scss
  frontend/src/scenes/session-recordings/player/PlayerConsole.tsx
  frontend/src/scenes/session-recordings/player/PlayerController.tsx
  frontend/src/scenes/session-recordings/player/PlayerEvents.scss
  frontend/src/scenes/session-recordings/player/PlayerEvents.tsx
  frontend/src/scenes/session-recordings/player/PlayerInspector.tsx
  frontend/src/scenes/session-recordings/player/PlayerMeta.scss
  frontend/src/scenes/session-recordings/player/PlayerMeta.tsx
  frontend/src/scenes/session-recordings/player/SessionRecordingPlayer.tsx
  frontend/src/scenes/session-recordings/player/SessionRecordingPlayerV2.tsx
  frontend/src/scenes/session-recordings/player/Time.tsx
  frontend/src/scenes/session-recordings/player/Timestamp.tsx
  frontend/src/scenes/session-recordings/player/eventsListLogic.ts
  frontend/src/scenes/session-recordings/player/icons.tsx
  frontend/src/scenes/session-recordings/player/metaLogic.ts
  frontend/src/scenes/session-recordings/player/sessionRecordingPlayerLogic.ts
  frontend/src/scenes/session-recordings/player/styles.scss
  frontend/src/scenes/session-recordings/sessionRecordingLogic.ts
  frontend/src/types.ts
Labels: feature/recordings

#10668 feat(property-filters): Feature flags in a separate tab
  cypress/e2e/events.js
  cypress/fixtures/api/event/feature_flag_property_definition.json
  frontend/src/lib/components/DefinitionPopup/DefinitionPopup.tsx
  frontend/src/lib/components/DefinitionPopup/definitionPopupLogic.ts
  frontend/src/lib/components/DefinitionPopup/utils.ts
  frontend/src/lib/components/PropertyFilters/components/TaxonomicPropertyFilter.tsx
  frontend/src/lib/components/PropertyFilters/components/taxonomicPropertyFilterLogic.test.ts
  frontend/src/lib/components/PropertyFilters/utils.ts
  frontend/src/lib/components/PropertyGroupFilters/PropertyGroupFilters.stories.tsx
  frontend/src/lib/components/ResizableTable/TableConfig.tsx
  frontend/src/lib/components/TaxonomicFilter/InfiniteList.tsx
  frontend/src/lib/components/TaxonomicFilter/TaxonomicFilter.stories.tsx
  frontend/src/lib/components/TaxonomicFilter/taxonomicFilterLogic.tsx
  frontend/src/lib/components/TaxonomicFilter/types.ts
  frontend/src/lib/components/TaxonomicPopup/TaxonomicPopup.stories.tsx
  frontend/src/scenes/experiments/Experiment.tsx
  frontend/src/scenes/experiments/SecondaryMetrics.tsx
  frontend/src/scenes/insights/EditorFilters/FunnelsQuerySteps.tsx
  frontend/src/scenes/insights/EditorFilters/TrendsGlobalAndOrFilters.tsx
  frontend/src/scenes/insights/EditorFilters/TrendsSteps.tsx
  frontend/src/scenes/insights/filters/ActionFilter/ActionFilter.stories.tsx
  frontend/src/scenes/insights/filters/BreakdownFilter/TaxonomicBreakdownButton.tsx
  frontend/src/scenes/project/Settings/TestAccountFiltersConfig.tsx
  frontend/src/scenes/session-recordings/SessionRecordingsTable.tsx
  posthog/api/property_definition.py
  posthog/api/test/test_property_definition.py
Labels: stale

#10973 fix: filter button sizing seems wrong
  frontend/src/lib/components/PropertyGroupFilters/PropertyGroupFilters.tsx
Labels: stale

#11188 feat(insights): Add "Number" display type to Trends
  frontend/src/exporter/ExportedInsight/ExportedInsight.tsx
  frontend/src/lib/components/ChartFilter/ChartFilter.tsx
  frontend/src/lib/components/CompareFilter/compareFilterLogic.ts
  frontend/src/lib/components/InsightCard/InsightCard.scss
  frontend/src/lib/components/InsightCard/InsightCard.tsx
  frontend/src/lib/constants.tsx
  frontend/src/scenes/insights/EditorFilters/TrendsSteps.tsx
  frontend/src/scenes/insights/InsightTooltip/InsightTooltip.tsx
  frontend/src/scenes/insights/InsightTooltip/insightTooltipUtils.tsx
  frontend/src/scenes/insights/Insights.stories.tsx
  frontend/src/scenes/insights/__mocks__/trendsNumber.json
  frontend/src/scenes/insights/aggregationAxisFormat.ts
  frontend/src/scenes/insights/aggregationAxisFormats.test.ts
  frontend/src/scenes/insights/filters/ActionFilter/ActionFilter.stories.tsx
  frontend/src/scenes/insights/views/BoldNumber/BoldNumber.scss
  frontend/src/scenes/insights/views/BoldNumber/BoldNumber.tsx
  frontend/src/scenes/insights/views/BoldNumber/index.ts
  frontend/src/scenes/insights/views/WorldMap/WorldMap.tsx
  frontend/src/scenes/trends/PersonsModal.tsx
  frontend/src/scenes/trends/Trends.tsx
  frontend/src/types.ts
  package.json
  posthog/constants.py
  yarn.lock
Labels: highlight :star:

#10933 fix(persons): Use encoded url for sceneUrl
  frontend/src/scenes/persons/Person.tsx
Labels: stale

#11149 chore(feature-flags): Bump posthoganalytics version
  posthog/models/team/team.py
  requirements.in
  requirements.txt
Labels: stale

#11302 style(emails): Tweaks to emails sent by PostHog
  posthog/templates/authorize_and_redirect.html
  posthog/templates/email/async_migration_error.html
  posthog/templates/email/canary_email.html
  posthog/templates/email/fatal_plugin_error.html
  posthog/templates/email/first_ingestion_reminder.html
  posthog/templates/email/invite.html
  posthog/templates/email/member_join.html
  posthog/templates/email/password_reset.html
  posthog/templates/email/second_ingestion_reminder.html
Labels: apps

#11037 perf(insights): Speed up loading properties
  cypress/e2e/a11y.js
  posthog/api/property_definition.py
Labels: stale

#11347 feat(data-deletion): Allow deleting events for persons (UI)
  frontend/src/scenes/persons/Person.tsx
  frontend/src/scenes/persons/PersonDeleteModal.tsx
  frontend/src/scenes/persons/PersonsTable.tsx
  frontend/src/scenes/persons/personsLogic.tsx
  posthog/api/person.py
  posthog/api/test/test_person.py
  posthog/settings/__init__.py
Labels: highlight :star:

#11469 fix: fewer loaders showing on the new dashboard modal
  frontend/src/scenes/dashboard/NewDashboardModal.tsx
Labels: release-1.39.0

#11471 fix: show user first name on plugins activity log
  frontend/src/lib/components/ActivityLog/activityLogLogic.plugin.test.tsx
  frontend/src/lib/components/ActivityLog/humanizeActivity.tsx
  frontend/src/scenes/plugins/pluginActivityDescriptions.tsx
Labels: release-1.39.0

#11474 chore: make multivariates & persistence non-beta
  frontend/src/scenes/feature-flags/FeatureFlag.tsx
Labels: release-1.39.0

#11486 fix(activity): Fix activity log on individual persons
  frontend/src/lib/api.ts
  frontend/src/lib/components/ActivityLog/ActivityLog.tsx
  posthog/api/person.py
  posthog/api/test/test_person.py
Labels: release-1.39.0

#11472 chore: Use instance setting for self-hosted person on events
  .github/actions/run-backend-tests/action.yml
  ee/clickhouse/materialized_columns/analyze.py
  ee/clickhouse/materialized_columns/columns.py
  frontend/src/lib/utils/eventUsageLogic.ts
  frontend/src/scenes/instance/SystemStatus/systemStatusLogic.ts
  posthog/cache_utils.py
  posthog/clickhouse/materialized_columns/column.py
  posthog/models/team/team.py
  posthog/models/team/util.py
  posthog/queries/person_distinct_id_query.py
  posthog/settings/dynamic_settings.py
  posthog/test/base.py
  posthog/test/test_team.py
Labels: release-1.39.0

#11473 fix(data-m): inconsistent alerts
  frontend/src/scenes/data-management/event-properties/EventPropertyDefinitionsTable.tsx
  frontend/src/scenes/data-management/events/EventDefinitionsTable.tsx
  frontend/src/scenes/events/UsageDisabledWarning.tsx
Labels: release-1.39.0

#11518 chore: cleanup old feature flags and person on events instance setting
  frontend/src/lib/constants.tsx
  frontend/src/scenes/insights/EditorFilters/EditorFilters.tsx
  posthog/settings/dynamic_settings.py
Labels: release-1.39.0
