Repository PostHog/posthog, pull requests merged in 2022-04, with the labels that each got.

#9220 chore(storybook): homepage story
  frontend/src/lib/api.mock.ts
  frontend/src/scenes/organization/Settings/VerifiedDomains/__snapshots__/verifiedDomainsLogic.test.ts.snap
  frontend/src/scenes/project-homepage/ProjectHomepage.stories.tsx
Labels: stale

#9246 refactor: `LemonButton`s in most places
  cypress/integration/dashboard.js
  frontend/src/lib/components/LemonRow/LemonRow.scss
  frontend/src/lib/components/PropertyFilters/components/FilterRow.tsx
  frontend/src/lib/components/icons.tsx
  frontend/src/scenes/actions/NewActionButton.tsx
  frontend/src/scenes/annotations/index.tsx
  frontend/src/scenes/cohorts/Cohorts.tsx
  frontend/src/scenes/dashboard/DashboardHeader.tsx
  frontend/src/scenes/dashboard/Dashboards.tsx
  frontend/src/scenes/dashboard/EmptyDashboardComponent.tsx
  frontend/src/scenes/experiments/Experiment.scss
  frontend/src/scenes/experiments/Experiment.tsx
  frontend/src/scenes/experiments/Experiments.tsx
  frontend/src/scenes/experiments/experimentLogic.tsx
  frontend/src/scenes/feature-flags/FeatureFlag.scss
  frontend/src/scenes/feature-flags/FeatureFlag.tsx
  frontend/src/scenes/feature-flags/FeatureFlags.tsx
  frontend/src/scenes/organization/Settings/InviteModal.tsx
  frontend/src/scenes/organization/Settings/Invites.tsx
  frontend/src/scenes/organization/Settings/VerifiedDomains/VerifiedDomains.tsx
  frontend/src/scenes/persons/NewPropertyComponent.tsx
  frontend/src/scenes/persons/Persons.tsx
  frontend/src/scenes/persons/PersonsSearch.tsx
  frontend/src/scenes/project-homepage/PrimaryDashboardModal.tsx
  frontend/src/scenes/project-homepage/ProjectHomepage.tsx
  frontend/src/scenes/saved-insights/SavedInsights.tsx
  frontend/src/scenes/toolbar-launch/AuthorizedUrlsTable.scss
  frontend/src/scenes/toolbar-launch/AuthorizedUrlsTable.tsx
  frontend/src/styles/global.scss
Labels: stale

#9222 feat(homepage): track insights viewed
  frontend/src/lib/utils/eventUsageLogic.ts
  frontend/src/scenes/funnels/funnelLogic.test.ts
  frontend/src/scenes/insights/insightLogic.test.ts
  frontend/src/scenes/insights/insightLogic.ts
  frontend/src/scenes/retention/retentionTableLogic.test.ts
  latest_migrations.manifest
  posthog/api/insight.py
  posthog/api/test/test_insight.py
  posthog/migrations/0225_insight_viewed.py
  posthog/models/__init__.py
  posthog/models/insight.py
  posthog/test/test_migration_0219.py
Labels: stale

#9263 refactor: transfer feature flag ownership & release
  frontend/src/lib/components/PayCard/PayCard.tsx
  frontend/src/lib/constants.tsx
  frontend/src/scenes/insights/InsightTabs/PathTab/PathTab.tsx
  frontend/src/scenes/insights/InsightTabs/TrendTab/funnelsCueLogic.tsx
Labels: stale

#9291 feat(trends): World Map
  ee/clickhouse/queries/breakdown_props.py
  ee/clickhouse/queries/funnels/base.py
  ee/clickhouse/queries/funnels/test/__snapshots__/test_funnel.ambr
  ee/clickhouse/queries/funnels/test/__snapshots__/test_funnel_strict.ambr
  ee/clickhouse/queries/funnels/test/__snapshots__/test_funnel_unordered.ambr
  ee/clickhouse/queries/test/test_breakdown_props.py
  ee/clickhouse/views/test/__snapshots__/test_clickhouse_experiment_secondary_results.ambr
  ee/clickhouse/views/test/__snapshots__/test_clickhouse_experiments.ambr
  frontend/src/lib/components/ChartFilter/ChartFilter.tsx
  frontend/src/lib/components/CompareFilter/compareFilterLogic.ts
  frontend/src/lib/components/InsightCard/InsightCard.tsx
  frontend/src/lib/components/InsightLegend/InsightLegend.tsx
  frontend/src/lib/constants.tsx
  frontend/src/scenes/insights/BreakdownFilter/TaxonomicBreakdownFilter.tsx
  frontend/src/scenes/insights/InsightContainer.tsx
  frontend/src/scenes/insights/InsightTabs/InsightDisplayConfig.tsx
  frontend/src/scenes/insights/InsightTabs/TrendTab/TrendTab.tsx
  frontend/src/scenes/insights/InsightTooltip/InsightTooltip.scss
  frontend/src/scenes/insights/Insights.stories.tsx
  frontend/src/scenes/insights/InsightsTable/InsightsTable.tsx
  frontend/src/scenes/insights/LineGraph/LineGraph.tsx
  frontend/src/scenes/insights/WorldMap/WorldMap.scss
  frontend/src/scenes/insights/WorldMap/WorldMap.tsx
  frontend/src/scenes/insights/WorldMap/countryCodes.ts
  frontend/src/scenes/insights/WorldMap/countryVectors.tsx
  frontend/src/scenes/insights/WorldMap/index.ts
  frontend/src/scenes/insights/WorldMap/worldMapLogic.tsx
  frontend/src/scenes/insights/__mocks__/trendsWorldMap.json
  frontend/src/scenes/insights/utils/cleanFilters.ts
  frontend/src/scenes/trends/PersonsModal.tsx
  frontend/src/scenes/trends/Trends.tsx
  frontend/src/scenes/trends/personsModalLogic.ts
  frontend/src/types.ts
  posthog/constants.py
  posthog/models/filters/mixins/common.py
Labels: highlight :star:

#9091 feat(insights): Warn before leaving insight with unsaved changes
  cypress/integration/insights.js
  frontend/src/lib/hooks/useUnloadConfirmation.ts
  frontend/src/lib/utils.tsx
  frontend/src/scenes/insights/Insight.tsx
  frontend/src/scenes/insights/insightLogic.ts
  frontend/src/scenes/insights/insightSceneLogic.tsx
  frontend/src/scenes/sceneLogic.ts
Labels: highlight :star:, stale

#9201 chore: remove flag for filter experiment
  frontend/src/lib/constants.tsx
  frontend/src/scenes/session-recordings/sessionRecordingsTableLogic.ts
Labels: stale

#9312 feat(retention): select number of weeks, adapt filter text
  frontend/src/scenes/insights/InsightTabs/RetentionTab.tsx
  frontend/src/scenes/insights/utils/cleanFilters.ts
  frontend/src/scenes/retention/retentionTableLogic.ts
  frontend/src/types.ts
Labels: stale

#9359 refactor(experiments): Remove `generateRandomAnimal` from codebase
  frontend/src/lib/utils/randomAnimal.ts
  frontend/src/scenes/experiments/experimentLogic.tsx
Labels: stale

#9255 perf: Speed up backend tests locally
  bin/tests
  posthog/conftest.py
  posthog/models/event_definition.py
  posthog/models/property_definition.py
Labels: stale

#9498 feat(ingestion): Add `$initial_pathname` support
  plugin-server/src/utils/db/utils.ts
Labels: release-1.35.0

#9502 fix(events): Improve sizing of `PropertiesTable` columns
  frontend/src/lib/components/PropertiesTable.scss
  frontend/src/lib/components/PropertiesTable.tsx
Labels: release-1.35.0

#9504 fix: funnels cue cta broken link
  frontend/src/scenes/insights/InsightTabs/TrendTab/FunnelsCue.tsx
  frontend/src/scenes/insights/InsightTabs/TrendTab/funnelsCueLogic.tsx
Labels: release-1.35.0

#9513 fix: Feature flag call
  posthog/models/team.py
Labels: release-1.35.0

#9304 feat(billing): Added billing limit and table to billing page
  frontend/src/lib/components/BillingAlerts.tsx
  frontend/src/lib/constants.tsx
  frontend/src/scenes/billing/CurrentPlan.tsx
  frontend/src/scenes/billing/CurrentUsage.tsx
  frontend/src/scenes/billing/billingLogic.ts
  frontend/src/types.ts
Labels: stale

#9519 fix: cohort detail patches
  frontend/src/lib/components/LemonInput/LemonInput.tsx
  frontend/src/lib/components/LemonTextArea/LemonTextArea.tsx
  frontend/src/scenes/cohorts/cohortLogic.ts
Labels: release-1.35.0
