Repository PostHog/posthog, pull requests merged in 2022-10, with the labels that each got.

#12037 feat: face hog v01
  frontend/src/layout/navigation/TopBar/NotificationBell.tsx
  frontend/src/layout/navigation/TopBar/NotificationsBell.scss
  frontend/src/layout/navigation/TopBar/TopBar.tsx
  frontend/src/layout/navigation/TopBar/notificationsLogic.ts
  frontend/src/lib/components/ActivityLog/ActivityLog.scss
  frontend/src/lib/components/ActivityLog/ActivityLog.stories.tsx
  frontend/src/lib/components/ActivityLog/ActivityLog.tsx
  frontend/src/lib/components/ActivityLog/activityLogLogic.feature-flag.test.tsx
  frontend/src/lib/components/ActivityLog/activityLogLogic.insight.test.tsx
  frontend/src/lib/components/ActivityLog/activityLogLogic.person.test.tsx
  frontend/src/lib/components/ActivityLog/activityLogLogic.plugin.test.tsx
  frontend/src/lib/components/ActivityLog/activityLogLogic.test.setup.ts
  frontend/src/lib/components/ActivityLog/activityLogLogic.test.tsx
  frontend/src/lib/components/ActivityLog/activityLogLogic.tsx
  frontend/src/lib/components/ActivityLog/humanizeActivity.tsx
  frontend/src/lib/components/LemonBadge/LemonBadge.scss
  frontend/src/lib/components/LemonBadge/LemonBadge.tsx
  frontend/src/lib/components/icons.tsx
  frontend/src/lib/constants.tsx
  frontend/src/scenes/feature-flags/FeatureFlag.tsx
  frontend/src/scenes/feature-flags/FeatureFlags.tsx
  frontend/src/scenes/feature-flags/activityDescriptions.tsx
  frontend/src/scenes/persons/Person.tsx
  frontend/src/scenes/plugins/Plugins.tsx
  frontend/src/scenes/plugins/plugin/HistoryDrawer.tsx
  frontend/src/scenes/saved-insights/SavedInsights.tsx
  frontend/src/scenes/saved-insights/activityDescriptions.tsx
  latest_migrations.manifest
  posthog/api/__init__.py
  posthog/api/activity_log.py
  posthog/api/test/test_activity_log.py
  posthog/migrations/0262_track_viewed_notifications.py
  posthog/models/__init__.py
  posthog/models/activity_logging/notification_viewed.py
Labels: you-snizza-you-lizza

#12047 feat(historical-exports): Release historical exports v2 for self-hosted
  posthog/settings/feature_flags.py
Labels: highlight :star:

#12025 feat: add info about US and EU hosting to flow
  frontend/src/lib/components/BridgePage/BridgePage.scss
  frontend/src/lib/components/BridgePage/BridgePage.tsx
  frontend/src/lib/components/LemonLabel/LemonLabel.stories.tsx
  frontend/src/lib/components/LemonLabel/LemonLabel.tsx
  frontend/src/lib/forms/Field.tsx
  frontend/src/scenes/authentication/RegionSelect.tsx
  frontend/src/scenes/authentication/Signup.tsx
Labels: feature/onboarding

#12034 chore: remove merge persons option from persons page
  cypress/e2e/person.js
  frontend/src/scenes/persons/MergeSplitPerson.tsx
  frontend/src/scenes/persons/Person.tsx
  frontend/src/scenes/persons/mergeSplitPersonLogic.ts
  posthog/api/person.py
  posthog/api/test/test_exports.py
  posthog/api/test/test_feature_flag.py
  posthog/api/test/test_insight.py
  posthog/api/test/test_person.py
  posthog/api/test/test_plugin.py
  posthog/management/commands/merge_distinct_emails.py
  posthog/models/activity_logging/activity_log.py
  posthog/models/person/person.py
  posthog/models/test/test_person_model.py
Labels: highlight :star:

#12144 feat(account-settings): Allow self-serve email address change
  frontend/src/scenes/me/Settings/UserDetails.tsx
  frontend/src/scenes/me/Settings/index.tsx
  frontend/src/scenes/organization/Settings/InviteModal.tsx
  frontend/src/scenes/userLogic.ts
  posthog/api/test/test_user.py
  posthog/api/user.py
  posthog/models/user.py
  posthog/tasks/email.py
  posthog/templates/email/base.html
  posthog/templates/email/email_change_new_address.html
  posthog/templates/email/email_change_old_address.html
  posthog/templates/email/styles.html
Labels: highlight :star:

#12156 feat: currency units choice
  frontend/src/lib/components/UnitPicker/UnitPicker.scss
  frontend/src/lib/components/UnitPicker/UnitPicker.tsx
  frontend/src/lib/constants.tsx
  frontend/src/scenes/funnels/FunnelLineGraph.tsx
  frontend/src/scenes/insights/Insight.scss
  frontend/src/scenes/insights/InsightDisplayConfig.tsx
  frontend/src/scenes/insights/aggregationAxisFormat.ts
  frontend/src/scenes/insights/aggregationAxisFormats.test.ts
  frontend/src/scenes/insights/utils.test.ts
  frontend/src/scenes/insights/views/BoldNumber/BoldNumber.tsx
  frontend/src/scenes/insights/views/InsightsTable/InsightsTable.tsx
  frontend/src/scenes/insights/views/LineGraph/LineGraph.tsx
  frontend/src/scenes/insights/views/LineGraph/PieChart.tsx
  frontend/src/scenes/insights/views/WorldMap/WorldMap.tsx
  frontend/src/scenes/retention/RetentionLineGraph.tsx
  frontend/src/scenes/trends/viz/ActionsHorizontalBar.tsx
  frontend/src/scenes/trends/viz/ActionsLineGraph.tsx
  frontend/src/scenes/trends/viz/ActionsPie.tsx
  frontend/src/types.ts
Labels: highlight :star:

#12190 fix(experiments): Use serializer for feature flag updates as well
  ee/clickhouse/views/experiments.py
  ee/clickhouse/views/test/__snapshots__/test_clickhouse_experiments.ambr
  ee/clickhouse/views/test/test_clickhouse_experiments.py
Labels: feature/experimentation

#12233 chore: Rollout groups properties writes to events
  plugin-server/src/config/config.ts
  plugin-server/src/types.ts
  plugin-server/src/utils/db/db.ts
  plugin-server/src/utils/db/hub.ts
  plugin-server/tests/main/db.test.ts
  plugin-server/tests/main/process-event.test.ts
  plugin-server/tests/worker/ingestion/process-event.test.ts
Labels: highlight :star:

#12339 fix: restrict alias to not allow merging already identified users into another
  plugin-server/src/worker/ingestion/person-state.ts
  plugin-server/tests/worker/ingestion/person-state.test.ts
Labels: highlight :star:

#12377 feat(trends): Compact series math selector
  cypress/e2e/trends.js
  frontend/src/lib/components/Cards/InsightCard/InsightDetails.tsx
  frontend/src/lib/components/LemonButton/LemonButton.scss
  frontend/src/lib/components/LemonButton/LemonButton.tsx
  frontend/src/lib/components/LemonSelect.tsx
  frontend/src/lib/components/PropertyKeyInfo.tsx
  frontend/src/lib/components/TaxonomicFilter/taxonomicFilterLogic.tsx
  frontend/src/lib/components/TaxonomicFilter/types.ts
  frontend/src/lib/constants.tsx
  frontend/src/lib/introductions/groupsAccessLogic.ts
  frontend/src/scenes/cohorts/CohortFilters/constants.tsx
  frontend/src/scenes/groups/GroupsIntroduction.tsx
  frontend/src/scenes/insights/filters/ActionFilter/ActionFilterRow/ActionFilterRow.tsx
  frontend/src/scenes/insights/filters/AggregationSelect.tsx
  frontend/src/scenes/insights/utils.test.ts
  frontend/src/scenes/insights/utils.tsx
  frontend/src/scenes/session-recordings/player/list/PlayerListRow.tsx
  frontend/src/scenes/trends/mathsLogic.tsx
  frontend/src/styles/utilities.scss
  frontend/src/types.ts
  posthog/api/documentation.py
  posthog/api/utils.py
  posthog/constants.py
  posthog/models/entity/entity.py
  posthog/models/filters/mixins/common.py
  posthog/queries/test/test_trends.py
  posthog/queries/trends/total_volume.py
  posthog/queries/trends/trends_event_query.py
  posthog/queries/trends/util.py
Labels: highlight :star:
