Repository PostHog/posthog, pull requests merged in 2022-05, with the labels that each got.

#9451 refactor(scenes): automatically bind props to logic in scenes
  frontend/src/scenes/App.tsx
  frontend/src/scenes/actions/Action.tsx
  frontend/src/scenes/cohorts/Cohort.tsx
  frontend/src/scenes/dashboard/Dashboard.tsx
  frontend/src/scenes/dashboard/dashboardLogic.ts
  frontend/src/scenes/experiments/Experiment.tsx
  frontend/src/scenes/experiments/experimentLogic.tsx
  frontend/src/scenes/feature-flags/FeatureFlag.tsx
  frontend/src/scenes/feature-flags/featureFlagLogic.ts
  frontend/src/scenes/insights/utils.ts
  frontend/src/scenes/persons/Person.tsx
  frontend/src/scenes/persons/Persons.tsx
  frontend/src/scenes/persons/personsLogic.ts
  frontend/src/scenes/sceneLogic.ts
  frontend/src/stories/How to build a scene.stories.mdx
  frontend/src/subscriptionsPlugin.ts
Labels: stale

#9755 chore(apps): rename plugins to apps
  frontend/src/layout/navigation/SideBar/SideBar.tsx
  frontend/src/lib/components/CommandPalette/commandPaletteLogic.ts
  frontend/src/lib/components/UniversalSearch/UniversalSearchPopup.tsx
  frontend/src/scenes/plugins/Plugins.tsx
  frontend/src/scenes/plugins/PluginsSearch.tsx
  frontend/src/scenes/plugins/edit/PluginDrawer.tsx
  frontend/src/scenes/plugins/edit/interface-jobs/PluginJobOptions.tsx
  frontend/src/scenes/plugins/plugin/CommunityPluginTag.tsx
  frontend/src/scenes/plugins/plugin/LocalPluginTag.tsx
  frontend/src/scenes/plugins/plugin/LogsDrawer.tsx
  frontend/src/scenes/plugins/plugin/PluginCard.tsx
  frontend/src/scenes/plugins/source/PluginSource.tsx
  frontend/src/scenes/plugins/source/createDefaultPluginSource.ts
  frontend/src/scenes/plugins/tabs/advanced/AdvancedTab.tsx
  frontend/src/scenes/plugins/tabs/advanced/CustomPlugin.tsx
  frontend/src/scenes/plugins/tabs/advanced/LocalPlugin.tsx
  frontend/src/scenes/plugins/tabs/advanced/SourcePlugin.tsx
  frontend/src/scenes/plugins/tabs/installed/sections/DisabledPluginsSection.tsx
  frontend/src/scenes/plugins/tabs/installed/sections/EnabledPluginsSection.tsx
  frontend/src/scenes/plugins/tabs/installed/sections/PluginsEmptyState.tsx
  frontend/src/scenes/plugins/tabs/installed/sections/UpgradeSection.tsx
  frontend/src/scenes/plugins/tabs/repository/RepositoryTab.tsx
  frontend/src/scenes/scenes.ts
  frontend/src/scenes/urls.ts
Labels: stale

#9970 chore: remove and-or-filtering flag
  cypress/integration/insights.js
  cypress/integration/retention.js
  cypress/integration/trends.js
  frontend/src/lib/constants.tsx
  frontend/src/scenes/insights/EditorFilters/EFTrendsGlobalFilters.tsx
  frontend/src/scenes/insights/EditorFilters/EditorFilters.tsx
  frontend/src/scenes/insights/InsightTabs/FunnelTab/FunnelTab.tsx
  frontend/src/scenes/insights/InsightTabs/PathTab/PathTab.tsx
  frontend/src/scenes/insights/InsightTabs/RetentionTab.tsx
  frontend/src/scenes/insights/InsightTabs/TrendTab/TrendTab.tsx
Labels: highlight :star:

#9968 chore: enable multi dashboard insight flag for self host
  cypress/integration/dashboard.js
  cypress/integration/trends.js
  posthog/settings/feature_flags.py
Labels: highlight :star:

#9984 chore: enable universal search for everyone
  cypress/integration/commandPalette.js
  frontend/src/layout/navigation/TopBar/SearchBox.tsx
  frontend/src/layout/navigation/TopBar/TopBar.scss
  frontend/src/layout/navigation/TopBar/TopBar.tsx
  frontend/src/lib/constants.tsx
  frontend/src/scenes/plugins/pluginsLogic.ts
Labels: highlight :star:, release-1.36.0

#9971 chore: remove experiments-secondary-metrics flag
  frontend/src/lib/constants.tsx
  frontend/src/scenes/experiments/Experiment.tsx
  frontend/src/scenes/experiments/SecondaryMetrics.tsx
  frontend/src/scenes/experiments/experimentLogic.tsx
Labels: highlight :star:, release-1.36.0

#9999 fix: update broken plugin-server deployment script
  bin/plugin-server
Labels: release-1.36.0

#10009 fix(insights): Put internal users filter at the top
  frontend/src/lib/components/LemonSwitch/LemonSwitch.tsx
  frontend/src/lib/components/PropertyGroupFilters/PropertyGroupFilters.tsx
  frontend/src/scenes/insights/TestAccountFilter/TestAccountFilter.tsx
Labels: release-1.36.0

#10012 fix(trends): Adjust timezone display in tooltip
  frontend/src/lib/utils.tsx
  frontend/src/scenes/insights/InsightTooltip/InsightTooltip.tsx
Labels: release-1.36.0

#10001 fix(login): Improve login page layout
  frontend/src/lib/components/SocialLoginButton/index.scss
  frontend/src/lib/components/SocialLoginButton/index.tsx
  frontend/src/lib/constants.tsx
  frontend/src/scenes/authentication/Login.scss
  frontend/src/scenes/authentication/Login.tsx
  frontend/src/scenes/authentication/bridgePagesShared.scss
  frontend/src/scenes/organization/Settings/VerifiedDomains/SSOSelect.tsx
  posthog/templatetags/posthog_assets.py
Labels: release-1.36.0

#9993 fix(cohorts): cannot save static cohort
  frontend/src/scenes/cohorts/cohortEditLogic.test.ts
  frontend/src/scenes/cohorts/cohortEditLogic.ts
  frontend/src/scenes/cohorts/cohortUtils.ts
Labels: release-1.36.0

#10020 fix(funnels): Fix `FunnelStepMore` taking up space when it's null
  frontend/src/lib/components/LemonRow/LemonRow.tsx
  frontend/src/scenes/funnels/FunnelBarChart.tsx
  frontend/src/scenes/funnels/FunnelStepMore.tsx
Labels: release-1.36.0

#9998 fix: soft or hard delete insight after soft or hard dashboard deletion
  ee/api/test/test_dashboard.py
  ee/api/test/test_insight.py
  posthog/api/dashboard.py
  posthog/api/forbid_destroy_model.py
  posthog/api/insight.py
  posthog/api/test/test_dashboard.py
  posthog/api/test/test_insight.py
  posthog/settings/object_storage.py
Labels: release-1.36.0

#10036 fix(trends): Better align series selector in persons modal
  frontend/src/lib/components/DateDisplay/DateDisplay.scss
  frontend/src/scenes/trends/PersonsModal.scss
Labels: release-1.36.0
