Repository PostHog/posthog, pull requests merged in 2022-03, with the labels that each got.

#8697 Support new style property groups in ColumnOptimizer and person property pushdowns
  ee/clickhouse/models/cohort.py
  ee/clickhouse/models/property.py
  ee/clickhouse/models/test/__snapshots__/test_property.ambr
  ee/clickhouse/models/test/test_property.py
  ee/clickhouse/models/util.py
  ee/clickhouse/queries/breakdown_props.py
  ee/clickhouse/queries/column_optimizer.py
  ee/clickhouse/queries/event_query.py
  ee/clickhouse/queries/funnels/test/__snapshots__/test_funnel.ambr
  ee/clickhouse/queries/funnels/test/__snapshots__/test_funnel_correlation.ambr
  ee/clickhouse/queries/funnels/test/__snapshots__/test_funnel_correlations_persons.ambr
  ee/clickhouse/queries/funnels/test/test_funnel.py
  ee/clickhouse/queries/funnels/test/test_funnel_correlations_persons.py
  ee/clickhouse/queries/person_query.py
  ee/clickhouse/queries/property_optimizer.py
  ee/clickhouse/queries/session_recordings/test/__snapshots__/test_clickhouse_session_recording_list.ambr
  ee/clickhouse/queries/test/__snapshots__/test_breakdown_props.ambr
  ee/clickhouse/queries/test/__snapshots__/test_event_query.ambr
  ee/clickhouse/queries/test/__snapshots__/test_person_query.ambr
  ee/clickhouse/queries/test/__snapshots__/test_trends.ambr
  ee/clickhouse/queries/test/test_breakdown_props.py
  ee/clickhouse/queries/test/test_person_query.py
  ee/clickhouse/queries/test/test_property_optimizer.py
  ee/clickhouse/queries/test/test_trends.py
  ee/clickhouse/queries/trends/breakdown.py
  ee/clickhouse/views/test/__snapshots__/test_clickhouse_retention.ambr
  package.json
  posthog/models/filters/mixins/property.py
  posthog/models/property.py
Labels: performance

#8759 Better describe points in time in the web performance view
  frontend/src/scenes/performance/WebPerformance.scss
  frontend/src/scenes/performance/WebPerformance.tsx
Labels: application-performance-monitoring

#8790 Remove instance settings from sidebar
  frontend/src/layout/navigation/SideBar/SideBar.tsx
  frontend/src/layout/navigation/TopBar/SitePopover.tsx
  frontend/src/lib/components/icons.tsx
Labels: release-1.33.0

#8718 fix(property-filters): materialized property value search
  ee/benchmarks/benchmarks.py
  ee/clickhouse/models/property.py
  ee/clickhouse/queries/property_values.py
  ee/clickhouse/sql/events.py
  ee/clickhouse/sql/person.py
  posthog/api/event.py
  posthog/api/person.py
  posthog/api/test/__snapshots__/test_event.ambr
  posthog/api/test/__snapshots__/test_person.ambr
  posthog/api/test/test_event.py
  posthog/api/test/test_person.py
Labels: performance

#8794 fix(cohorts): person cohorts tab wasn't returning consistently
  ee/clickhouse/models/cohort.py
  ee/clickhouse/sql/cohort.py
  frontend/src/scenes/persons/PersonCohorts.tsx
  posthog/api/person.py
  posthog/api/test/test_person.py
Labels: bug, cohorts

#8897 fix(web performance): avoid NaN% when calculating percentage of time taken
  frontend/src/scenes/performance/WebPerformance.tsx
Labels: application-performance-monitoring, quality

#8733 fix(auth): Make axes less strict
  posthog/settings/web.py
Labels: stale

#9030 ci(codespaces): install node 16 in codespaces image
  .devcontainer/Dockerfile
Labels: codespaces-build

#8847 fix(cohorts): Restore person actions on cohort persons page
  ee/clickhouse/queries/person_query.py
  ee/clickhouse/queries/test/__snapshots__/test_person_query.ambr
  ee/clickhouse/sql/cohort.py
  frontend/src/lib/api.ts
  frontend/src/scenes/persons/Persons.tsx
  frontend/src/scenes/persons/personsLogic.ts
  posthog/api/cohort.py
  posthog/api/person.py
  posthog/api/test/test_cohort.py
  posthog/api/test/test_person.py
  posthog/constants.py
  posthog/models/filters/filter.py
  posthog/models/filters/mixins/common.py
Labels: bug, feature/cohorts

#9013 feat(sharding): Remove CLICKHOUSE_REPLICATION
  ee/api/test/__snapshots__/test_instance_settings.ambr
  ee/clickhouse/materialized_columns/columns.py
  ee/clickhouse/materialized_columns/replication.py
  ee/clickhouse/migrations/0011_cohortpeople_no_shard.py
  ee/clickhouse/sql/events.py
  ee/clickhouse/sql/session_recording_events.py
  ee/clickhouse/sql/test/__snapshots__/test_schema.ambr
  ee/tasks/materialized_columns.py
  plugin-server/tests/helpers/clickhouse.ts
  posthog/async_migrations/definition.py
  posthog/async_migrations/test/test_migrations_not_required.py
  posthog/settings/data_stores.py
Labels: highlight :star:

#8987 feat(settings): staff users
  frontend/src/lib/components/icons.tsx
  frontend/src/scenes/instance/SystemStatus/StaffUsersTab.tsx
  frontend/src/scenes/instance/SystemStatus/index.tsx
  frontend/src/scenes/instance/SystemStatus/staffUsersLogic.ts
  frontend/src/scenes/instance/SystemStatus/systemStatusLogic.ts
  frontend/src/scenes/scenes.ts
  frontend/src/scenes/urls.ts
  frontend/src/styles/global.scss
Labels: highlight :star:

#9002 feat(sso): enforce SSO on self-hosted instances
  ee/api/test/test_authentication.py
  ee/settings.py
  posthog/api/authentication.py
  posthog/api/test/test_authentication.py
  posthog/api/test/test_signup.py
  posthog/urls.py
  posthog/utils.py
  posthog/views.py
Labels: highlight :star:, enterprise, feature/sso

#9204 fix(web-performance): nav timing isn't always present
  frontend/src/scenes/performance/webPerformanceLogic.ts
Labels: bug, P2, feature/apm

#9205 feat(data-management): detect boolean properties on ingestion
  plugin-server/src/worker/ingestion/property-definitions-auto-discovery.ts
  plugin-server/tests/worker/ingestion/team-manager.test.ts
Labels: enhancement, feature/data-management

#9224 chore: remove data management FF
  frontend/public/actions-tutorial-grouping.svg
  frontend/public/actions-tutorial-retroactive.svg
  frontend/public/actions-tutorial-standardized.svg
  frontend/src/lib/components/TaxonomicFilter/InfiniteList.tsx
  frontend/src/scenes/actions/ActionsTable.tsx
  frontend/src/scenes/appScenes.ts
  frontend/src/scenes/data-management/event-properties/EventPropertyDefinitionsTable.tsx
  frontend/src/scenes/data-management/events/EventDefinitionsTable.tsx
  frontend/src/scenes/events/EventsTable.tsx
  frontend/src/scenes/events/EventsVolumeTable.tsx
  frontend/src/scenes/events/PropertiesVolumeTable.tsx
  frontend/src/scenes/events/VolumeTable.scss
  frontend/src/scenes/events/VolumeTable.tsx
  frontend/src/scenes/events/definitions/DefinitionDescription.tsx
  frontend/src/scenes/events/definitions/DefinitionDrawer.tsx
  frontend/src/scenes/events/definitions/DefinitionOwnerDropdown.tsx
  frontend/src/scenes/events/definitions/EventPropertiesStats.tsx
  frontend/src/scenes/events/definitions/EventsTableSnippet.tsx
  frontend/src/scenes/events/definitions/VolumeTableRecordDescription.tsx
  frontend/src/scenes/events/definitions/definitionDrawerLogic.ts
  frontend/src/scenes/sceneTypes.ts
Labels: highlight :star:

#9250 fix(migrations): Upgrade infi.orm
  requirements.in
  requirements.txt
Labels: release-1.34.0

#9217 feat(activity-logging): track UI actions on persons
  posthog/api/person.py
  posthog/api/test/test_feature_flag.py
  posthog/api/test/test_person.py
  posthog/models/activity_logging/activity_log.py
  posthog/models/activity_logging/serializers.py
Labels: enhancement, feature/activity-logging

#9247 fix(personsmodal): Make sure person modal doesn't cause page to reset
  frontend/src/scenes/trends/personsModalLogic.ts
Labels: release-1.34.0

#9266 feat(web-performance): Move waterfall chart onto its own page
  frontend/src/lib/api.ts
  frontend/src/lib/components/ResizableTable/tableConfigLogic.test.ts
  frontend/src/lib/components/ResizableTable/tableConfigLogic.ts
  frontend/src/scenes/events/EventsTable.tsx
  frontend/src/scenes/events/eventsTableLogic.test.ts
  frontend/src/scenes/events/eventsTableLogic.ts
  frontend/src/scenes/groups/Group.tsx
  frontend/src/scenes/performance/WebPerformance.scss
  frontend/src/scenes/performance/WebPerformance.stories.tsx
  frontend/src/scenes/performance/WebPerformance.tsx
  frontend/src/scenes/performance/WebPerformanceWaterfallChart.tsx
  frontend/src/scenes/performance/webPerformanceLogic.tsx
  frontend/src/scenes/persons/Person.tsx
  frontend/src/scenes/scenes.ts
  frontend/src/scenes/session-recordings/sessionRecordingLogic.ts
  frontend/src/scenes/urls.ts
  posthog/api/event.py
  posthog/api/test/test_event.py
Labels: feature/apm

#9226 feat(activity-logging): adds history tab to the Persons page
  frontend/src/lib/api.ts
  frontend/src/lib/components/ActivityLog/ActivityLog.scss
  frontend/src/lib/components/ActivityLog/ActivityLog.stories.tsx
  frontend/src/lib/components/ActivityLog/ActivityLog.tsx
  frontend/src/lib/components/ActivityLog/__mocks__/activityLogMocks.ts
  frontend/src/lib/components/ActivityLog/activityLogLogic.test.tsx
  frontend/src/lib/components/ActivityLog/activityLogLogic.tsx
  frontend/src/lib/components/ActivityLog/humanizeActivity.tsx
  frontend/src/lib/constants.tsx
  frontend/src/scenes/feature-flags/FeatureFlags.tsx
  frontend/src/scenes/feature-flags/activityDescriptions.tsx
  frontend/src/scenes/feature-flags/featureFlagsLogic.test.ts
  frontend/src/scenes/feature-flags/featureFlagsLogic.ts
  frontend/src/scenes/persons/Person.tsx
  frontend/src/scenes/persons/activityDescriptions.tsx
  frontend/src/scenes/persons/personsLogic.ts
  frontend/src/types.ts
  posthog/models/activity_logging/activity_log.py
  posthog/test/test_activity_logging.py
Labels: enhancement, feature/activity-logging

#9315 fix(migration): fix organisation domain migration with whitelisted domains
  posthog/migrations/0223_organizationdomain.py
Labels: release-1.34.0
