Repository PostHog/posthog, pull requests merged in 2023-01, with the labels that each got.

#13543 chore(CD): rename and consolidate container build workflows
  .github/workflows/container-images-release-unstable.yml
  .github/workflows/container-images-release.yml
  .github/workflows/docker-image-publish.yml
  .github/workflows/docker-release-image-publish.yml
  .github/workflows/docker-unstable-image.yml
Labels: highlight :star:

#13592 chore(flags): Remove flag for variant overrides
  frontend/src/lib/constants.tsx
  frontend/src/scenes/feature-flags/FeatureFlag.tsx
Labels: highlight :star:

#13573 fix: session recordings listing is nplus1 for persons
  posthog/api/session_recording.py
  posthog/api/test/__snapshots__/test_session_recordings.ambr
  posthog/api/test/test_session_recordings.py
Labels: release-1.43.0

#13611 chore(roles): add role based access to self hosted
  posthog/settings/feature_flags.py
Labels: highlight :star:, release-1.43.0

#13629 fix: dashboard duplication was not skipping deleted tiles
  posthog/api/dashboards/dashboard.py
  posthog/api/test/dashboards/test_dashboard.py
Labels: release-1.43.0

#13633 chore: Release Export recordings feature
  frontend/src/lib/constants.tsx
  frontend/src/scenes/session-recordings/SessionRecordings.tsx
  frontend/src/scenes/session-recordings/player/PlayerController.tsx
Labels: highlight :star:, release-1.43.0

#13600 feat: don't stop chasing waterfalls
  ee/api/performance_events.py
  ee/api/test/test_performance_events.py
  ee/test/fixtures/performance_event_fixtures.py
  frontend/src/lib/api.ts
  frontend/src/lib/utils.tsx
  frontend/src/queries/nodes/DataTable/renderColumn.tsx
  frontend/src/queries/query.ts
  frontend/src/queries/schema.ts
  frontend/src/queries/utils.ts
  frontend/src/scenes/performance/WebPerformance.scss
  frontend/src/scenes/performance/WebPerformance.stories.tsx
  frontend/src/scenes/performance/WebPerformance.tsx
  frontend/src/scenes/performance/WebPerformanceWaterfallChart.tsx
  frontend/src/scenes/performance/webPerformanceLogic.tsx
  frontend/src/scenes/session-recordings/player/inspector/v2/components/ItemPerformanceEvent.tsx
  frontend/src/scenes/urls.ts
  frontend/src/styles/utilities.scss
  frontend/src/types.ts
  posthog/conftest.py
  posthog/models/performance/sql.py
Labels: lisbon-web-performance

#13648 chore: enable website-analytics-template for self hosted
  posthog/settings/feature_flags.py
Labels: release-1.43.0

#13655 fix(roles): fix new org resource bug
  frontend/src/scenes/organization/Settings/Permissions/permissionsLogic.tsx
Labels: release-1.43.0

#13646 chore: Disable persons on events by default for self-hosted
  posthog/settings/dynamic_settings.py
Labels: release-1.43.0

#13794 fix: dashboard modal could not cope with deleted tiles
  cypress/e2e/dashboard.cy.ts
  cypress/e2e/trends.cy.ts
  cypress/productAnalytics/index.ts
  frontend/src/exporter/__mocks__/Exporter.mocks.tsx
  frontend/src/lib/components/AddToDashboard/AddToDashboard.tsx
  frontend/src/lib/components/AddToDashboard/AddToDashboardModal.tsx
  frontend/src/lib/components/AddToDashboard/addToDashboardModalLogic.ts
  frontend/src/lib/components/Cards/InsightCard/InsightCard.stories.tsx
  frontend/src/scenes/insights/insightLogic.test.ts
  frontend/src/scenes/saved-insights/activityDescriptions.tsx
  frontend/src/types.ts
  posthog/api/dashboards/dashboard.py
  posthog/api/insight.py
  posthog/api/test/__snapshots__/test_insight.ambr
  posthog/api/test/dashboards/__snapshots__/test_dashboard.ambr
  posthog/api/test/dashboards/test_dashboard.py
  posthog/api/test/test_insight.py
  posthog/models/insight.py
Labels: highlight :star:

#13900 chore(plugin-server): Upgrade jsonwebtoken to 9.0.0
  plugin-server/package.json
  plugin-server/pnpm-lock.yaml
Labels: highlight :star:

#13954 feat: remove `items` from dashboard API
  frontend/src/scenes/dashboard/dashboardLogic.test.ts
  frontend/src/scenes/dashboard/dashboardLogic.tsx
  posthog/api/dashboards/dashboard.py
  posthog/api/test/dashboards/__init__.py
  posthog/api/test/dashboards/test_dashboard.py
  posthog/utils.py
Labels: highlight :star:
