Repository PostHog/posthog, pull requests merged in 2023-10, with the labels that each got.

#17363 fix: quotes in Go feature flag snippit
  frontend/src/scenes/feature-flags/FeatureFlagSnippets.tsx
Labels: stale

#17622 chore: add backfill warning for exports bigger than 1 month
  frontend/src/scenes/batch_exports/BatchExportBackfillModal.tsx
Labels: stale

#17636 feat: change unique idx on messsaging table
  latest_migrations.manifest
  posthog/migrations/0352_auto_20230926_1833.py
  posthog/models/messaging.py
Labels: stale

#17749 feat: display entire element chain
  frontend/src/lib/components/HTMLElementsDisplay/HTMLElementsDisplay.tsx
  frontend/src/lib/components/HTMLElementsDisplay/htmlElementsDisplayLogic.ts
  frontend/src/lib/components/HTMLElementsDisplay/preselectWithCSS.test.ts
  frontend/src/toolbar/actions/actionsTabLogic.tsx
Labels: hacktoberfest-accepted

#18068 feat: configure session recording sample rate
  frontend/src/lib/api.mock.ts
  frontend/src/lib/components/FlagSelector.tsx
  frontend/src/lib/constants.tsx
  frontend/src/scenes/early-access-features/EarlyAccessFeature.tsx
  frontend/src/scenes/organization/Settings/VerifiedDomains/__snapshots__/verifiedDomainsLogic.test.ts.snap
  frontend/src/scenes/session-recordings/settings/SessionRecordingSettings.tsx
  frontend/src/scenes/surveys/Survey.tsx
  frontend/src/scenes/surveys/SurveyEdit.tsx
  frontend/src/scenes/teamLogic.tsx
  frontend/src/types.ts
  latest_migrations.manifest
  posthog/admin.py
  posthog/api/decide.py
  posthog/api/team.py
  posthog/api/test/__snapshots__/test_action.ambr
  posthog/api/test/__snapshots__/test_annotation.ambr
  posthog/api/test/__snapshots__/test_decide.ambr
  posthog/api/test/__snapshots__/test_early_access_feature.ambr
  posthog/api/test/__snapshots__/test_element.ambr
  posthog/api/test/__snapshots__/test_insight.ambr
  posthog/api/test/__snapshots__/test_preflight.ambr
  posthog/api/test/__snapshots__/test_survey.ambr
  posthog/api/test/dashboards/__snapshots__/test_dashboard.ambr
  posthog/api/test/notebooks/__snapshots__/test_notebook.ambr
  posthog/api/test/test_decide.py
  posthog/api/test/test_team.py
  posthog/migrations/0356_add_replay_cost_control.py
  posthog/models/filters/test/__snapshots__/test_filter.ambr
  posthog/models/team/team.py
  posthog/session_recordings/test/__snapshots__/test_session_recordings.ambr
  posthog/test/__snapshots__/test_feature_flag.ambr
Labels: you-snizza-bo-logna

#18224 feat: beta tag for sampling controls
  frontend/src/scenes/session-recordings/settings/SessionRecordingSettings.tsx
Labels: you-snizza-bo-logna
