Repository PostHog/posthog, pull requests merged in 2023-11, with the labels that each got.

#18057 fix: spacing for "Addons" text on billing product screen
  frontend/src/scenes/billing/BillingProduct.tsx
Labels: stale

#17731 chore: upgrade react 18
  frontend/__snapshots__/exporter-exporter--dashboard.png
  frontend/__snapshots__/exporter-exporter--trends-number-insight.png
  frontend/__snapshots__/scenes-app-experiments--complete-funnel-experiment.png
  frontend/__snapshots__/scenes-app-experiments--running-trend-experiment.png
  frontend/__snapshots__/scenes-app-insights--funnel-historical-trends-edit--webkit.png
  frontend/__snapshots__/scenes-app-insights--retention-breakdown-edit--webkit.png
  frontend/__snapshots__/scenes-other-billing-v2--billing-v-2-with-discount.png
  frontend/__snapshots__/scenes-other-billing-v2--billing-v-2.png
  frontend/src/exporter/index.tsx
  frontend/src/index.tsx
  frontend/src/lib/lemon-ui/LemonDialog/LemonDialog.tsx
  frontend/src/lib/lemon-ui/LemonMenu/LemonMenu.tsx
  frontend/src/lib/logic/inAppPrompt/inAppPromptLogic.tsx
  frontend/src/lib/logic/promptLogic.tsx
  frontend/src/scenes/funnels/useFunnelTooltip.tsx
  frontend/src/scenes/insights/views/BoldNumber/BoldNumber.tsx
  frontend/src/scenes/insights/views/LineGraph/LineGraph.tsx
  frontend/src/scenes/insights/views/LineGraph/PieChart.tsx
  frontend/src/scenes/insights/views/WorldMap/WorldMap.tsx
  frontend/src/scenes/notebooks/NotebooksTable/NotebooksTable.tsx
  frontend/src/scenes/session-recordings/saved-playlists/SavedSessionRecordingPlaylists.tsx
  frontend/src/scenes/trends/persons-modal/PersonsModal.tsx
  frontend/src/toolbar/index.tsx
  package.json
  pnpm-lock.yaml
Labels: epic

#18559 feat(web-analytics): design tweaks
  frontend/src/queries/nodes/WebOverview/WebOverview.tsx
  frontend/src/scenes/web-analytics/WebDashboard.tsx
  frontend/src/scenes/web-analytics/WebTabs.tsx
  frontend/src/scenes/web-analytics/webAnalyticsLogic.ts
Labels: web-analytics

#18572 feat(web-analytics): add health check warnings
  frontend/src/scenes/web-analytics/WebAnalyticsHealthCheck.tsx
  frontend/src/scenes/web-analytics/WebDashboard.tsx
  frontend/src/scenes/web-analytics/webAnalyticsLogic.ts
  posthog/hogql_queries/web_analytics/web_analytics_query_runner.py
Labels: web-analytics

#18361 chore(surveys): move open feedback template to top
  frontend/src/scenes/surveys/constants.tsx
Labels: stale

#18641 fix(notebooks): handle updates in insight visualization component
  frontend/src/scenes/notebooks/Nodes/NotebookNodeQuery.tsx
Labels: stale

#18733 chore: hobby deployment on PR
  .github/pr-deploy/hobby.yaml.tmpl
  .github/workflows/container-images-ci.yml
  .github/workflows/pr-cleanup.yml
  .github/workflows/pr-deploy.yml
  bin/deploy-hobby
  docker-compose.hobby.yml
Labels: deploy
