Repository PostHog/posthog, pull requests merged in 2023-12, with the labels that each got.

#19129 chore: Hobby SSL
  .github/pr-deploy/hobby.yaml.tmpl
  .github/workflows/pr-deploy.yml
Labels: deploy

#18926 chore: update main README
  README.md
Labels: stale

#18830 chore(deps): Upgrade to Django 4.1
  ee/api/test/__snapshots__/test_organization_resource_access.ambr
  posthog/api/test/__snapshots__/test_decide.ambr
  posthog/api/test/__snapshots__/test_feature_flag.ambr
  posthog/api/test/__snapshots__/test_organization_feature_flag.ambr
  posthog/api/test/__snapshots__/test_plugin.ambr
  posthog/api/test/dashboards/__snapshots__/test_dashboard.ambr
  posthog/api/test/test_organization.py
  posthog/api/test/test_team.py
  posthog/middleware.py
  posthog/models/filters/test/__snapshots__/test_filter.ambr
  posthog/models/test/test_tagged_item_model.py
  posthog/settings/access.py
  posthog/temporal/batch_exports/batch_exports.py
  posthog/temporal/data_imports/external_data_job.py
  posthog/temporal/data_imports/pipelines/stripe/helpers.py
  posthog/temporal/tests/conftest.py
  posthog/temporal/tests/test_external_data_job.py
  posthog/temporal/tests/utils/models.py
  posthog/test/__snapshots__/test_feature_flag.ambr
  requirements-dev.in
  requirements-dev.txt
  requirements.in
  requirements.txt
Labels: deploy

#19282 fix(web-analytics): Fix bug where we tried to compare to previous results, for graph of all time
  frontend/src/scenes/web-analytics/webAnalyticsLogic.ts
Labels: web-analytics

#19305 fix(web-analytics): Fix overview not filtering test users
  posthog/hogql_queries/web_analytics/stats_table.py
  posthog/hogql_queries/web_analytics/test/test_web_overview.py
  posthog/hogql_queries/web_analytics/test/test_web_stats_table.py
  posthog/hogql_queries/web_analytics/web_analytics_query_runner.py
  posthog/hogql_queries/web_analytics/web_overview.py
Labels: web-analytics

#19285 chore(deps): Upgrade to Django 4.1
  ee/api/test/__snapshots__/test_organization_resource_access.ambr
  posthog/api/test/__snapshots__/test_decide.ambr
  posthog/api/test/__snapshots__/test_feature_flag.ambr
  posthog/api/test/__snapshots__/test_organization_feature_flag.ambr
  posthog/api/test/__snapshots__/test_plugin.ambr
  posthog/api/test/dashboards/__snapshots__/test_dashboard.ambr
  posthog/api/test/test_organization.py
  posthog/api/test/test_team.py
  posthog/middleware.py
  posthog/models/filters/test/__snapshots__/test_filter.ambr
  posthog/models/test/test_tagged_item_model.py
  posthog/settings/access.py
  posthog/temporal/batch_exports/batch_exports.py
  posthog/temporal/data_imports/external_data_job.py
  posthog/temporal/tests/conftest.py
  posthog/temporal/tests/test_external_data_job.py
  posthog/temporal/tests/utils/models.py
  posthog/test/__snapshots__/test_feature_flag.ambr
  requirements-dev.in
  requirements-dev.txt
  requirements.in
  requirements.txt
Labels: deploy

#19139 feat(3000): changed color theme ui
  frontend/src/layout/navigation/TopBar/SitePopover.tsx
  frontend/src/lib/lemon-ui/LemonSelect/LemonSelect.tsx
Labels: stale
