Repository PostHog/posthog, pull requests merged in 2023-03, with the labels that each got.

#14231 chore: port most celery metrics to prometheus
  posthog/celery.py
Labels: stale

#14687 feat: allow toggling of autocapture in project settings
  frontend/__snapshots__/scenes-app-insights--trends-world-map--webkit.png
  frontend/src/lib/api.mock.ts
  frontend/src/lib/utils/eventUsageLogic.ts
  frontend/src/scenes/ingestion/ingestionLogic.ts
  frontend/src/scenes/ingestion/panels/SuperpowersPanel.tsx
  frontend/src/scenes/insights/EmptyStates/timeout-state.json
  frontend/src/scenes/organization/Settings/VerifiedDomains/__snapshots__/verifiedDomainsLogic.test.ts.snap
  frontend/src/scenes/project/Settings/AutocaptureSettings.tsx
  frontend/src/scenes/project/Settings/IngestionInfo.tsx
  frontend/src/types.ts
  latest_migrations.manifest
  posthog/api/decide.py
  posthog/api/team.py
  posthog/api/test/__snapshots__/test_action.ambr
  posthog/api/test/__snapshots__/test_annotation.ambr
  posthog/api/test/__snapshots__/test_decide.ambr
  posthog/api/test/__snapshots__/test_element.ambr
  posthog/api/test/__snapshots__/test_insight.ambr
  posthog/api/test/__snapshots__/test_session_recordings.ambr
  posthog/api/test/test_decide.py
  posthog/migrations/0309_team_autocapture_opt_out.py
  posthog/models/team/team.py
  posthog/test/__snapshots__/test_feature_flag.ambr
Labels: highlight :star:

#14308 fix(persons): hide persons in the future
  ee/clickhouse/queries/test/__snapshots__/test_person_query.ambr
  posthog/api/person.py
  posthog/api/test/__snapshots__/test_person.ambr
  posthog/queries/person_query.py
Labels: stale

#14759 feat: allow new insight type choice from sidebar
  cypress/e2e/actions.cy.ts
  cypress/e2e/insights.cy.ts
  cypress/productAnalytics/index.ts
  frontend/src/layout/navigation/SideBar/SideBar.tsx
  frontend/src/scenes/saved-insights/SavedInsights.scss
  frontend/src/scenes/saved-insights/SavedInsights.tsx
  frontend/src/scenes/saved-insights/newInsightsMenu.tsx
Labels: highlight :star:

#14458 chore(recordings): Optimize recordings list query
  frontend/src/lib/constants.tsx
  frontend/src/scenes/session-recordings/playlist/sessionRecordingsListLogic.ts
  posthog/api/session_recording.py
  posthog/api/test/__snapshots__/test_session_recordings.ambr
  posthog/api/test/test_session_recordings.py
  posthog/models/filters/mixins/property.py
  posthog/queries/session_recordings/session_recording_list.py
  posthog/queries/session_recordings/test/__snapshots__/test_session_recording_list.ambr
  posthog/queries/session_recordings/test/test_session_recording_list.py
  posthog/queries/trends/test/__snapshots__/test_formula.ambr
Labels: feature/recordings, performance

#14926 feat: Automatically create deploys for labelled PRs seeded with demo data
  .github/pr-deploy/tailscale.yaml.tmpl
  .github/pr-deploy/values.yaml.tmpl
  .github/workflows/container-images-ci.yml
  .github/workflows/pr-deploy.yml
Labels: deploy
