Repository PostHog/posthog, pull requests merged in 2024-04, with the labels that each got.

#21434 feat: Pass PR labels through to deploy action
  .github/actions/get-pr-labels/action.yml
  .github/workflows/container-images-cd.yml
Labels: feature/actions, canary

#21523 feat: event debug view in the toolbar
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/feature_request.yml
  frontend/__snapshots__/scenes-other-toolbar--actions--light.png
  frontend/__snapshots__/scenes-other-toolbar--actions-dark--dark.png
  frontend/__snapshots__/scenes-other-toolbar--default--dark.png
  frontend/__snapshots__/scenes-other-toolbar--default--light.png
  frontend/__snapshots__/scenes-other-toolbar--default-dark--dark.png
  frontend/__snapshots__/scenes-other-toolbar--default-dark--light.png
  frontend/__snapshots__/scenes-other-toolbar--events-debugger--dark.png
  frontend/__snapshots__/scenes-other-toolbar--events-debugger--light.png
  frontend/__snapshots__/scenes-other-toolbar--events-debugger-dark--dark.png
  frontend/__snapshots__/scenes-other-toolbar--events-debugger-dark--light.png
  frontend/__snapshots__/scenes-other-toolbar--events-debugger-empty--dark.png
  frontend/__snapshots__/scenes-other-toolbar--events-debugger-empty--light.png
  frontend/__snapshots__/scenes-other-toolbar--events-debugger-empty-dark--dark.png
  frontend/__snapshots__/scenes-other-toolbar--events-debugger-empty-dark--light.png
  frontend/__snapshots__/scenes-other-toolbar--feature-flags--light.png
  frontend/__snapshots__/scenes-other-toolbar--feature-flags-dark--dark.png
  frontend/__snapshots__/scenes-other-toolbar--heatmap--light.png
  frontend/__snapshots__/scenes-other-toolbar--inspect--dark.png
  frontend/__snapshots__/scenes-other-toolbar--inspect--light.png
  frontend/__snapshots__/scenes-other-toolbar--inspect-dark--dark.png
  frontend/__snapshots__/scenes-other-toolbar--inspect-dark--light.png
  frontend/src/lib/components/AnimatedCollapsible.tsx
  frontend/src/toolbar/Toolbar.stories.tsx
  frontend/src/toolbar/bar/Toolbar.scss
  frontend/src/toolbar/bar/Toolbar.tsx
  frontend/src/toolbar/bar/toolbarLogic.ts
  frontend/src/toolbar/debug/EventDebugMenu.tsx
  frontend/src/toolbar/debug/eventDebugMenuLogic.ts
Labels: heatmaps-in-the-heat

#18653 chore(deps): Upgrade to Django 4.2
  ee/api/test/__snapshots__/test_organization_resource_access.ambr
  posthog/api/instance_status.py
  posthog/api/property_definition.py
  posthog/api/test/__snapshots__/test_action.ambr
  posthog/api/test/__snapshots__/test_annotation.ambr
  posthog/api/test/__snapshots__/test_decide.ambr
  posthog/api/test/__snapshots__/test_early_access_feature.ambr
  posthog/api/test/__snapshots__/test_element.ambr
  posthog/api/test/__snapshots__/test_feature_flag.ambr
  posthog/api/test/__snapshots__/test_insight.ambr
  posthog/api/test/__snapshots__/test_organization_feature_flag.ambr
  posthog/api/test/__snapshots__/test_plugin.ambr
  posthog/api/test/__snapshots__/test_preflight.ambr
  posthog/api/test/__snapshots__/test_survey.ambr
  posthog/api/test/dashboards/__snapshots__/test_dashboard.ambr
  posthog/api/test/notebooks/__snapshots__/test_notebook.ambr
  posthog/api/test/test_decide.py
  posthog/api/test/test_feature_flag.py
  posthog/models/dashboard_tile.py
  posthog/models/feature_flag/flag_matching.py
  posthog/models/filters/test/__snapshots__/test_filter.ambr
  posthog/queries/app_metrics/test/__snapshots__/test_historical_exports.ambr
  posthog/session_recordings/test/__snapshots__/test_session_recordings.ambr
  posthog/settings/web.py
  posthog/tasks/test/__snapshots__/test_process_scheduled_changes.ambr
  posthog/tasks/usage_report.py
  posthog/test/__snapshots__/test_feature_flag.ambr
  requirements-dev.in
  requirements-dev.txt
  requirements.in
  requirements.txt
Labels: deploy, canary

#21572 feat: Switch from WSGI to ASGI (attempt #2)
  .github/workflows/ci-e2e.yml
  posthog/asgi.py
  posthog/settings/sentry.py
  posthog/wsgi.py
  unit.json
Labels: canary

#20632 feat: Refactor loading of snapshots
  frontend/src/scenes/session-recordings/__mocks__/recording_snapshots.ts
  frontend/src/scenes/session-recordings/file-playback/sessionRecordingFilePlaybackSceneLogic.ts
  frontend/src/scenes/session-recordings/player/inspector/playerInspectorLogic.ts
  frontend/src/scenes/session-recordings/player/sessionRecordingDataLogic.test.ts
  frontend/src/scenes/session-recordings/player/sessionRecordingDataLogic.ts
  frontend/src/scenes/session-recordings/player/sessionRecordingPlayerLogic.test.ts
  frontend/src/scenes/session-recordings/player/sessionRecordingPlayerLogic.ts
  frontend/src/types.ts
Labels: waiting

#21579 feat: Switch from wsgi to asgi (attempt 3)
  .github/workflows/ci-e2e.yml
  posthog/asgi.py
  posthog/settings/sentry.py
  posthog/wsgi.py
  unit.json
Labels: canary

#20736 feat: Swap ingestion endpoints to new .i.posthog.com ones
  bin/deploy-hobby
  cypress/e2e/auto-redirect.cy.ts
  frontend/src/layout.html
  frontend/src/layout/navigation-3000/sidepanel/panels/sidePanelDocsLogic.ts
  frontend/src/lib/components/JSSnippet.tsx
  frontend/src/lib/utils/apiHost.ts
  frontend/src/scenes/feature-flags/FeatureFlagSnippets.tsx
  frontend/src/scenes/notebooks/NotebookTemplates/notebookTemplates.ts
  frontend/src/scenes/onboarding/sdks/sdk-install-instructions/flutter.tsx
  frontend/src/scenes/onboarding/sdks/sdk-install-instructions/next-js.tsx
  frontend/src/scenes/toolbar-launch/ToolbarLaunch.tsx
  plugin-server/src/utils/posthog.ts
  posthog/ph_client.py
  posthog/year_in_posthog/2023.html
  posthog/year_in_posthog/hibernating.html
Labels: waiting

#21629 feat: Heatmaps ingestion
  plugin-server/src/config/config.ts
  plugin-server/src/config/kafka-topics.ts
  plugin-server/src/types.ts
  plugin-server/src/worker/ingestion/event-pipeline/extractHeatmapDataStep.ts
  plugin-server/src/worker/ingestion/event-pipeline/runner.ts
  plugin-server/tests/worker/ingestion/event-pipeline/__snapshots__/extractHeatmapDataStep.test.ts.snap
  plugin-server/tests/worker/ingestion/event-pipeline/__snapshots__/runner.test.ts.snap
  plugin-server/tests/worker/ingestion/event-pipeline/extractHeatmapDataStep.test.ts
  plugin-server/tests/worker/ingestion/event-pipeline/runner.test.ts
Labels: heatmaps-in-the-heat

#21630 feat: Heatmaps toolbar code
  frontend/__snapshots__/scenes-other-billing-v2--billing-v-2--light.png
  frontend/__snapshots__/scenes-other-toolbar--heatmap--dark.png
  frontend/__snapshots__/scenes-other-toolbar--heatmap--light.png
  frontend/__snapshots__/scenes-other-toolbar--heatmap-dark--dark.png
  frontend/__snapshots__/scenes-other-toolbar--heatmap-dark--light.png
  frontend/src/lib/constants.tsx
  frontend/src/loadPostHogJS.tsx
  frontend/src/toolbar/actions/ActionsEditingToolbarMenu.tsx
  frontend/src/toolbar/actions/ActionsListView.tsx
  frontend/src/toolbar/actions/actionsTabLogic.tsx
  frontend/src/toolbar/bar/ToolbarMenu.tsx
  frontend/src/toolbar/elements/AutocaptureElement.tsx
  frontend/src/toolbar/elements/AutocaptureElementLabel.tsx
  frontend/src/toolbar/elements/ElementInfoWindow.tsx
  frontend/src/toolbar/elements/Elements.tsx
  frontend/src/toolbar/elements/Heatmap.tsx
  frontend/src/toolbar/elements/ScrollDepth.tsx
  frontend/src/toolbar/elements/elementsLogic.ts
  frontend/src/toolbar/elements/heatmapLogic.ts
  frontend/src/toolbar/flags/flagsToolbarLogic.ts
  frontend/src/toolbar/posthog.ts
  frontend/src/toolbar/stats/HeatmapToolbarMenu.tsx
  frontend/src/toolbar/stats/currentPageLogic.ts
  frontend/src/toolbar/toolbarConfigLogic.ts
  frontend/src/toolbar/toolbarPosthogJS.ts
  frontend/src/toolbar/types.ts
  frontend/src/toolbar/utils.ts
  package.json
  patches/heatmap.js@2.0.5.patch
  pnpm-lock.yaml
Labels: heatmaps-in-the-heat

#21623 feat: heatmap storage and API
  posthog/api/__init__.py
  posthog/clickhouse/migrations/0059_heatmaps_events.py
  posthog/clickhouse/schema.py
  posthog/clickhouse/test/__snapshots__/test_schema.ambr
  posthog/conftest.py
  posthog/heatmaps/heatmaps_api.py
  posthog/heatmaps/sql.py
  posthog/heatmaps/test/__snapshots__/test_heatmaps_api.ambr
  posthog/heatmaps/test/test_heatmaps_api.py
  posthog/hogql/constants.py
  posthog/hogql/database/database.py
  posthog/hogql/database/schema/heatmaps.py
  posthog/hogql/database/test/__snapshots__/test_database.ambr
  posthog/hogql/escape_sql.py
  posthog/kafka_client/topics.py
Labels: heatmaps-in-the-heat

#21802 fix: Wrap asgi application to ignore lifetime requests
  posthog/asgi.py
Labels: canary

#21848 fix: same numbers everywhere
  posthog/heatmaps/heatmaps_api.py
  posthog/heatmaps/test/__snapshots__/test_heatmaps_api.ambr
  posthog/heatmaps/test/test_heatmaps_api.py
Labels: heatmaps-in-the-heat

#21858 fix: Wrap asgi application to ignore lifetime requests
  posthog/asgi.py
Labels: canary
