Repository PostHog/posthog, pull requests merged in 2024-12, with the labels that each got.

#26615 feat: Add more fallback flags for missing languages
  frontend/src/scenes/insights/views/WorldMap/countryCodes.ts
Labels: team/web-analytics

#26602 fix: Specify `multidict` version on requirements
  requirements-dev.in
  requirements-dev.txt
  requirements.in
  requirements.txt
Labels: dependencies

#26665 build: Add Browserslist update on a schedule
  .github/actions/browserslist-update/action.yml
Labels: github_actions

#26689 fix: Fix base branch for browserlist database update
  .github/actions/browserslist-update/action.yml
Labels: automerge

#26690 fix(chore): Move workflow to the right folder
  .github/workflows/browserslist-update.yml
Labels: automerge

#26691 fix: Pass `github_token` to the `browserslist` action
  .github/workflows/browserslist-update.yml
Labels: automerge

#26703 ci: Configure pnpm/node before running browserslist update
  .github/workflows/browserslist-update.yml
Labels: dependencies

#26725 ci: Use POSTHOG_BOT_GITHUB_TOKEN to allow opening PRs
  .github/workflows/browserslist-update.yml
Labels: dependencies

#26739 feat: Add `CompareFilter` to Web Analytics frontend
  frontend/src/lib/components/CompareFilter/CompareFilter.tsx
  frontend/src/lib/constants.tsx
  frontend/src/queries/schema.json
  frontend/src/queries/schema.ts
  frontend/src/scenes/web-analytics/WebDashboard.tsx
  frontend/src/scenes/web-analytics/webAnalyticsLogic.tsx
  posthog/hogql_queries/web_analytics/test/test_web_overview.py
  posthog/hogql_queries/web_analytics/web_overview.py
  posthog/schema.py
Labels: team/web-analytics

#26849 fix: Fix conflict between posthog toolbar and Tanstack dev tools
  frontend/src/toolbar/ToolbarApp.tsx
Labels: bug

#26822 feat(query_log): add query_log table to hogql
  posthog/hogql/database/database.py
  posthog/hogql/database/schema/query_log.py
  posthog/hogql/database/schema/test/test_table_query_log.py
  posthog/hogql/database/test/__snapshots__/test_database.ambr
  posthog/hogql/printer.py
Labels: feature/hogql

#26932 fix: add fixed heights for date picker and table header (month and buttons)
  frontend/__snapshots__/lemon-ui-lemon-calendar-lemon-calendar--custom-styles--dark.png
  frontend/__snapshots__/lemon-ui-lemon-calendar-lemon-calendar--custom-styles--light.png
  frontend/__snapshots__/lemon-ui-lemon-calendar-lemon-calendar--default--dark.png
  frontend/__snapshots__/lemon-ui-lemon-calendar-lemon-calendar--default--light.png
  frontend/__snapshots__/lemon-ui-lemon-calendar-lemon-calendar--friday-first--dark.png
  frontend/__snapshots__/lemon-ui-lemon-calendar-lemon-calendar--friday-first--light.png
  frontend/__snapshots__/lemon-ui-lemon-calendar-lemon-calendar--hour--dark.png
  frontend/__snapshots__/lemon-ui-lemon-calendar-lemon-calendar--hour--light.png
  frontend/__snapshots__/lemon-ui-lemon-calendar-lemon-calendar--minute--dark.png
  frontend/__snapshots__/lemon-ui-lemon-calendar-lemon-calendar--minute--light.png
  frontend/__snapshots__/lemon-ui-lemon-calendar-lemon-calendar--multiple-months--dark.png
  frontend/__snapshots__/lemon-ui-lemon-calendar-lemon-calendar--multiple-months--light.png
  frontend/__snapshots__/lemon-ui-lemon-calendar-lemon-calendar--saturday-first--dark.png
  frontend/__snapshots__/lemon-ui-lemon-calendar-lemon-calendar--saturday-first--light.png
  frontend/__snapshots__/lemon-ui-lemon-calendar-lemon-calendar--sunday-first--dark.png
  frontend/__snapshots__/lemon-ui-lemon-calendar-lemon-calendar--sunday-first--light.png
  frontend/__snapshots__/lemon-ui-lemon-calendar-lemon-calendar--thursday-first--dark.png
  frontend/__snapshots__/lemon-ui-lemon-calendar-lemon-calendar--thursday-first--light.png
  frontend/__snapshots__/lemon-ui-lemon-calendar-lemon-calendar--wednesday-first--dark.png
  frontend/__snapshots__/lemon-ui-lemon-calendar-lemon-calendar--wednesday-first--light.png
  frontend/__snapshots__/lemon-ui-lemon-calendar-lemon-calendar-select--default--dark.png
  frontend/__snapshots__/lemon-ui-lemon-calendar-lemon-calendar-select--default--light.png
  frontend/__snapshots__/lemon-ui-lemon-calendar-lemon-calendar-select--hour--dark.png
  frontend/__snapshots__/lemon-ui-lemon-calendar-lemon-calendar-select--hour--light.png
  frontend/__snapshots__/lemon-ui-lemon-calendar-lemon-calendar-select--minute--dark.png
  frontend/__snapshots__/lemon-ui-lemon-calendar-lemon-calendar-select--minute--light.png
  frontend/__snapshots__/lemon-ui-lemon-calendar-lemon-calendar-select--past--dark.png
  frontend/__snapshots__/lemon-ui-lemon-calendar-lemon-calendar-select--past--light.png
  frontend/__snapshots__/lemon-ui-lemon-calendar-lemon-calendar-select--upcoming--dark.png
  frontend/__snapshots__/lemon-ui-lemon-calendar-lemon-calendar-select--upcoming--light.png
  frontend/__snapshots__/lemon-ui-lemon-calendar-lemon-calendar-select--with-time-toggle--dark.png
  frontend/__snapshots__/lemon-ui-lemon-calendar-lemon-calendar-select--with-time-toggle--light.png
  frontend/__snapshots__/lemon-ui-lemon-calendar-lemon-calendar-select--with-time-toggle-and-multiple-months--dark.png
  frontend/__snapshots__/lemon-ui-lemon-calendar-lemon-calendar-select--with-time-toggle-and-multiple-months--light.png
  frontend/src/lib/lemon-ui/LemonCalendar/LemonCalendar.scss
  frontend/src/lib/lemon-ui/LemonCalendar/LemonCalendar.tsx
  frontend/src/lib/lemon-ui/LemonCalendar/LemonCalendarSelect.stories.tsx
Labels: design, ux
