Repository PostHog/posthog, pull requests merged in 2024-08, with the labels that each got.

#24124 fix: properties definition filter moved
  frontend/src/scenes/data-management/properties/PropertyDefinitionsTable.tsx
Labels: stale

#24155 fix: self hosted replay storage access
  docker-compose.hobby.yml
  plugin-server/src/main/services/object_storage.ts
Labels: feature/replay

#23246 chore(environments): Add `project_id`-based filtering to API
  ee/api/billing.py
  ee/api/dashboard_collaborator.py
  ee/clickhouse/views/person.py
  ee/urls.py
  posthog/api/__init__.py
  posthog/api/cohort.py
  posthog/api/dashboards/dashboard.py
  posthog/api/documentation.py
  posthog/api/element.py
  posthog/api/event.py
  posthog/api/feature_flag.py
  posthog/api/insight.py
  posthog/api/person.py
  posthog/api/plugin.py
  posthog/api/routing.py
  posthog/api/search.py
  posthog/api/test/__snapshots__/test_action.ambr
  posthog/api/test/__snapshots__/test_feature_flag.ambr
  posthog/api/test/__snapshots__/test_insight.ambr
  posthog/api/test/dashboards/__snapshots__/test_dashboard.ambr
  posthog/api/test/notebooks/__snapshots__/test_notebook.ambr
  posthog/heatmaps/heatmaps_api.py
Labels: stale

#24305 fix(data-warehouse): fix data table in notebooks
  frontend/__snapshots__/exporter-exporter--trends-line-insight-legend--dark.png
  frontend/__snapshots__/exporter-exporter--trends-line-insight-legend--light.png
  frontend/src/queries/Query/Query.tsx
  frontend/src/queries/nodes/DataTable/DataTable.tsx
  frontend/src/queries/nodes/DataTable/dataTableLogic.ts
  frontend/src/queries/nodes/DataTable/renderColumn.tsx
  frontend/src/queries/nodes/DataTable/renderColumnMeta.tsx
  frontend/src/queries/nodes/DataVisualization/Components/Table.tsx
  frontend/src/queries/nodes/DataVisualization/DataVisualization.tsx
  frontend/src/queries/nodes/DataVisualization/dataVisualizationLogic.ts
  frontend/src/queries/nodes/InsightViz/InsightViz.tsx
  frontend/src/queries/types.ts
  frontend/src/scenes/debug/QueryTabs.tsx
  frontend/src/types.ts
Labels: stale

#24423 fix(data-warehouse): De-nest hubspot tables
  posthog/temporal/data_imports/pipelines/hubspot/__init__.py
Labels: stale

#24166 feat: Pull event/property definitions into its own service, so we can get it out of the plugin server
  .github/workflows/rust-docker-build.yml
  rust/Cargo.lock
  rust/Cargo.toml
  rust/common/serve_metrics/Cargo.toml
  rust/common/serve_metrics/src/lib.rs
  rust/property-defs-rs/Cargo.toml
  rust/property-defs-rs/src/app_context.rs
  rust/property-defs-rs/src/config.rs
  rust/property-defs-rs/src/lib.rs
  rust/property-defs-rs/src/main.rs
  rust/property-defs-rs/src/metrics_consts.rs
  rust/property-defs-rs/src/types.rs
Labels: waiting

#24286 fix(insights): hide delete series button when there is a single series
  cypress/e2e/trends.cy.ts
  frontend/__snapshots__/scenes-app-insights--stickiness-edit--light--webkit.png
  frontend/__snapshots__/scenes-app-insights--stickiness-edit--light.png
  frontend/__snapshots__/scenes-app-insights--trends-bar-breakdown-edit--dark--webkit.png
  frontend/__snapshots__/scenes-app-insights--trends-bar-breakdown-edit--dark.png
  frontend/__snapshots__/scenes-app-insights--trends-bar-breakdown-edit--light--webkit.png
  frontend/__snapshots__/scenes-app-insights--trends-bar-breakdown-edit--light.png
  frontend/__snapshots__/scenes-app-insights--trends-bar-edit--dark--webkit.png
  frontend/__snapshots__/scenes-app-insights--trends-bar-edit--light--webkit.png
  frontend/__snapshots__/scenes-app-insights--trends-bar-edit--light.png
  frontend/__snapshots__/scenes-app-insights--trends-line-breakdown-edit--dark--webkit.png
  frontend/__snapshots__/scenes-app-insights--trends-line-breakdown-edit--dark.png
  frontend/__snapshots__/scenes-app-insights--trends-line-breakdown-edit--light--webkit.png
  frontend/__snapshots__/scenes-app-insights--trends-line-breakdown-edit--light.png
  frontend/__snapshots__/scenes-app-insights--trends-line-edit--dark.png
  frontend/__snapshots__/scenes-app-insights--trends-line-edit--light.png
  frontend/__snapshots__/scenes-app-insights--trends-pie-breakdown-edit--dark--webkit.png
  frontend/__snapshots__/scenes-app-insights--trends-pie-breakdown-edit--dark.png
  frontend/__snapshots__/scenes-app-insights--trends-pie-breakdown-edit--light--webkit.png
  frontend/__snapshots__/scenes-app-insights--trends-pie-breakdown-edit--light.png
  frontend/__snapshots__/scenes-app-insights--trends-pie-edit--dark--webkit.png
  frontend/__snapshots__/scenes-app-insights--trends-pie-edit--light--webkit.png
  frontend/__snapshots__/scenes-app-insights--trends-pie-edit--light.png
  frontend/__snapshots__/scenes-app-insights--trends-table-breakdown-edit--light.png
  frontend/__snapshots__/scenes-app-insights--trends-table-edit--dark--webkit.png
  frontend/__snapshots__/scenes-app-insights--trends-table-edit--dark.png
  frontend/__snapshots__/scenes-app-insights--trends-table-edit--light--webkit.png
  frontend/__snapshots__/scenes-app-insights--trends-table-edit--light.png
  frontend/__snapshots__/scenes-app-insights--trends-value-breakdown-edit--light--webkit.png
  frontend/__snapshots__/scenes-app-insights--trends-value-breakdown-edit--light.png
  frontend/__snapshots__/scenes-app-insights--trends-value-edit--light--webkit.png
  frontend/__snapshots__/scenes-app-insights--trends-value-edit--light.png
  frontend/src/queries/nodes/InsightViz/TrendsSeries.tsx
  frontend/src/scenes/insights/filters/ActionFilter/ActionFilterRow/ActionFilterRow.tsx
Labels: waiting

#23626 chore(deps): Upgrade to Django 5
  cypress/e2e/auth-password-reset.cy.ts
  cypress/e2e/auth.cy.ts
  cypress/e2e/auto-redirect.cy.ts
  cypress/e2e/invites.cy.ts
  cypress/e2e/preflight.cy.ts
  cypress/e2e/signup.cy.ts
  cypress/productAnalytics/index.ts
  cypress/support/index.ts
  ee/api/test/test_action.py
  ee/api/test/test_dashboard.py
  ee/api/test/test_event_definition.py
  ee/api/test/test_insight.py
  ee/api/test/test_license.py
  ee/api/test/test_property_definition.py
  ee/api/test/test_tagged_item.py
  ee/billing/billing_manager.py
  ee/billing/test/test_billing_manager.py
  frontend/__snapshots__/scenes-app-insights--funnel-top-to-bottom-breakdown-edit--light.png
  frontend/src/scenes/userLogic.ts
  mypy-baseline.txt
  posthog/api/capture.py
  posthog/api/decide.py
  posthog/api/plugin_log_entry.py
  posthog/api/test/notebooks/test_notebook.py
  posthog/api/test/test_action.py
  posthog/api/test/test_authentication.py
  posthog/api/test/test_capture.py
  posthog/api/test/test_decide.py
  posthog/api/test/test_early_access_feature.py
  posthog/api/test/test_feature_flag.py
  posthog/api/test/test_person.py
  posthog/api/test/test_personal_api_keys.py
  posthog/api/test/test_preflight.py
  posthog/api/test/test_signup.py
  posthog/api/test/test_site_app.py
  posthog/api/test/test_stickiness.py
  posthog/api/test/test_survey.py
  posthog/api/user.py
  posthog/api/utils.py
  posthog/auth.py
  posthog/demo/matrix/matrix.py
  posthog/demo/matrix/taxonomy_inference.py
  posthog/hogql/test/test_query.py
  posthog/middleware.py
  posthog/models/event/util.py
  posthog/models/plugin.py
  posthog/queries/util.py
  posthog/settings/web.py
  posthog/tasks/tasks.py
  posthog/test/test_middleware.py
  posthog/test/test_plugin_log_entry.py
  posthog/test/test_rate_limit.py
  posthog/test/test_urls.py
  posthog/test/test_utils_cors.py
  posthog/urls.py
  posthog/utils.py
  posthog/utils_cors.py
  requirements-dev.txt
  requirements.in
  requirements.txt
Labels: deploy, waiting, canary
