Repository PostHog/posthog, pull requests merged in 2024-07, with the labels that each got.

#21946 feat: buffered canvas playback
  frontend/src/lib/utils.tsx
  frontend/src/scenes/session-recordings/player/rrweb/canvas/canvas-plugin.ts
  frontend/src/toolbar/elements/elementsLogic.ts
Labels: waiting

#23643 feat(insights): histogram_bin_count for total value charts
  posthog/hogql_queries/insights/trends/breakdown.py
  posthog/hogql_queries/insights/trends/test/__snapshots__/test_trends.ambr
  posthog/hogql_queries/insights/trends/test/test_trends_query_runner.py
  posthog/hogql_queries/insights/trends/trends_query_builder.py
  posthog/hogql_queries/insights/trends/trends_query_runner.py
Labels: team/product-analytics

#23805 fix(lemon-ui): a hook in LemonSelect captures an old function reference
  frontend/src/lib/lemon-ui/LemonSelect/LemonSelect.tsx
Labels: team/product-analytics

#23576 refactor(persons): remove persons-hogql-query feature flag
  frontend/__snapshots__/scenes-app-dashboards--insight-legend--dark.png
  frontend/__snapshots__/scenes-app-persons-groups--persons--dark.png
  frontend/__snapshots__/scenes-app-persons-groups--persons--light.png
  frontend/src/lib/constants.tsx
  frontend/src/scenes/cohorts/cohortEditLogic.ts
  frontend/src/scenes/persons-management/tabs/personsSceneLogic.ts
Labels: stale

#23649 fix(insights): polishing of multiple breakdowns in Trends
  frontend/__snapshots__/components-cards-insight-details--trends-world-map--dark.png
  frontend/__snapshots__/components-cards-insight-details--trends-world-map--light.png
  frontend/src/lib/components/ActivityLog/activityLogLogic.insight.test.tsx
  frontend/src/lib/components/ActivityLog/complex.sql
  frontend/src/lib/components/ActivityLog/full_query.sql
  frontend/src/lib/components/ActivityLog/weekly.sql
  frontend/src/lib/components/Cards/InsightCard/InsightDetails.tsx
  frontend/src/queries/nodes/InsightViz/InsightDisplayConfig.tsx
  frontend/src/queries/utils.ts
  frontend/src/scenes/insights/filters/BreakdownFilter/taxonomicBreakdownFilterLogic.test.ts
  frontend/src/scenes/insights/filters/BreakdownFilter/taxonomicBreakdownFilterLogic.ts
  frontend/src/scenes/insights/insightVizDataLogic.ts
  frontend/src/scenes/saved-insights/activityDescriptions.tsx
  posthog/hogql_queries/insights/trends/having.sql
Labels: team/product-analytics

#23993 feat(insights): first time for user math type for Actors Query
  mypy-baseline.txt
  posthog/hogql_queries/insights/test/__snapshots__/test_insight_actors_query_runner.ambr
  posthog/hogql_queries/insights/trends/aggregation_operations.py
  posthog/hogql_queries/insights/trends/test/__snapshots__/test_trends.ambr
  posthog/hogql_queries/insights/trends/test/test_aggregation_operations.py
  posthog/hogql_queries/insights/trends/test/test_trends_actors_query_builder.py
  posthog/hogql_queries/insights/trends/test/test_trends_persons.py
  posthog/hogql_queries/insights/trends/test/test_trends_query_runner.py
  posthog/hogql_queries/insights/trends/trends_actors_query_builder.py
  posthog/hogql_queries/insights/trends/trends_query_builder.py
Labels: team/product-analytics
