Repository PostHog/posthog, pull requests merged in 2024-02, with the labels that each got.

#20006 chore(deps): Upgrade Django 4.1
  ee/api/test/__snapshots__/test_organization_resource_access.ambr
  mypy-baseline.txt
  posthog/api/test/__snapshots__/test_decide.ambr
  posthog/api/test/__snapshots__/test_feature_flag.ambr
  posthog/api/test/__snapshots__/test_organization_feature_flag.ambr
  posthog/api/test/__snapshots__/test_plugin.ambr
  posthog/api/test/dashboards/__snapshots__/test_dashboard.ambr
  posthog/api/test/test_organization.py
  posthog/api/test/test_team.py
  posthog/hogql_queries/insights/trends/trends_query_runner.py
  posthog/middleware.py
  posthog/models/filters/test/__snapshots__/test_filter.ambr
  posthog/models/test/test_tagged_item_model.py
  posthog/settings/access.py
  posthog/temporal/batch_exports/batch_exports.py
  posthog/temporal/data_imports/external_data_job.py
  posthog/temporal/tests/conftest.py
  posthog/temporal/tests/external_data/test_external_data_job.py
  posthog/temporal/tests/utils/models.py
  posthog/test/__snapshots__/test_feature_flag.ambr
  posthog/warehouse/data_load/validate_schema.py
  requirements-dev.txt
  requirements.in
  requirements.txt
Labels: deploy

#20122 fix: reduce toolbar bundle size by 60%
  .gitignore
  frontend/__snapshots__/components-html-elements-display--editable-display--dark.png
  frontend/__snapshots__/components-html-elements-display--editable-display--light.png
  frontend/__snapshots__/components-html-elements-display--editable-display-with-preselection--dark.png
  frontend/__snapshots__/components-html-elements-display--editable-display-with-preselection--light.png
  frontend/__snapshots__/components-html-elements-display--with-uniqueness-check--dark.png
  frontend/__snapshots__/components-html-elements-display--with-uniqueness-check--light.png
  frontend/build.mjs
  frontend/src/lib/components/Cards/TextCard/TextCardModal.tsx
  frontend/src/lib/components/HTMLElementsDisplay/HTMLElementsDisplay.tsx
  frontend/src/lib/lemon-ui/LemonTextArea/LemonTextArea.stories.tsx
  frontend/src/lib/lemon-ui/LemonTextArea/LemonTextArea.tsx
  frontend/src/lib/lemon-ui/LemonTextArea/LemonTextAreaMarkdown.tsx
  frontend/src/lib/lemon-ui/LemonTextArea/index.ts
  frontend/src/scenes/UpgradeModal.tsx
  frontend/src/toolbar/stats/HeatmapToolbarMenu.tsx
  frontend/utils.mjs
  package.json
  pnpm-lock.yaml
Labels: waiting

#20156 feat(experiment): Significance for secondary metrics
  ee/clickhouse/queries/experiments/funnel_experiment_result.py
  ee/clickhouse/queries/experiments/secondary_experiment_result.py
  ee/clickhouse/queries/experiments/trend_experiment_result.py
  ee/clickhouse/views/experiments.py
  ee/clickhouse/views/test/__snapshots__/test_clickhouse_experiment_secondary_results.ambr
  ee/clickhouse/views/test/test_clickhouse_experiment_secondary_results.py
  frontend/src/scenes/experiments/Experiment.tsx
  frontend/src/scenes/experiments/ExperimentResult.tsx
  frontend/src/scenes/experiments/SecondaryMetricsResult.tsx
  frontend/src/scenes/experiments/SecondaryMetricsTable.tsx
  frontend/src/scenes/experiments/experimentLogic.tsx
  frontend/src/types.ts
Labels: stale

#20363 fix: Replace remaining app.posthog.com with us.
  .github/ISSUE_TEMPLATE/bug_report.md
  Dockerfile.cloud
  README.md
  frontend/build.mjs
  frontend/src/lib/components/HedgehogBuddy/sprites/sprites.tsx
  frontend/src/lib/constants.tsx
  posthog/exceptions.py
Labels: stale

#20427 fix(surveys): targeting flag not deleted during updates bug
  posthog/api/survey.py
  posthog/api/test/test_survey.py
Labels: stale
