Repository PostHog/posthog, pull requests merged in 2024-03, with the labels that each got.

#19977 feat: Optimize loading of members in the UI
  frontend/__snapshots__/scenes-app-sidepanels--side-panel-settings--dark.png
  frontend/__snapshots__/scenes-app-sidepanels--side-panel-settings--light.png
  frontend/__snapshots__/scenes-other-settings--settings-project--dark.png
  frontend/__snapshots__/scenes-other-settings--settings-project--light.png
  frontend/src/layout/ErrorProjectUnavailable.tsx
  frontend/src/layout/GlobalModals.tsx
  frontend/src/layout/navigation-3000/sidepanel/panels/activation/activationLogic.ts
  frontend/src/layout/navigation/navigationLogic.ts
  frontend/src/lib/api.mock.ts
  frontend/src/lib/api.ts
  frontend/src/lib/components/MemberSelect.tsx
  frontend/src/lib/components/Subscriptions/views/EditSubscription.tsx
  frontend/src/scenes/organization/membersLogic.tsx
  frontend/src/scenes/settings/organization/Members.tsx
  frontend/src/scenes/settings/organization/VerifiedDomains/__snapshots__/verifiedDomainsLogic.test.ts.snap
  frontend/src/scenes/settings/project/teamMembersLogic.tsx
  frontend/src/scenes/settings/user/TwoFactorAuthentication.tsx
  frontend/src/types.ts
  posthog/api/organization.py
  posthog/api/organization_member.py
  posthog/api/test/__snapshots__/test_api_docs.ambr
  posthog/test/test_middleware.py
Labels: waiting

#20917 fix: Split healthcheck to separate nginx unit app
  unit.json
Labels: deploy

#20804 chore(capture): change 'is False' to 'not'
  posthog/api/capture.py
Labels: stale

#21092 chore: only run depot runner comparison when labelled
  .github/workflows/ci-backend-depot.yml
  .github/workflows/ci-e2e-depot.yml
Labels: test-depot

#21115 chore: remove flag that has been on for four months
  frontend/src/lib/constants.tsx
  frontend/src/scenes/session-recordings/file-playback/sessionRecordingFilePlaybackLogic.ts
  frontend/src/scenes/session-recordings/player/sessionRecordingDataLogic.ts
  frontend/src/scenes/session-recordings/playlist/SessionRecordingsPlaylist.tsx
  frontend/src/scenes/session-recordings/playlist/SessionRecordingsPlaylistTroubleshooting.tsx
Labels: test-depot

#21122 feat: mobile replay onboarding
  frontend/src/lib/constants.tsx
  frontend/src/scenes/onboarding/Onboarding.tsx
  frontend/src/scenes/onboarding/onboardingLogic.tsx
  frontend/src/scenes/onboarding/sdks/SDKs.tsx
  frontend/src/scenes/onboarding/sdks/product-analytics/android.tsx
  frontend/src/scenes/onboarding/sdks/sdk-install-instructions/android.tsx
  frontend/src/scenes/onboarding/sdks/sdksLogic.tsx
  frontend/src/scenes/onboarding/sdks/session-replay/SessionReplaySDKInstructions.tsx
  frontend/src/scenes/onboarding/sdks/session-replay/android.tsx
  frontend/src/scenes/onboarding/sdks/session-replay/index.tsx
  frontend/src/scenes/urls.ts
Labels: test-depot
