Repository PostHog/posthog, pull requests merged in 2024-06, with the labels that each got.

#22475 remove unnecessary deleteRecordSuccess call in managed proxy
  frontend/src/scenes/settings/project/proxyLogic.ts
Labels: stale

#22747 chore: we're assigning cache ages let's count then
  posthog/caching/insight_cache.py
  posthog/caching/insight_caching_state.py
Labels: nerd sniped

#22746 fix: consider soft deleted when syncing caching state
  posthog/caching/insight_caching_state.py
  posthog/caching/test/test_insight_caching_state.py
Labels: nerd sniped

#22776 chore: metric for batch insight caching state updates
  posthog/caching/insight_caching_state.py
Labels: nerd sniped

#22932 chore: upgrade python to 3.11 :snake:
  .devcontainer/Dockerfile
  .github/actions/run-backend-tests/action.yml
  .github/workflows/benchmark.yml
  .github/workflows/ci-backend-update-test-timing.yml
  .github/workflows/ci-backend.yml
  .github/workflows/ci-hog.yml
  .github/workflows/ci-plugin-server.yml
  .run/Celery Beat.run.xml
  .run/Celery Threads.run.xml
  .run/Celery.run.xml
  .run/PostHog.run.xml
  bin/build-schema-python.sh
  bin/deploy-hobby
  ee/api/test/__snapshots__/test_time_to_see_data.ambr
  mypy.ini
  posthog/api/comments.py
  posthog/api/feature_flag.py
  posthog/api/plugin.py
  posthog/api/routing.py
  posthog/api/test/__snapshots__/test_api_docs.ambr
  posthog/api/user.py
  posthog/api/utils.py
  posthog/batch_exports/models.py
  posthog/clickhouse/table_engines.py
  posthog/constants.py
  posthog/decorators.py
  posthog/demo/matrix/randomization.py
  posthog/demo/products/hedgebox/models.py
  posthog/hogql/ast.py
  posthog/hogql/constants.py
  posthog/hogql_queries/legacy_compatibility/filter_to_query.py
  posthog/kafka_client/client.py
  posthog/management/commands/create_channel_definitions_file.py
  posthog/models/feature_flag/flag_matching.py
  posthog/models/plugin.py
  posthog/models/property/property.py
  posthog/schema.py
  production.Dockerfile
  requirements-dev.txt
  requirements.in
  requirements.txt
  unit.json.tpl
Labels: canary

#23235 feat(web-analytics): Add live stats logic
  frontend/src/lib/constants.tsx
  frontend/src/scenes/web-analytics/WebAnalyticsLiveUserCount.tsx
  frontend/src/scenes/web-analytics/WebDashboard.tsx
  frontend/src/scenes/web-analytics/liveWebAnalyticsLogic.tsx
Labels: team/web-analytics

#22778 fix: Update bug_report.yml to include link to EU
  .github/ISSUE_TEMPLATE/bug_report.yml
Labels: stale
