Repository PostHog/posthog, pull requests merged in 2024-11, with the labels that each got.

#25553 fix(event): Data Management page event filter reset after viewing a r…
  frontend/src/scenes/data-management/definition/DefinitionView.tsx
Labels: stale

#26104 feat(trends): improve filtering trends results
  frontend/__snapshots__/scenes-app-insights-error-empty-states--long-loading--dark.png
  frontend/src/scenes/insights/views/InsightsTable/InsightsTable.tsx
Labels: deploy

#25736 chore: upgrade rrweb to alpha.17
  frontend/src/scenes/session-recordings/player/rrweb/canvas/canvas-plugin.ts
  frontend/src/scenes/session-recordings/player/rrweb/index.ts
  frontend/src/scenes/session-recordings/player/sessionRecordingPlayerLogic.ts
  frontend/src/types.ts
  package.json
  patches/rrweb@2.0.0-alpha.13.patch
  patches/rrweb@2.0.0-alpha.17.patch
  pnpm-lock.yaml
Labels: stale

#26070 feat: Update README
  README.md
Labels: stale

#26159 feat: rbac middleware
  ee/api/rbac/access_control.py
  ee/api/rbac/role.py
  ee/api/rbac/test/test_access_control.py
  ee/api/test/__snapshots__/test_instance_settings.ambr
  ee/api/test/__snapshots__/test_organization_resource_access.ambr
  ee/api/test/test_action.py
  ee/api/test/test_organization.py
  ee/api/test/test_project.py
  ee/api/test/test_team.py
  ee/clickhouse/views/test/test_clickhouse_experiments.py
  posthog/api/dashboards/dashboard.py
  posthog/api/documentation.py
  posthog/api/feature_flag.py
  posthog/api/insight.py
  posthog/api/notebook.py
  posthog/api/organization.py
  posthog/api/organization_member.py
  posthog/api/project.py
  posthog/api/routing.py
  posthog/api/search.py
  posthog/api/team.py
  posthog/api/test/__snapshots__/test_action.ambr
  posthog/api/test/__snapshots__/test_annotation.ambr
  posthog/api/test/__snapshots__/test_api_docs.ambr
  posthog/api/test/__snapshots__/test_decide.ambr
  posthog/api/test/__snapshots__/test_element.ambr
  posthog/api/test/__snapshots__/test_feature_flag.ambr
  posthog/api/test/__snapshots__/test_insight.ambr
  posthog/api/test/__snapshots__/test_organization_feature_flag.ambr
  posthog/api/test/__snapshots__/test_plugin.ambr
  posthog/api/test/dashboards/__snapshots__/test_dashboard.ambr
  posthog/api/test/dashboards/test_dashboard.py
  posthog/api/test/notebooks/__snapshots__/test_notebook.ambr
  posthog/api/test/notebooks/test_notebook.py
  posthog/api/test/test_action.py
  posthog/api/test/test_activity_log.py
  posthog/api/test/test_annotation.py
  posthog/api/test/test_cohort.py
  posthog/api/test/test_decide.py
  posthog/api/test/test_event.py
  posthog/api/test/test_feature_flag.py
  posthog/api/test/test_insight.py
  posthog/api/test/test_organization.py
  posthog/api/test/test_organization_feature_flag.py
  posthog/api/test/test_person.py
  posthog/api/test/test_plugin.py
  posthog/api/test/test_survey.py
  posthog/middleware.py
  posthog/permissions.py
  posthog/rbac/access_control_api_mixin.py
  posthog/rbac/test/test_user_access_control.py
  posthog/rbac/user_access_control.py
  posthog/session_recordings/test/__snapshots__/test_session_recordings.ambr
  posthog/test/test_middleware.py
  posthog/utils.py
  posthog/warehouse/api/test/test_external_data_source.py
Labels: canary

#26464 fix: fixed popover overflowing edge of browser
  frontend/src/lib/lemon-ui/Popover/Popover.tsx
Labels: bug, design
