Repository PostHog/posthog, pull requests merged in 2024-09, with the labels that each got.

#24463 feat(insights): generate trends using GenAI
  .github/workflows/rust-docker-build.yml
  ee/hogai/__init__.py
  ee/hogai/generate_trends_agent.py
  ee/hogai/hardcoded_definitions.py
  ee/hogai/system_prompt.py
  ee/hogai/team_prompt.py
  ee/hogai/trends_function.py
  frontend/__snapshots__/components-command-bar--actions--dark.png
  frontend/__snapshots__/components-command-bar--actions--light.png
  frontend/__snapshots__/components-command-bar--search--dark.png
  frontend/__snapshots__/components-command-bar--search--light.png
  frontend/__snapshots__/scenes-other-settings--settings-user--dark.png
  frontend/__snapshots__/scenes-other-settings--settings-user--light.png
  frontend/src/layout/navigation-3000/navigationLogic.tsx
  frontend/src/lib/api.ts
  frontend/src/lib/components/CommandBar/ActionResult.tsx
  frontend/src/lib/components/CommandBar/ActionResults.tsx
  frontend/src/lib/components/CommandBar/SearchResult.tsx
  frontend/src/lib/components/CommandBar/index.scss
  frontend/src/lib/components/HedgehogBuddy/HedgehogBuddy.tsx
  frontend/src/lib/components/HedgehogBuddy/HedgehogBuddyRender.tsx
  frontend/src/lib/components/HedgehogBuddy/sprites/sprites.tsx
  frontend/src/lib/lemon-ui/LemonInput/LemonInput.scss
  frontend/src/lib/lemon-ui/LemonInput/LemonInput.tsx
  frontend/src/lib/lemon-ui/icons/categories.ts
  frontend/src/queries/schema.json
  frontend/src/queries/schema.ts
  frontend/src/scenes/appScenes.ts
  frontend/src/scenes/max/Max.scss
  frontend/src/scenes/max/Max.tsx
  frontend/src/scenes/max/maxLogic.ts
  frontend/src/scenes/sceneTypes.ts
  frontend/src/scenes/scenes.ts
  frontend/src/scenes/urls.ts
  package.json
  pnpm-lock.yaml
  posthog/api/query.py
  posthog/api/test/__snapshots__/test_api_docs.ambr
  posthog/schema.py
  requirements-dev.in
  requirements-dev.txt
  requirements.in
  requirements.txt
Labels: waiting

#24901 fix: retention query returns wrong results with target_first_time
  posthog/hogql_queries/insights/retention_query_runner.py
  posthog/hogql_queries/insights/test/test_retention_query_runner.py
Labels: team/product-analytics

#24882 feat(hog): standardize event fields
  .github/workflows/rust-docker-build.yml
  frontend/src/scenes/pipeline/hogfunctions/hogFunctionConfigurationLogic.tsx
  frontend/src/types.ts
  plugin-server/src/cdp/types.ts
  plugin-server/src/cdp/utils.ts
  plugin-server/tests/cdp/hog-executor.test.ts
  posthog/cdp/templates/activecampaign/test_template_activecampaign.py
  posthog/cdp/templates/avo/template_avo.py
  posthog/cdp/templates/avo/test_template_avo.py
  posthog/cdp/templates/braze/template_braze.py
  posthog/cdp/templates/braze/test_template_braze.py
  posthog/cdp/templates/clearbit/template_clearbit.py
  posthog/cdp/templates/customerio/template_customerio.py
  posthog/cdp/templates/customerio/test_template_customerio.py
  posthog/cdp/templates/engage/template_engage.py
  posthog/cdp/templates/gleap/template_gleap.py
  posthog/cdp/templates/gleap/test_template_gleap.py
  posthog/cdp/templates/google_cloud_storage/template_google_cloud_storage.py
  posthog/cdp/templates/google_cloud_storage/test_template_google_cloud_storage.py
  posthog/cdp/templates/google_pubsub/template_google_pubsub.py
  posthog/cdp/templates/google_pubsub/test_template_google_pubsub.py
  posthog/cdp/templates/helpers.py
  posthog/cdp/templates/intercom/template_intercom.py
  posthog/cdp/templates/knock/template_knock.py
  posthog/cdp/templates/knock/test_knock_template.py
  posthog/cdp/templates/loops/template_loops.py
  posthog/cdp/templates/loops/test_template_loops.py
  posthog/cdp/templates/posthog/template_posthog.py
  posthog/cdp/templates/posthog/test_template_posthog.py
  posthog/cdp/templates/rudderstack/template_rudderstack.py
  posthog/cdp/templates/rudderstack/test_template_rudderstack.py
  posthog/cdp/templates/salesforce/template_salesforce.py
  posthog/cdp/templates/slack/template_slack.py
  posthog/cdp/templates/zapier/template_zapier.py
  posthog/cdp/templates/zendesk/test_template_zendesk.py
Labels: stale
