Repository PostHog/posthog, pull requests merged in 2025-08, with the labels that each got.

#35979 feat(max): /remember command
  ee/hogai/eval/eval_memory.py
  ee/hogai/graph/memory/nodes.py
  ee/hogai/graph/memory/prompts.py
  ee/hogai/graph/root/nodes.py
  frontend/src/scenes/max/Thread.tsx
  frontend/src/scenes/max/components/QuestionInput.tsx
  frontend/src/scenes/max/components/SlashCommandAutocomplete.tsx
Labels: evals-ready

#35964 fix: add feedback button on all survey pages
  frontend/src/scenes/surveys/SurveyTemplates.tsx
  frontend/src/scenes/surveys/SurveyView.tsx
  frontend/src/scenes/surveys/Surveys.tsx
  frontend/src/scenes/surveys/components/SurveyFeedbackButton.tsx
Labels: feature/surveys

#35630 chore: increase auth form column max-width
  frontend/src/lib/components/BridgePage/BridgePage.scss
Labels: stale

#36141 chore(max): Final query generation fixes
  ee/hogai/eval/eval_trends.py
  ee/hogai/graph/funnels/prompts.py
  ee/hogai/graph/query_planner/nodes.py
  ee/hogai/graph/retention/prompts.py
  ee/hogai/graph/shared_prompts.py
  ee/hogai/graph/trends/prompts.py
Labels: evals-ready

#35614 feat(max): allow the filter tool to take a dynamic response format and a dynamic prompt
  ee/hogai/assistant.py
  ee/hogai/eval/eval_tool_filter_generation.py
  ee/hogai/graph/base.py
  ee/hogai/graph/filter_options/__init__.py
  ee/hogai/graph/filter_options/graph.py
  ee/hogai/graph/filter_options/nodes.py
  ee/hogai/graph/filter_options/prompts.py
  ee/hogai/graph/filter_options/test/__init__.py
  ee/hogai/graph/filter_options/test/test_graph.py
  ee/hogai/graph/filter_options/test/test_nodes.py
  ee/hogai/graph/filter_options/toolkit.py
  ee/hogai/graph/filter_options/types.py
  ee/hogai/graph/mixins.py
  ee/hogai/graph/query_planner/toolkit.py
  ee/hogai/graph/taxonomy/__init__.py
  ee/hogai/graph/taxonomy/agent.py
  ee/hogai/graph/taxonomy/nodes.py
  ee/hogai/graph/taxonomy/prompts.py
  ee/hogai/graph/taxonomy/test/__init__.py
  ee/hogai/graph/taxonomy/test/test_agent.py
  ee/hogai/graph/taxonomy/test/test_nodes.py
  ee/hogai/graph/taxonomy/test/test_toolkit.py
  ee/hogai/graph/taxonomy/test/test_tools.py
  ee/hogai/graph/taxonomy/toolkit.py
  ee/hogai/graph/taxonomy/tools.py
  ee/hogai/graph/taxonomy/types.py
  ee/hogai/utils/exceptions.py
  ee/hogai/utils/state.py
  products/replay/backend/max_tools.py
  products/replay/backend/prompts.py
  pyproject.toml
  uv.lock
Labels: evals-ready

#36790 chore: insight search UX improvements
  ee/hogai/assistant.py
  ee/hogai/graph/insights/nodes.py
  ee/hogai/graph/insights/prompts.py
Labels: feature/max-ai

#36846 chore: insight search prompt improvements
  ee/hogai/graph/insights/prompts.py
Labels: feature/max-ai, evals-ready

#36004 feat(capture-rs): migrate /i/v0/e/ and /batch/ endpoints to unify event processing
  rust/capture/src/router.rs
  rust/capture/src/v0_endpoint.rs
  rust/capture/tests/events.rs
  rust/capture/tests/integration_new_endpoints.rs
  rust/capture/tests/integration_next_endpoints.rs
Labels: waiting

#36880 fix: strengthening prompts to improve Max's use of 'search_documentation'
  ee/hogai/eval/conftest.py
  ee/hogai/eval/eval_root.py
  ee/hogai/eval/eval_root_style.py
  ee/hogai/graph/root/prompts.py
  ee/hogai/tool.py
Labels: feature/max-ai, evals-ready

#36960 fix: hosted survey missing styles for emoji rating
  posthog/templates/surveys/public_survey.html
Labels: feature/surveys

#37016 fix(charts): enable horizontal scrolling in chart tooltips
  frontend/src/scenes/insights/InsightTooltip/InsightTooltip.scss
  frontend/src/scenes/insights/views/LineGraph/LineGraph.tsx
Labels: bug, feature/insights

#37032 chore(max): add the end/start of day in the date filters
  ee/hogai/eval/max_tools/eval_session_replay_filter_generation.py
  products/replay/backend/prompts.py
Labels: evals-ready

#37159 fix(max): Improve query generation for unique users search
  ee/hogai/eval/max_tools/eval_hogql_generator_tool.py
  ee/hogai/graph/sql/prompts.py
Labels: evals-ready

#37175 chore: lazy loading stream writer
  ee/hogai/graph/insights/nodes.py
  ee/hogai/graph/insights/test/test_nodes.py
Labels: feature/max-ai

#37002 fix(max): hogql get better at matching properties
  ee/hogai/eval/ci/max_tools/eval_hogql_generator_tool.py
  ee/hogai/graph/taxonomy/prompts.py
  products/data_warehouse/backend/max_tools.py
  products/data_warehouse/backend/prompts.py
Labels: evals-ready

#37230 fix(max): adding initialMaxPrompt to actually be in the prompt
  frontend/src/scenes/max/maxLogic.tsx
Labels: feature/max-ai

#37292 feat(max): suggestions from MaxTool(s) now showing in UI
  frontend/src/scenes/max/Max.stories.tsx
  frontend/src/scenes/max/MaxTool.tsx
  frontend/src/scenes/max/max-constants.tsx
  frontend/src/scenes/max/maxGlobalLogic.tsx
  frontend/src/scenes/max/maxLogic.test.ts
  frontend/src/scenes/max/maxLogic.tsx
Labels: feature/max-ai

#37126 fix: survey responses not showing due to time filter
  frontend/src/scenes/surveys/surveyLogic.tsx
  frontend/src/scenes/surveys/utils.test.ts
  frontend/src/scenes/surveys/utils.ts
Labels: feature/surveys

#37364 feat: Evaluate replay-related routing
  ee/hogai/eval/ci/eval_session_summarization.py
Labels: evals-ready

#37336 chore: add dashboard insight refreshed event
  frontend/src/lib/utils/eventUsageLogic.ts
  frontend/src/scenes/dashboard/dashboardLogic.tsx
Labels: team/analytics-platform
