Repository PostHog/posthog, pull requests merged in 2025-01, with the labels that each got.

#27061 chore: release issue grouping
  frontend/src/lib/constants.tsx
  frontend/src/scenes/error-tracking/ErrorTrackingFilters.tsx
  frontend/src/scenes/error-tracking/ErrorTrackingIssueScene.tsx
  frontend/src/scenes/error-tracking/ErrorTrackingScene.tsx
  frontend/src/scenes/error-tracking/errorTrackingDataNodeLogic.tsx
  frontend/src/scenes/error-tracking/errorTrackingIssueSceneLogic.ts
  frontend/src/scenes/error-tracking/errorTrackingLogic.ts
  frontend/src/scenes/error-tracking/errorTrackingSceneLogic.ts
  posthog/api/__init__.py
  posthog/api/error_tracking.py
Labels: stale

#27112 fix(Surveys): do not show adaptive limits UI if feature flag is disabled
  frontend/src/scenes/surveys/SurveyEdit.tsx
Labels: stale

#27176 feat: Add human friendly comparison periods toggle
  frontend/__snapshots__/scenes-other-settings--settings-project--dark.png
  frontend/__snapshots__/scenes-other-settings--settings-project--light.png
  frontend/__snapshots__/scenes-other-settings--settings-project-with-replay-features--dark.png
  frontend/__snapshots__/scenes-other-settings--settings-project-with-replay-features--light.png
  frontend/__snapshots__/scenes-other-settings--settings-session-timeout-all-options--dark.png
  frontend/__snapshots__/scenes-other-settings--settings-session-timeout-all-options--light.png
  frontend/__snapshots__/scenes-other-settings--settings-session-timeout-password-only--dark.png
  frontend/__snapshots__/scenes-other-settings--settings-session-timeout-password-only--light.png
  frontend/__snapshots__/scenes-other-settings--settings-session-timeout-sso-enforced-github--dark.png
  frontend/__snapshots__/scenes-other-settings--settings-session-timeout-sso-enforced-github--light.png
  frontend/__snapshots__/scenes-other-settings--settings-session-timeout-sso-enforced-google--dark.png
  frontend/__snapshots__/scenes-other-settings--settings-session-timeout-sso-enforced-google--light.png
  frontend/__snapshots__/scenes-other-settings--settings-session-timeout-sso-enforced-saml--dark.png
  frontend/__snapshots__/scenes-other-settings--settings-session-timeout-sso-enforced-saml--light.png
  frontend/__snapshots__/scenes-other-settings--settings-session-timeout-sso-only--dark.png
  frontend/__snapshots__/scenes-other-settings--settings-session-timeout-sso-only--light.png
  frontend/src/lib/api.mock.ts
  frontend/src/scenes/settings/SettingsMap.tsx
  frontend/src/scenes/settings/environment/HumanFriendlyComparisonPeriodsSetting.tsx
  frontend/src/scenes/settings/organization/VerifiedDomains/__snapshots__/verifiedDomainsLogic.test.ts.snap
  frontend/src/scenes/settings/types.ts
  frontend/src/scenes/teamActivityDescriber.tsx
  frontend/src/types.ts
  posthog/api/team.py
  posthog/api/test/__snapshots__/test_action.ambr
  posthog/api/test/__snapshots__/test_annotation.ambr
  posthog/api/test/__snapshots__/test_decide.ambr
  posthog/api/test/__snapshots__/test_early_access_feature.ambr
  posthog/api/test/__snapshots__/test_element.ambr
  posthog/api/test/__snapshots__/test_feature_flag.ambr
  posthog/api/test/__snapshots__/test_insight.ambr
  posthog/api/test/__snapshots__/test_organization_feature_flag.ambr
  posthog/api/test/__snapshots__/test_preflight.ambr
  posthog/api/test/__snapshots__/test_survey.ambr
  posthog/api/test/dashboards/__snapshots__/test_dashboard.ambr
  posthog/api/test/notebooks/__snapshots__/test_notebook.ambr
  posthog/hogql_queries/utils/query_compare_to_date_range.py
  posthog/hogql_queries/utils/test/test_query_compare_to_date_range.py
  posthog/migrations/0540_team_human_friendly_comparison_periods.py
  posthog/migrations/max_migration.txt
  posthog/models/filters/test/__snapshots__/test_filter.ambr
  posthog/models/team/team.py
  posthog/session_recordings/test/__snapshots__/test_session_recordings.ambr
  posthog/tasks/test/__snapshots__/test_process_scheduled_changes.ambr
  posthog/test/__snapshots__/test_feature_flag.ambr
  posthog/utils.py
Labels: team/product-analytics, team/web-analytics

#27394 chore: Enable web vitals capture
  frontend/src/loadPostHogJS.tsx
Labels: team/web-analytics

#27409 feat: Add P75 quantile for Core Web Vitals - and globally
  frontend/src/lib/components/InsightLabel/index.tsx
  frontend/src/queries/schema.json
  frontend/src/scenes/cohorts/CohortFilters/constants.tsx
  frontend/src/scenes/trends/mathsLogic.tsx
  frontend/src/types.ts
  posthog/api/documentation.py
  posthog/hogql_queries/insights/trends/aggregation_operations.py
  posthog/hogql_queries/insights/trends/test/test_aggregation_operations.py
  posthog/hogql_queries/insights/trends/test/test_trends.py
  posthog/management/commands/compare_hogql_insights.py
  posthog/models/entity/entity.py
  posthog/queries/test/test_trends.py
  posthog/queries/trends/util.py
  posthog/schema.py
Labels: team/web-analytics

#27413 chore: Use `actions/{download,upload}-artifact@v4`
  .github/workflows/benchmark.yml
  .github/workflows/build-hogql-parser.yml
  .github/workflows/ci-backend.yml
  .github/workflows/ci-e2e.yml
  .github/workflows/ci-plugin-server.yml
  .github/workflows/storybook-chromatic.yml
  frontend/__snapshots__/scenes-app-sidepanels--side-panel-docs--dark.png
  frontend/__snapshots__/scenes-app-sidepanels--side-panel-docs--light.png
Labels: automerge

#27067 chore(experiments): Tests covering materialized columns support
  posthog/hogql_queries/experiments/test/test_experiment_trends_query_runner.py
Labels: waiting

#27415 feat(llm-obs): LLM observability dashboard
  frontend/src/layout/navigation-3000/navigationLogic.tsx
  frontend/src/lib/constants.tsx
  frontend/src/scenes/appScenes.ts
  frontend/src/scenes/llm-observability/LLMObservabilityScene.tsx
  frontend/src/scenes/llm-observability/llmObservabilityLogic.tsx
  frontend/src/scenes/sceneTypes.ts
  frontend/src/scenes/scenes.ts
  frontend/src/scenes/urls.ts
  posthog/demo/matrix/models.py
  posthog/demo/products/__init__.py
  posthog/demo/products/spikegpt/__init__.py
  posthog/demo/products/spikegpt/data.py
  posthog/demo/products/spikegpt/matrix.py
  posthog/demo/products/spikegpt/models.py
  posthog/demo/products/spikegpt/taxonomy.py
  posthog/management/commands/generate_demo_data.py
  requirements-dev.in
  requirements-dev.txt
Labels: deploy

#27155 fix: Update Svelte Onboarding Code
  frontend/src/scenes/onboarding/sdks/sdk-install-instructions/svelte.tsx
Labels: stale

#27479 feat: Add base CoreWebVitals view
  ee/clickhouse/views/test/funnel/__snapshots__/test_clickhouse_funnel_person.ambr
  frontend/src/layout/navigation-3000/navigationLogic.tsx
  frontend/src/layout/navigation/SideBar/SidebarChangeNotice.tsx
  frontend/src/lib/components/Alerts/insightAlertsLogic.ts
  frontend/src/lib/lemon-ui/LemonMenu/LemonMenu.tsx
  frontend/src/lib/lemon-ui/LemonSegmentedSelect/LemonSegmentedSelect.tsx
  frontend/src/lib/lemon-ui/Tooltip/Tooltip.tsx
  frontend/src/queries/Query/Query.tsx
  frontend/src/queries/nodes/CoreWebVitals/CoreWebVitals.tsx
  frontend/src/queries/nodes/CoreWebVitals/CoreWebVitalsContent.tsx
  frontend/src/queries/nodes/CoreWebVitals/CoreWebVitalsProgressBar.tsx
  frontend/src/queries/nodes/CoreWebVitals/CoreWebVitalsTab.scss
  frontend/src/queries/nodes/CoreWebVitals/CoreWebVitalsTab.tsx
  frontend/src/queries/nodes/CoreWebVitals/definitions.ts
  frontend/src/queries/schema.json
  frontend/src/queries/schema/schema-general.ts
  frontend/src/queries/utils.ts
  frontend/src/scenes/insights/aggregationAxisFormat.ts
  frontend/src/scenes/insights/insightVizDataLogic.ts
  frontend/src/scenes/insights/views/LineGraph/LineGraph.tsx
  frontend/src/scenes/saved-insights/SavedInsights.tsx
  frontend/src/scenes/trends/trendsDataLogic.ts
  frontend/src/scenes/trends/viz/ActionsLineGraph.tsx
  frontend/src/scenes/web-analytics/WebAnalyticsHealthCheck.tsx
  frontend/src/scenes/web-analytics/WebDashboard.tsx
  frontend/src/scenes/web-analytics/tiles/WebAnalyticsTile.tsx
  frontend/src/scenes/web-analytics/webAnalyticsLogic.tsx
  posthog/schema.py
Labels: team/web-analytics

#27559 feat(source-connection-string): Postgres connection string configuration
  frontend/src/scenes/data-warehouse/external/forms/SourceForm.tsx
  frontend/src/scenes/data-warehouse/external/forms/parseConnectionString.ts
  frontend/src/scenes/data-warehouse/new/NewSourceWizard.tsx
  frontend/src/scenes/data-warehouse/new/sourceWizardLogic.tsx
Labels: team/data-warehouse

#24527 refactor(insights): add migration to convert filters to query
  posthog/migrations/0545_insight_filters_to_query.py
  posthog/migrations/max_migration.txt
Labels: waiting

#27576 perf(quereies): run queries over websockets
  frontend/src/queries/query.ts
  frontend/src/queries/queryWebSocket.ts
  posthog/api/query_ws.py
  posthog/api/test/test_query_ws.py
  posthog/api/websocket.py
  posthog/asgi.py
  posthog/settings/web.py
  requirements.in
  requirements.txt
Labels: deploy

#27611 refactor: Couple touches for Core Web Vitals
  frontend/src/lib/components/TaxonomicFilter/InfiniteList.tsx
  frontend/src/lib/utils/definitions.ts
  frontend/src/queries/nodes/CoreWebVitals/CoreWebVitals.tsx
  frontend/src/queries/nodes/CoreWebVitals/CoreWebVitalsProgressBar.tsx
  frontend/src/queries/nodes/CoreWebVitals/CoreWebVitalsTab.tsx
  frontend/src/queries/nodes/CoreWebVitals/definitions.ts
  frontend/src/queries/nodes/WebOverview/WebOverview.tsx
  frontend/src/scenes/llm-observability/llmObservabilityLogic.tsx
  frontend/src/scenes/web-analytics/WebDashboard.tsx
  frontend/src/scenes/web-analytics/tiles/WebAnalyticsTile.tsx
  frontend/src/scenes/web-analytics/webAnalyticsLogic.tsx
Labels: team/web-analytics

#27653 fix: Fix staleness check
  frontend/__snapshots__/exporter-exporter--dashboard--dark.png
  frontend/__snapshots__/filters-taxonomic-filter--events-free--dark.png
  frontend/__snapshots__/filters-taxonomic-filter--events-free--light.png
  frontend/__snapshots__/filters-taxonomic-filter--events-premium--dark.png
  frontend/__snapshots__/filters-taxonomic-filter--events-premium--light.png
  frontend/src/lib/components/TaxonomicFilter/InfiniteList.tsx
Labels: team/web-analytics

#27663 feat: Add Core Web Vitals path breakdown
  frontend/src/layout/navigation-3000/navigationLogic.tsx
  frontend/src/queries/Query/Query.tsx
  frontend/src/queries/nodes/CoreWebVitals/CoreWebVitalsContent.tsx
  frontend/src/queries/nodes/CoreWebVitals/CoreWebVitalsPathBreakdown.tsx
  frontend/src/queries/nodes/CoreWebVitals/CoreWebVitalsProgressBar.tsx
  frontend/src/queries/nodes/CoreWebVitals/definitions.ts
  frontend/src/queries/schema.json
  frontend/src/queries/schema/schema-general.ts
  frontend/src/queries/utils.ts
  frontend/src/scenes/saved-insights/SavedInsights.tsx
  frontend/src/scenes/scenes.ts
  frontend/src/scenes/web-analytics/WebDashboard.tsx
  frontend/src/scenes/web-analytics/tiles/WebAnalyticsTile.tsx
  frontend/src/scenes/web-analytics/webAnalyticsLogic.tsx
  posthog/hogql_queries/query_runner.py
  posthog/hogql_queries/web_analytics/core_web_vitals_path_breakdown.py
  posthog/hogql_queries/web_analytics/stats_table.py
  posthog/hogql_queries/web_analytics/test/test_core_web_vitals_path_breakdown.py
  posthog/hogql_queries/web_analytics/web_analytics_query_runner.py
  posthog/schema.py
Labels: team/web-analytics

#27691 refactor: Rename Core Web Vitals to Web Vitals
  frontend/src/layout/navigation-3000/navigationLogic.tsx
  frontend/src/lib/constants.tsx
  frontend/src/queries/Query/Query.tsx
  frontend/src/queries/nodes/WebVitals/WebVitals.tsx
  frontend/src/queries/nodes/WebVitals/WebVitalsContent.tsx
  frontend/src/queries/nodes/WebVitals/WebVitalsPathBreakdown.tsx
  frontend/src/queries/nodes/WebVitals/WebVitalsProgressBar.tsx
  frontend/src/queries/nodes/WebVitals/WebVitalsTab.scss
  frontend/src/queries/nodes/WebVitals/WebVitalsTab.tsx
  frontend/src/queries/nodes/WebVitals/definitions.ts
  frontend/src/queries/schema.json
  frontend/src/queries/schema/schema-general.ts
  frontend/src/queries/utils.ts
  frontend/src/scenes/appScenes.ts
  frontend/src/scenes/saved-insights/SavedInsights.tsx
  frontend/src/scenes/sceneTypes.ts
  frontend/src/scenes/scenes.ts
  frontend/src/scenes/urls.ts
  frontend/src/scenes/web-analytics/WebAnalyticsHealthCheck.tsx
  frontend/src/scenes/web-analytics/WebDashboard.tsx
  frontend/src/scenes/web-analytics/tiles/WebAnalyticsTile.tsx
  frontend/src/scenes/web-analytics/webAnalyticsLogic.tsx
  posthog/hogql_queries/query_runner.py
  posthog/hogql_queries/web_analytics/test/test_web_vitals_path_breakdown.py
  posthog/hogql_queries/web_analytics/web_analytics_query_runner.py
  posthog/hogql_queries/web_analytics/web_vitals_path_breakdown.py
  posthog/schema.py
Labels: team/web-analytics

#27579 ci: Add a lot more memory to PR previews
  .github/pr-deploy/hobby.yaml.tmpl
Labels: deploy

#27284 chore: upgrade xmlsec and debian
  .devcontainer/Dockerfile
  .devcontainer/library-scripts/docker-in-docker-debian.sh
  .flox/env/manifest.lock
  .flox/env/manifest.toml
  .github/workflows/rust.yml
  Dockerfile
  ee/api/test/test_authentication.py
  requirements.in
  requirements.txt
  rust/Dockerfile
  rust/Dockerfile.migrate-hooks
Labels: deploy

#27709 feat: Add Storybook snapshots for Web Analytics and Web Vitals
  frontend/__snapshots__/queries-webvitals--web-vitals--dark.png
  frontend/__snapshots__/queries-webvitals--web-vitals--light.png
  frontend/__snapshots__/queries-webvitalspathbreakdown--web-vitals-path-breakdown--dark.png
  frontend/__snapshots__/queries-webvitalspathbreakdown--web-vitals-path-breakdown--light.png
  frontend/__snapshots__/scenes-app-web-analytics--web-analytics-dashboard--dark.png
  frontend/__snapshots__/scenes-app-web-analytics--web-analytics-dashboard--light.png
  frontend/__snapshots__/web-analytics-dashboard--web-analytics-dashboard--dark.png
  frontend/__snapshots__/web-analytics-dashboard--web-analytics-dashboard--light.png
  frontend/__snapshots__/web-analytics-tiles--browser--dark.png
  frontend/__snapshots__/web-analytics-tiles--browser--light.png
  frontend/__snapshots__/web-analytics-tiles--path--dark.png
  frontend/__snapshots__/web-analytics-tiles--path--light.png
  frontend/__snapshots__/web-analytics-tiles--referrer-domain--dark.png
  frontend/__snapshots__/web-analytics-tiles--referrer-domain--light.png
  frontend/__snapshots__/web-analytics-tiles--retention--dark.png
  frontend/__snapshots__/web-analytics-tiles--retention--light.png
  frontend/__snapshots__/web-analytics-tiles--world-map--dark.png
  frontend/__snapshots__/web-analytics-tiles--world-map--light.png
  frontend/src/lib/utils/apiHost.ts
  frontend/src/queries/examples.ts
  frontend/src/queries/nodes/WebVitals/WebVitals.stories.tsx
  frontend/src/queries/nodes/WebVitals/WebVitalsPathBreakdown.stories.tsx
  frontend/src/queries/nodes/WebVitals/WebVitalsPathBreakdown.tsx
  frontend/src/queries/nodes/WebVitals/__mocks__/WebVitals.json
  frontend/src/queries/nodes/WebVitals/__mocks__/WebVitalsPathBreakdown.json
  frontend/src/queries/nodes/WebVitals/__mocks__/WebVitalsTrends.json
  frontend/src/scenes/web-analytics/WebAnalyticsDashboard.stories.tsx
  frontend/src/scenes/web-analytics/WebAnalyticsLiveUserCount.tsx
  frontend/src/scenes/web-analytics/__mocks__/UniqueVisitors.json
  frontend/src/scenes/web-analytics/__mocks__/WebOverview.json
  frontend/src/scenes/web-analytics/tiles/WebAnalyticsTile.stories.tsx
  frontend/src/scenes/web-analytics/tiles/__mocks__/Browser.json
  frontend/src/scenes/web-analytics/tiles/__mocks__/Path.json
  frontend/src/scenes/web-analytics/tiles/__mocks__/ReferringDomain.json
  frontend/src/scenes/web-analytics/tiles/__mocks__/Retention.json
  frontend/src/scenes/web-analytics/tiles/__mocks__/WorldMap.json
Labels: team/web-analytics

#27858 chore(ci): try and alert when automerge jobs complete or fail
  .github/workflows/alert-on-failed-automerge.yml
  .github/workflows/automerge.yml
Labels: automerge

#27940 refactor(web-analytics): Remove fully-enabled FFs
  frontend/src/lib/constants.tsx
  frontend/src/scenes/web-analytics/WebAnalyticsDashboard.stories.tsx
  frontend/src/scenes/web-analytics/WebAnalyticsDashboard.tsx
  frontend/src/scenes/web-analytics/webAnalyticsLogic.tsx
Labels: team/web-analytics

#27996 fix: no longer persist Survey editing state
  frontend/src/scenes/surveys/Survey.tsx
Labels: feature/surveys

#28000 fix: adds default value for survey feedback button appearance
  frontend/src/scenes/surveys/constants.tsx
  frontend/src/scenes/surveys/surveyLogic.tsx
Labels: bug

#28010 refactor(web-analytics): Remove Web Vitals from sidebar
  frontend/src/layout/navigation-3000/navigationLogic.tsx
Labels: team/web-analytics

#27880 chore: Add no typegen config for vscode
  .vscode/launch.json
Labels: team-devex

#28021 chore: added lemon tree component and default story
  frontend/__snapshots__/lemon-ui-lemon-tree--default--dark.png
  frontend/__snapshots__/lemon-ui-lemon-tree--default--light.png
  frontend/src/lib/lemon-ui/LemonTree/LemonTree.stories.tsx
  frontend/src/lib/lemon-ui/LemonTree/LemonTree.tsx
  package.json
  pnpm-lock.yaml
  tailwind.config.js
Labels: ux

#28121 chore: add CONTRIBUTING guide to Surveys
  frontend/__snapshots__/scenes-app-insights--funnel-top-to-bottom-breakdown--dark.png
  frontend/src/scenes/surveys/CONTRIBUTING.md
Labels: feature/surveys

#28131 chore: add label to ignore greptile
  greptile.json
Labels: no-greptile

#26282 feat(cdp): add linkedin integration
  frontend/public/services/linkedin.png
  frontend/src/lib/api.ts
  frontend/src/lib/integrations/LinkedInIntegrationHelpers.tsx
  frontend/src/lib/integrations/integrationsLogic.ts
  frontend/src/lib/integrations/linkedInAdsIntegrationLogic.ts
  frontend/src/scenes/pipeline/hogfunctions/integrations/HogFunctionInputIntegrationField.tsx
  frontend/src/types.ts
  greptile.json
  posthog/api/integration.py
  posthog/cdp/templates/__init__.py
  posthog/cdp/templates/linkedin_ads/template_linkedin_ads.py
  posthog/cdp/templates/linkedin_ads/test_template_linkedin_ads.py
  posthog/migrations/0558_alter_integration_kind.py
  posthog/migrations/max_migration.txt
  posthog/models/integration.py
  posthog/settings/integrations.py
Labels: waiting

#28120 refactor: Several toolbar fixes/style changes
  frontend/__snapshots__/scenes-other-toolbar--actions--dark.png
  frontend/__snapshots__/scenes-other-toolbar--actions--light.png
  frontend/__snapshots__/scenes-other-toolbar--actions-dark--dark.png
  frontend/__snapshots__/scenes-other-toolbar--actions-dark--light.png
  frontend/__snapshots__/scenes-other-toolbar--events-debugger-empty--dark.png
  frontend/__snapshots__/scenes-other-toolbar--events-debugger-empty--light.png
  frontend/__snapshots__/scenes-other-toolbar--events-debugger-empty-dark--dark.png
  frontend/__snapshots__/scenes-other-toolbar--events-debugger-empty-dark--light.png
  frontend/__snapshots__/scenes-other-toolbar--experiments--dark.png
  frontend/__snapshots__/scenes-other-toolbar--experiments--light.png
  frontend/__snapshots__/scenes-other-toolbar--experiments-disabled-in-parent--dark.png
  frontend/__snapshots__/scenes-other-toolbar--experiments-disabled-in-parent--light.png
  frontend/__snapshots__/scenes-other-toolbar--feature-flags--dark.png
  frontend/__snapshots__/scenes-other-toolbar--feature-flags--light.png
  frontend/__snapshots__/scenes-other-toolbar--feature-flags-dark--dark.png
  frontend/__snapshots__/scenes-other-toolbar--feature-flags-dark--light.png
  frontend/__snapshots__/scenes-other-toolbar--heatmap--dark.png
  frontend/__snapshots__/scenes-other-toolbar--heatmap--light.png
  frontend/__snapshots__/scenes-other-toolbar--heatmap-dark--dark.png
  frontend/__snapshots__/scenes-other-toolbar--heatmap-dark--light.png
  frontend/src/lib/components/PropertyKeyInfo.scss
  frontend/src/scenes/session-recordings/components/PanelSettings.tsx
  frontend/src/toolbar/bar/Toolbar.scss
  frontend/src/toolbar/bar/Toolbar.tsx
  frontend/src/toolbar/bar/ToolbarMenu.tsx
  frontend/src/toolbar/debug/EventDebugMenu.tsx
  frontend/src/toolbar/debug/eventDebugMenuLogic.ts
  frontend/src/toolbar/elements/ElementInfo.tsx
  frontend/src/toolbar/elements/ElementInfoWindow.tsx
  frontend/src/toolbar/elements/ElementStatistic.tsx
  frontend/src/toolbar/elements/Elements.scss
  frontend/src/toolbar/elements/Elements.tsx
  frontend/src/toolbar/experiments/ExperimentsToolbarMenu.tsx
Labels: feature/toolbar
