Repository PostHog/posthog, pull requests merged in 2025-07, with the labels that each got.

#33117 fix(revenue analytics): Add tooltip for revenue property
  products/revenue_analytics/frontend/settings/EventConfiguration.tsx
Labels: stale

#34557 fix(max): add retry efficiency scorer & resolve unsupported sql function
  .vscode/launch.json
  ee/hogai/eval/conftest.py
  ee/hogai/eval/eval_sql.py
  ee/hogai/eval/scorers.py
  ee/hogai/graph/schema_generator/nodes.py
  ee/hogai/utils/types.py
  posthog/hogql/ai.py
Labels: evals-ready

#34768 fix(max): eval runs after async changes
  ee/hogai/django_checkpoint/checkpointer.py
  ee/hogai/django_checkpoint/test/test_checkpointer.py
  ee/hogai/eval/conftest.py
Labels: evals-ready

#34525 refactor: Remove dead `links` Rust code
  .github/workflows/ci-rust.yml
  frontend/__snapshots__/scenes-app-links--links-list--dark.png
  frontend/__snapshots__/scenes-app-links--links-list--light.png
  posthog/hogql/database/schema/links.py
  products/links/frontend/LinksScene.tsx
  rust/Cargo.lock
  rust/Cargo.toml
  rust/links/.sqlx/query-ca831f6430f5371ad11d3741b99d5451c96af96d9321c3cd56db4a8cb4993f9e.json
  rust/links/Cargo.toml
  rust/links/Readme.MD
  rust/links/src/api/endpoints.rs
  rust/links/src/api/mod.rs
  rust/links/src/config.rs
  rust/links/src/lib.rs
  rust/links/src/main.rs
  rust/links/src/redirect/mod.rs
  rust/links/src/redirect/models.rs
  rust/links/src/redirect/redirect_cache.rs
  rust/links/src/redirect/redirect_query.rs
  rust/links/src/redirect/redirect_service.rs
  rust/links/src/redirect/redis_utils.rs
  rust/links/src/router.rs
  rust/links/src/server.rs
  rust/links/src/utils/generator.rs
  rust/links/src/utils/mod.rs
  rust/links/src/utils/test_utils.rs
  rust/links/tests/helpers/mod.rs
  rust/links/tests/test_redirect.rs
Labels: stale

#35008 fix: change open-ended tag on input
  frontend/src/scenes/surveys/SurveyEditQuestionRow.tsx
Labels: feature/surveys

#31131 chore: upgrade ClickHouse to 25.3.2.39
  .github/actions/run-backend-tests/action.yml
  .github/workflows/ci-backend-update-test-timing.yml
  .github/workflows/ci-backend.yml
  .github/workflows/ci-dagster.yml
  .github/workflows/ci-e2e-playwright.yml
  docker-compose.base.yml
  docker-compose.dev.yml
  ee/clickhouse/models/test/__snapshots__/test_cohort.ambr
  ee/clickhouse/queries/enterprise_cohort_query.py
  ee/clickhouse/queries/test/__snapshots__/test_cohort_query.ambr
  ee/clickhouse/queries/test/test_cohort_query.py
  ee/session_recordings/queries/test/__snapshots__/test_session_recording_list_from_query.ambr
  posthog/clickhouse/test/__snapshots__/test_cluster.ambr
  posthog/hogql/functions/mapping.py
  posthog/hogql_queries/hogql_cohort_query.py
  posthog/queries/foss_cohort_query.py
  posthog/queries/funnels/test/test_funnel_trends.py
  posthog/session_recordings/queries/session_recording_list_from_query.py
  posthog/session_recordings/queries/sub_queries/cohort_subquery.py
  posthog/session_recordings/queries/test/listing_recordings/__snapshots__/test_session_recording_list_from_query.ambr
  posthog/session_recordings/queries/test/listing_recordings/__snapshots__/test_session_recordings_list_by_cohort.ambr
  posthog/session_recordings/queries/test/listing_recordings/__snapshots__/test_session_recordings_list_by_group_properties.ambr
  posthog/settings/service_requirements.py
Labels: waiting

#35037 fix(max): instructed Max not to use relational operators in JOIN
  ee/hogai/eval/eval_tool_generate_hogql_query.py
  posthog/hogql/ai.py
Labels: feature/max-ai

#34304 chore(max): Switch from GPT-4o to 4.1
  ee/hogai/graph/memory/nodes.py
  ee/hogai/graph/root/nodes.py
  ee/surveys/summaries/summarize_surveys.py
  posthog/hogql/ai.py
  posthog/settings/session_replay.py
  products/data_warehouse/backend/hogql_fixer_ai.py
  products/replay/backend/max_tools.py
  pyproject.toml
  uv.lock
Labels: evals-ready

#34547 feat(capture): set up mirror deploy to observe /i/v0 events w/legacy handling
  rust/capture/src/config.rs
  rust/capture/src/router.rs
Labels: waiting

#33111 feat: surveys on Max AI
  ee/hogai/eval/eval_surveys.py
  frontend/src/queries/schema.json
  frontend/src/queries/schema/index.ts
  frontend/src/queries/schema/schema-assistant-messages.ts
  frontend/src/queries/schema/schema-surveys.ts
  frontend/src/scenes/max/maxGlobalLogic.tsx
  frontend/src/scenes/surveys/SurveySettings.tsx
  frontend/src/scenes/surveys/Surveys.tsx
  frontend/src/scenes/surveys/constants.tsx
  frontend/src/scenes/surveys/utils.ts
  frontend/src/types.ts
  posthog/constants.py
  posthog/schema.py
  products/surveys/__init__.py
  products/surveys/backend/__init__.py
  products/surveys/backend/max_tools.py
  products/surveys/backend/prompts.py
  products/surveys/backend/test_max_tools.py
Labels: feature/surveys, feature/max-ai

#34867 feat: Backend logic for personal API key restriction
  frontend/__snapshots__/scenes-app-settings-environment--settings-environment-surveys--dark.png
  frontend/__snapshots__/scenes-app-settings-project--settings-project-surveys--dark.png
  frontend/src/lib/constants.tsx
  frontend/src/scenes/settings/organization/Members.tsx
  posthog/api/organization.py
  posthog/api/test/test_personal_api_keys.py
  posthog/constants.py
  posthog/permissions.py
Labels: stale

#35503 fix(max): shared attributes between nodes and tools
  ee/hogai/assistant.py
  ee/hogai/eval/eval_surveys.py
  ee/hogai/eval/max_tools/eval_hogql_generator_tool.py
  ee/hogai/graph/base.py
  ee/hogai/graph/mixins.py
  ee/hogai/graph/root/nodes.py
  ee/hogai/graph/root/test/test_nodes.py
  ee/hogai/graph/test/test_mixins.py
  ee/hogai/tool.py
  mypy-baseline.txt
  products/data_warehouse/backend/api/fix_hogql.py
  products/data_warehouse/backend/test/test_max_tools.py
  products/surveys/backend/test_max_tools.py
Labels: evals-ready

#35450 refactor(max): Use team taxonomy for events
  ee/hogai/eval/eval_tool_filter_generation.py
  ee/hogai/graph/filter_options/nodes.py
  ee/hogai/graph/filter_options/prompts.py
  ee/hogai/graph/filter_options/test/test_nodes.py
  ee/hogai/graph/filter_options/toolkit.py
  ee/hogai/graph/filter_options/types.py
  ee/hogai/graph/query_planner/nodes.py
  ee/hogai/graph/query_planner/test/test_nodes.py
  ee/hogai/utils/helpers.py
  ee/hogai/utils/test/test_format_events_prompt.py
  products/replay/backend/prompts.py
Labels: evals-ready

#35552 chore(max): Make AI evals baseline clearer
  .github/workflows/ci-ai.yml
Labels: evals-ready

#35654 chore: add debug and move some scripts in external surveys
  posthog/api/test/test_external_surveys.py
  posthog/templates/surveys/public_survey.html
Labels: feature/surveys

#35663 fix: no overwriting caddyfile in hobby install
  bin/deploy-hobby
  docker-compose.base.yml
  docker-compose.hobby.yml
Labels: hobby-self-host

#35674 fix: hobby caddy templating
  bin/deploy-hobby
  docker-compose.hobby.yml
Labels: hobby-self-host

#35689 fix: docker compose caddy routing
  docker-compose.base.yml
Labels: hobby-self-host

#35843 fix: skeleton loading for survey questions with scale 10
  frontend/src/scenes/surveys/components/question-visualizations/SurveyQuestionVisualization.tsx
Labels: feature/surveys

#35937 fix: don't add `project/{projectId}` to URL if `project/{projectApiKey}` is already in URL
  frontend/src/lib/utils/router-utils.test.ts
  frontend/src/lib/utils/router-utils.ts
Labels: bug

#35963 chore: use array.full.js when loading the SDK on external surveys
  posthog/templates/surveys/public_survey.html
Labels: feature/surveys

#34807 feat(revenue-analytics): Revenue Analytics person virtual revenue properties - the empire strikes back
  frontend/__snapshots__/scenes-app-data-management--revenue-analytics-settings--dark.png
  frontend/__snapshots__/scenes-app-data-management--revenue-analytics-settings--light.png
  frontend/__snapshots__/scenes-app-settings-environment--settings-environment-revenue-analytics--dark.png
  frontend/__snapshots__/scenes-app-settings-environment--settings-environment-revenue-analytics--light.png
  frontend/src/lib/components/HogQLDropdown/HogQLDropdown.tsx
  frontend/src/queries/schema.json
  frontend/src/queries/schema/schema-general.ts
  frontend/src/scenes/data-warehouse/ViewLinkModal.tsx
  frontend/src/scenes/data-warehouse/editor/editorSceneLogic.tsx
  frontend/src/scenes/data-warehouse/viewLinkLogic.tsx
  frontend/src/scenes/web-analytics/WebAnalyticsDashboard.stories.tsx
  frontend/src/taxonomy/core-filter-definitions-by-group.json
  frontend/src/types.ts
  posthog/api/services/query.py
  posthog/api/test/test_property_definition.py
  posthog/hogql/database/database.py
  posthog/hogql/database/schema/persons.py
  posthog/hogql/database/schema/revenue_analytics.py
  posthog/hogql/database/schema/test/__snapshots__/test_revenue_analytics.ambr
  posthog/hogql/database/schema/test/test_persons.py
  posthog/hogql/database/schema/test/test_revenue_analytics.py
  posthog/hogql/database/test/__snapshots__/test_database.ambr
  posthog/hogql/test/__snapshots__/test_resolver.ambr
  posthog/hogql/test/test_property.py
  posthog/schema.py
  posthog/session_recordings/test/__snapshots__/test_session_recordings.ambr
  posthog/taxonomy/taxonomy.py
  posthog/warehouse/models/datawarehouse_saved_query.py
  posthog/warehouse/models/join.py
  products/revenue_analytics/backend/hogql_queries/revenue_example_data_warehouse_tables_query_runner.py
  products/revenue_analytics/backend/hogql_queries/revenue_example_events_query_runner.py
  products/revenue_analytics/backend/hogql_queries/test/__snapshots__/test_revenue_analytics_customer_count_query_runner.ambr
  products/revenue_analytics/backend/hogql_queries/test/__snapshots__/test_revenue_analytics_growth_rate_query_runner.ambr
  products/revenue_analytics/backend/hogql_queries/test/__snapshots__/test_revenue_analytics_metrics_query_runner.ambr
  products/revenue_analytics/backend/hogql_queries/test/__snapshots__/test_revenue_analytics_overview_query_runner.ambr
  products/revenue_analytics/backend/hogql_queries/test/__snapshots__/test_revenue_analytics_revenue_query_runner.ambr
  products/revenue_analytics/backend/hogql_queries/test/__snapshots__/test_revenue_analytics_top_customers_query_runner.ambr
  products/revenue_analytics/backend/hogql_queries/test/__snapshots__/test_revenue_example_events_query_runner.ambr
  products/revenue_analytics/backend/hogql_queries/test/test_revenue_analytics_growth_rate_query_runner.py
  products/revenue_analytics/backend/hogql_queries/test/test_revenue_analytics_overview_query_runner.py
  products/revenue_analytics/backend/hogql_queries/test/test_revenue_analytics_revenue_query_runner.py
  products/revenue_analytics/backend/hogql_queries/test/test_revenue_analytics_top_customers_query_runner.py
  products/revenue_analytics/backend/hogql_queries/test/test_views.py
  products/revenue_analytics/backend/test/test_revenue_analytics_base_view.py
  products/revenue_analytics/backend/views/revenue_analytics_base_view.py
  products/revenue_analytics/backend/views/revenue_analytics_charge_view.py
  products/revenue_analytics/backend/views/revenue_analytics_customer_view.py
  products/revenue_analytics/backend/views/revenue_analytics_invoice_item_view.py
  products/revenue_analytics/backend/views/revenue_analytics_product_view.py
  products/revenue_analytics/backend/views/revenue_analytics_subscription_view.py
  products/revenue_analytics/frontend/__mocks__/DatabaseSchemaQuery.json
  products/revenue_analytics/frontend/settings/ExternalDataSourceConfiguration.tsx
  products/revenue_analytics/frontend/settings/RevenueAnalyticsSettings.stories.tsx
  products/revenue_analytics/frontend/settings/revenueAnalyticsSettingsLogic.ts
Labels: stale
