Repository PostHog/posthog, pull requests merged in 2025-10, with the labels that each got.

#38536 chore(max): increase export timeouts in dagster
  dags/max_ai/snapshot_team_data.py
  posthog/hogql_queries/ai/actors_property_taxonomy_query_runner.py
  posthog/hogql_queries/ai/event_taxonomy_query_runner.py
  posthog/hogql_queries/ai/team_taxonomy_query_runner.py
Labels: stale

#38933 feat(max): tool groups
  .github/workflows/ci-ai.yml
  ee/hogai/context/context.py
  ee/hogai/eval/ci/conftest.py
  ee/hogai/eval/ci/eval_root.py
  ee/hogai/graph/base.py
  ee/hogai/graph/billing/nodes.py
  ee/hogai/graph/billing/test/test_nodes.py
  ee/hogai/graph/inkeep_docs/nodes.py
  ee/hogai/graph/inkeep_docs/test/test_nodes.py
  ee/hogai/graph/memory/prompts.py
  ee/hogai/graph/query_planner/nodes.py
  ee/hogai/graph/query_planner/prompts.py
  ee/hogai/graph/root/nodes.py
  ee/hogai/graph/root/prompts.py
  ee/hogai/graph/root/test/test_nodes.py
  ee/hogai/graph/root/tools/__init__.py
  ee/hogai/graph/root/tools/legacy.py
  ee/hogai/graph/root/tools/navigate.py
  ee/hogai/graph/root/tools/read.py
  ee/hogai/graph/root/tools/read_taxonomy.py
  ee/hogai/graph/root/tools/search.py
  ee/hogai/graph/root/tools/todo_write.py
  ee/hogai/graph/sql/mixins.py
  ee/hogai/test/test_assistant.py
  ee/hogai/tool.py
  frontend/src/queries/schema.json
  frontend/src/queries/schema/schema-assistant-messages.ts
  posthog/schema.py
  products/product_analytics/backend/max_tools.py
Labels: evals-ready

#39196 fix(max): max memory fixes
  ee/hogai/eval/ci/eval_memory.py
  ee/hogai/graph/memory/prompts.py
Labels: feature/max-ai, evals-ready

#38489 feat(max): allow multiple property value search
  ee/hogai/graph/taxonomy/format.py
  ee/hogai/graph/taxonomy/nodes.py
  ee/hogai/graph/taxonomy/test/test_entities.py
  ee/hogai/graph/taxonomy/test/test_events.py
  ee/hogai/graph/taxonomy/test/test_groups.py
  ee/hogai/graph/taxonomy/test/test_nodes.py
  ee/hogai/graph/taxonomy/test/test_toolkit.py
  ee/hogai/graph/taxonomy/toolkit.py
  ee/session_recordings/queries/test/__snapshots__/test_session_recording_list_from_query.ambr
  products/error_tracking/backend/max_tools.py
  products/revenue_analytics/backend/max_tools.py
  products/surveys/backend/max_tools.py
Labels: evals-ready
